### ISSUE TITLE
Power sensors not included with state: "> 0"

### ISSUE THREAD

**Issue by hulkhaugen** [thomasloven/lovelace-auto-entities#1]
Trying to replace monster-card with this one, and all but one card works as I hoped.

```
cards:
  - entity: sensor.electricity_price
    max: 1.6
    min: 0
    name: Strømpris
    severity:
      green: 0
      red: 1
      yellow: 0.65
    type: gauge
    unit: kr
  - card:
      show_header_toggle: false
      type: entities
    filter:
      include:
        - entity_id: sensor.*power*
          state: '> 0'
    type: 'custom:auto-entities'
title: Strømforbruk
type: 'custom:vertical-stack-in-card'
```
If I remove the include->state line, all the entities shows up, but I only want the entities with values greater than 0.0 to show up. Could it be related to the UoM? Not sure, it works with MonsterCard.

**Comment by hulkhaugen** [comment]
It works when I do it like this:

```
cards:
  - entity: sensor.electricity_price_sagmesterveien_6
    max: 1.6
    min: 0
    name: Strømpris
    severity:
      green: 0
      red: 1
      yellow: 0.65
    type: gauge
    unit: kr
  - card:
      show_header_toggle: false
      type: entities
    filter:
      exclude:
        - state: '0.0'
      include:
        - entity_id: sensor.*power*
    type: 'custom:auto-entities'
title: Strømforbruk
type: 'custom:vertical-stack-in-card'
```
