### ISSUE TITLE
Using a custom card for each single entity

### ISSUE THREAD

**Issue by gcorgnet** [thomasloven/lovelace-auto-entities#10]
Hi, I have made a small change so that I can use an "entities" card but use a custom card to represent each separate entity being rendered, 
For example, I am using it with custom:slider-entity-row so that I can have a slider on my list of Lights that are currently on.
Happy to submit a PR, but I currently don;t have permission to create a branch, Cheers

![image](https://user-images.githubusercontent.com/4731735/54181615-ff2f0200-4503-11e9-94e3-c4f326a7d4a6.png)

**Comment by thomasloven** [comment]
This is already supported
```yaml
type: custom:auto-entities
card:
  type: entities
  title: Lights on
filter:
  include:
    - domain: light
      state: 'on'
      options:
        type: 'custom:slider-entity-row'
        toggle: true
    ... etc ...
```
