### ISSUE TITLE
Use regex in attributes

### ISSUE THREAD

**Issue by eloo** [thomasloven/lovelace-auto-entities#104]
Hi,
i'm just struggling around to get the filtering to work with regex in attributes..
Currently it looks like this:
``` 
        filter:
          include:  
            - domain: sensor
              attributes:
                product_id: "/.*/"
```
and the idea is to just filter for sensors which have this attribute set.
But with this "regex" its not working but with the actual values its working.

So i'm not sure if regex should work for attributes this way?
Maybe you can help me with this.

Thanks
eloo
