### ISSUE TITLE
Columns doesn't work in HA 0.108

### ISSUE THREAD

**Issue by fribse** [thomasloven/lovelace-auto-entities#106]
Hi Thomas et al.

auto-entities v.16
HA 0.108

I've this card set up:
```
card:
  align: left
  columns: 2
  padding: 2px
  severity:
    - color: '#bf4040'
      value: 10
    - color: '#bf9540'
      value: 30
    - color: '#40bf40'
      value: 100
  title_position: inside
  title_style:
    font-size: 16px
  type: 'custom:bar-card'
  value_style:
    font-size: 8px
filter:
  exclude:
    - entity_id: '*mobil*'
    - entity_id: '*h8*'
  include:
    - entity_id: '*_battery'
    - entity_id: '*_battery_level'
type: 'custom:auto-entities'
```

After upgrading to 0.108 from 0.107.7 all the auto-entities are shown in one long column.
