### ISSUE TITLE
Filter by "device" not working

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-auto-entities#109]
I'm trying to filter entities based on a device.
Code:

```
card:
  show_header_toggle: false
  title: SmartTv
  type: entities
filter:
  include:
    - entity_id: switch.samsung_ocf_tv
    - entity_id: media_player.smart_tv
    - entity_id: sensor.samsung_ocf_tv_tv_channel
    - entity_id: sensor.samsung_ocf_tv_media_input_source
  exclude:
    - state: 'off'
      device: /samsung_ocf_tv/
      not:
        entity_id: switch.samsung_ocf_tv
type: 'custom:auto-entities'
```

media_player is correctly hidden when "off".
I would like to hide also "tv_channel" and "tv_media_input_source" but not switch when switch is off.

I tried using both device name (SAMSUNG OCF TV) and device substring (samsung_ocf_tv); both without luck.

Simone
