### ISSUE TITLE
Feature request: Automatically remove part of the entity name

### ISSUE THREAD

**Issue by sildehoop** [thomasloven/lovelace-auto-entities#110]
I name my entities in what room is they are, but it is very ugly in cards and unnecessary
<img width="495" alt="Schermafbeelding 2020-05-04 om 11 28 27" src="https://user-images.githubusercontent.com/34340385/80952727-6b508180-8dfa-11ea-95a6-0e83887bed94.png">
<img width="493" alt="Schermafbeelding 2020-05-04 om 11 28 35" src="https://user-images.githubusercontent.com/34340385/80952720-668bcd80-8dfa-11ea-99e6-e8132c8bcb98.png">

**Comment by oxan** [comment]
#103 would fix this.

**Comment by saarsinai** [comment]
would love to see this feature as well!

**Comment by thomasloven** [comment]
Auto-entities can't and shouldn't do everything, but it can be combined with something that does
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: switch*
      options:
        type: custom:some-custom-row-type-which-supports-the-wanted-functionality
```

**Comment by saarsinai** [comment]
what worked for me after @thomasloven suggestions!
used he's other custom component (installed from hacs also) `custom:template-entity-row`

then used the template ability in name field to remove static text from the name,

have fun.
@sildehoop 
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: light.*some*filter
      options:
        type: custom:template-entity-row
        name: >
          {{ state_attr(config.entity, 'friendly_name') | replace('Living Room Light', '') }}
```

**Comment by bcutter** [comment]
That doesn´t work as expected, as everything else changes:
- state_color is missing
- secondary information last_triggered is shown in absolute
- toggle switch is missing, instead state text is give

Before (without 'custom:template-entity-row'):
![grafik](https://user-images.githubusercontent.com/13799156/112700612-d54c9c00-8e8e-11eb-8cd1-48d13ae777ae.png)

After (cutting "Switch-Control_Switch", best/closest I could get):
![grafik](https://user-images.githubusercontent.com/13799156/112700570-c1a13580-8e8e-11eb-8f8f-01cc6f9b756c.png)

I therefore strongly vote for a native implementation in auto-entities as config option, see https://github.com/thomasloven/lovelace-auto-entities/issues/166

**Comment by slovdahl** [comment]
These two problems can be solved at least:

> - state_color is missing
> - toggle switch is missing, instead state text is give

Add `toggle` and `active` like this:

```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: light.*some*filter
      options:
        type: custom:template-entity-row
        name: "{{ state_attr(config.entity, 'friendly_name') | replace('Living Room Light', '') }}"
        toggle: true
        active: "{{ is_state(config.entity, 'on') }}"
```

And getting the right secondary state is probably doable too using the `secondary` field, see https://github.com/thomasloven/lovelace-template-entity-row#options for more information.

**Comment by bcutter** [comment]
> And getting the right secondary state is probably doable too using the `secondary` field, see https://github.com/thomasloven/lovelace-template-entity-row#options for more information.

Best I could make out of the original...
![grafik](https://user-images.githubusercontent.com/13799156/185770724-42bcdc4b-9756-4b2d-a7ae-711ef65e2432.png)

...by using template-entity-row is this:
![grafik](https://user-images.githubusercontent.com/13799156/185770663-535874d7-2f35-4c41-9580-031159c55fbc.png)

...by using these options:
```
          options:
            secondary: >
              {{ state_attr(config.entity, 'last_triggered') | relative_time }}
            type: custom:template-entity-row
            name: >
              {{ state_attr(config.entity, 'friendly_name') | replace('Switch-Control_', '') }}
            toggle: true
            active: "{{ is_state(config.entity, 'on') }}"
```

How to convert the e. g. "2 hours" back to the local language format "Vor 2 Stunden"? The output of `relative_time` stays in English unfortunately :-(

**Comment by ildar170975** [comment]
There are plenty of possible use-cases - but all of them are covered by `template` option.
And yes, a user must LEARN how to do it.
Otherwise it would be 100500 new options - just to cover some special use-case.

Anyway, this is an Open Source project.
Everyone make add possible efforts & propose it's own implementation.

**Comment by neuhausj** [comment]
Is this topic still active ?

It would be really useful to have something similar to "bulk_rename" from battery_state ( https://github.com/maxwroc/battery-state-card#entity-filtering-and-bulk-renaming )

Ex:
![image](https://github.com/user-attachments/assets/139cfd0b-8c4f-4c20-8c57-6121530ddaf0)

**Comment by bcutter** [comment]
That's not new. It did not happen in the last almost 5 years. It will not happen in the next five years. It's simply way too difficult to adopt a feature which is already available in a similar integration.

**Comment by dcapslock** [comment]
You can use the undocumented (for now) `eval_js` option. This simply takes a JSON stringified version of the resulting list with options, and runs eval() across it, before parsing JSON back for final output. This allows simple `${}` javascript expressions through which you can do your bulk rename.

e.g.

```yaml
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - options:
        eval_js: true
        name: >-
          ${state.attributes.friendly_name.replace('Lights','').replace('Light','').trim()
          }
      area: kitchen
  exclude: []
```
