### ISSUE TITLE
media-control as a card type is not working

### ISSUE THREAD

**Issue by vlebourl** [thomasloven/lovelace-auto-entities#111]
using `type: media-control` and filtering for `entity_id: "media_player.*"`yields the following error:

```
Specify an entity from within the media_player domain.
entities:
  - entity: media_player.plex_plex_web_opera_osx
  - entity: media_player.plex_plex_web_chrome_windows
  - entity: media_player.plex_plex_for_android_tv_bravia_4k_gb_atv3
  - entity: media_player.plex_plex_for_android_mobile_pixel_4
  - entity: media_player.plex_plex_web_chrome_osx
  - entity: media_player.plex_plex_web_opera_osx
type: media-control
 ```
