### ISSUE TITLE
FR: Add ability to filter by config_entry_id ID

### ISSUE THREAD

**Issue by poldim** [thomasloven/lovelace-auto-entities#114]
Similar to the other filters, add filtering for `config_entry_id` as identified for integrations.

The syntax would work the same way as your other filters:
```
      - type: custom:auto-entities
        ...
        filter:
          include:
            - config_entry_id: b116ccef16ef4952ae0307b767202ec4
```

<img width="918" alt="Configuration - Home Assistant 2020-05-17 09-51-42" src="https://user-images.githubusercontent.com/16869713/82154707-76f16e80-9824-11ea-99c8-63e17dd523d2.png">

<img width="821" alt="Configuration - Home Assistant 2020-05-17 09-58-18" src="https://user-images.githubusercontent.com/16869713/82154773-0e56c180-9825-11ea-8cf1-5e4833327e3f.png">

This is listed with each entity in the `.storage/core.entity_registry`:

<img width="886" alt="docker 2020-05-17 10-03-54" src="https://user-images.githubusercontent.com/16869713/82154891-c7b59700-9825-11ea-9683-2f892b171918.png">

BTW, I tried using the device filter to see if it also checked those fields and it gave me an empty card:
```
      - type: custom:auto-entities
        title: Device filter test
        card:
          type: entities
        filter:
          include:
            - device: 042fab06aea44aa8999013e5f379b3bd*
            - device: 042fab06aea44aa8999013e5f379b3bd
            - device: a1a155e82eda4a6a92343d0c2dc015f1*
            - device: a1a155e82eda4a6a92343d0c2dc015f1
```
