### ISSUE TITLE
Getting "too much recursion" after upgrading to 1.10

### ISSUE THREAD

**Issue by sstratoti** [thomasloven/lovelace-auto-entities#115]
```
arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Core on Docker
os_name | Linux
os_version | 5.3.0-51-generic
python_version | 3.7.7
timezone | America/New_York
version | 0.110.1
virtualenv | false
```

I have this error message on my main lovelace page.
I'm using Firefox 76.0.1 (64-bit) 

```
too much recursion

card:
  attribute: battery_level
  columns: 1
  height: 25px
  positions:
    icon: 'off'
    indicator: inside
    name: outside
  severity:
    - color: '#FF0000'
      from: 1
      to: 10
    - color: '#ff6600'
      from: 11
      to: 20
    - color: '#ff9933'
      from: 21
      to: 30
    - color: '#ffcc00'
      from: 31
      to: 40
    - color: '#ffdb60'
      from: 41
      to: 50
    - color: '#ffdb60'
      from: 51
      to: 60
    - color: '#ffdb60'
      from: 61
      to: 70
    - color: '#CCFF33'
      from: 71
      to: 80
    - color: '#66FF33'
      from: 81
      to: 90
    - color: '#279b37'
      from: 91
      to: 100
  style: |-
    bar-card-value {
      margin-right: auto;
      font-size: 13px;
      font-weight: bold;
      text-shadow: 1px 1px #0005;
    }
  type: 'custom:bar-card'
  unit_of_measurement: '%'
  width: 60%
filter:
  include:
    - attributes:
        battery_level: <=30
type: 'custom:auto-entities'
```
Do I have my card set up wrong somehow? It's been working fine for a while now. Could it be an issue with the custom bar-card?
