### ISSUE TITLE
Feature request: Support footer with button rows

### ISSUE THREAD

**Issue by drew-kun** [thomasloven/lovelace-auto-entities#116]
Hi! I am struggling with some specific task and I have no clue how to achieve this without this feature.

The ha `entities` card supports the [footer feature](https://www.home-assistant.io/lovelace/header-footer/), therefore it is easy to do something like this (note those 4 buttons at the bottom of the card):

![Screen Shot 2020-05-24 at 1 32 02 PM](https://user-images.githubusercontent.com/10493450/82760090-0a650980-9dfa-11ea-9b34-af75d8fd923b.png)
The code I use is something like:

```yaml
  cards:
  - type: entities
    title: Lights
    entities:
    - light.kitchen_intelite
    - type: custom:auto-entities
      show_empty: false
      card:
        type: entities
        show_header_toggle: false
      filter:
        template: |
          {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
            input_number.kitchen_intelite_brightness
            input_number.kitchen_intelite_temperature
          {% endif %}
          {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
           input_number.kitchen_intelite_brightness_dark_mode
          {% endif %}

    footer:
      type: buttons
      entities:
      - entity: switch.kitchen_intelite_mourn_mode
      - entity: switch.kitchen_intelite_noon_mode
      - entity: switch.kitchen_intelite_eve_mode
      - entity: switch.kitchen_intelite_dark_mode
```
The problem here is that I use the `auto-entities` card within the `entities` card (which supports footer option) in order to blend the buttons at the botton into the setup, but the entities-card has this shadow around it, which I want also to get rid of... So basically I want the whole picture to be flat, without any borders or shadows

Another option I tried is to use `custom:paper-buttons-row`:
![Screen Shot 2020-05-24 at 8 07 56 PM](https://user-images.githubusercontent.com/10493450/82760298-48aef880-9dfb-11ea-9813-f768416acc54.png)

This setup allows to unify the light with conditional sliders, but there is no way to unify the bottom button row with them (see, they are outside of the card now). The code is here:

```yaml
cards:
- type: vertical-stack
  title: Kitchen Controls
  cards:
  - type: custom:auto-entities
    title: Lights
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
    entities:
    - light.kitchen_intelite
    filter:
      template: |
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
          input_number.kitchen_intelite_brightness
          input_number.kitchen_intelite_temperature
        {% endif %}
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
         input_number.kitchen_intelite_brightness_dark_mode
        {% endif %}
  - type: custom:paper-buttons-row
    buttons:
    - entity: switch.kitchen_intelite_mourn_mode
      name: false
    - entity: switch.kitchen_intelite_noon_mode
      name: false
    - entity: switch.kitchen_intelite_eve_mode
      name: false
    - entity: switch.kitchen_intelite_dark_mode
      name: false
```
This obviously did not solve the problem...

It simply would be great to have the same `footer` feature support (or something similar) in this auto-entities card. This would help to have kind of solid flat-looking card with conditionally appearing sliders and buttons nicely.

So, for example, the code to achieve what I described could have been as simple as the following (kind of combination of two listed above... as an option):

```yaml
cards:
- type: vertical-stack
  title: Kitchen Controls
  cards:
  - type: custom:auto-entities
    title: Lights
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
    entities:
    - light.kitchen_intelite
    filter:
      template: |
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
          input_number.kitchen_intelite_brightness
          input_number.kitchen_intelite_temperature
        {% endif %}
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
         input_number.kitchen_intelite_brightness_dark_mode
        {% endif %}

    footer:
      type: buttons
      entities:
      - entity: switch.kitchen_intelite_mourn_mode
      - entity: switch.kitchen_intelite_noon_mode
      - entity: switch.kitchen_intelite_eve_mode
      - entity: switch.kitchen_intelite_dark_mode
```

**Comment by danlun** [comment]
You made a really nice looking card here, great!! So I agree 100% yes pls lets have what you wish for!!!

**Comment by KTibow** [comment]
Haven't tried this out yet, but you might be able to do this with [card-mod](https://github.com/thomasloven/lovelace-card-mod):
```yaml
cards:
  - type: entities
    title: Lights
    entities:
    - light.kitchen_intelite
    - type: custom:auto-entities
      show_empty: false
      card:
        type: entities
        show_header_toggle: false
      filter:
        template: |
          {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
            input_number.kitchen_intelite_brightness
            input_number.kitchen_intelite_temperature
          {% endif %}
          {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
           input_number.kitchen_intelite_brightness_dark_mode
          {% endif %}
      style: |
        ha-card {
          box-shadow: unset;
        }

    footer:
      type: buttons
      entities:
      - entity: switch.kitchen_intelite_mourn_mode
      - entity: switch.kitchen_intelite_noon_mode
      - entity: switch.kitchen_intelite_eve_mode
      - entity: switch.kitchen_intelite_dark_mode
type: entities
```

**Comment by WhistleMaster** [comment]
You could also use conditional row, something like that:

```
entities:
  - entity: light.kitchen_intelite
  - type: conditional
    conditions:
      - entity: light.kitchen_intelite
        state: 'on'
    row:
      entity: input_number.kitchen_intelite_brightness
  - type: conditional
    conditions:
      - entity: light.kitchen_intelite
        state: 'on'
    row:
      entity: input_number.kitchen_intelite_temperature
  - type: conditional
    conditions:
      - entity: light.kitchen_intelite
        state: 'on'
    row:
      type: 'custom:paper-buttons-row'
      buttons:
        - entity: switch.kitchen_intelite_mourn_mode
        - entity: switch.kitchen_intelite_noon_mode
        - entity: switch.kitchen_intelite_eve_mode
        - entity: switch.kitchen_intelite_dark_mode
title: Lights
type: entities
```

**Comment by drew-kun** [comment]
@WhistleMaster thank you very much for that... Your solution looks pretty, although, at the end of a day, I have achieved what I wanted this way:

```yaml
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Lights
      show_header_toggle: false
    entities:
    - light.kitchen_intelite
    - type: custom:paper-buttons-row
      buttons:
      - entity: switch.kitchen_intelite_mourn_mode
        name: false
      - entity: switch.kitchen_intelite_noon_mode
        name: false
      - entity: switch.kitchen_intelite_eve_mode
        name: false
      - entity: switch.kitchen_intelite_dark_mode
        name: false
    filter:
      template: |
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','off')%}
          input_number.kitchen_intelite_brightness
          input_number.kitchen_intelite_temperature
        {% endif %}
        {% if is_state('light.kitchen_intelite','on') and is_state('switch.kitchen_intelite_dark_mode','on')%}
          input_number.kitchen_intelite_brightness_dark_mode
        {% endif %}
```
So closing.. Thank you all!
