### ISSUE TITLE
Filter adds entities that should be excluded

### ISSUE THREAD

**Issue by DavidFW1960** [thomasloven/lovelace-auto-entities#12]
I have a card configured like this:
```
          - type: entities
            title: Automations & Scenes
            show_header_toggle: false
            entities: 
              - type: custom:auto-entities
                card:
                  type: custom:fold-entity-row
                  head:
                    type: section
                    label: All Automations
                  open: false
                filter:
                  include:
                    - entity_id: "automation.*"
              - type: custom:auto-entities
                card:
                  type: custom:fold-entity-row
                  head:
                    type: section
                    label: Scenes
                  open: false
                filter:
                  include:
                    - entity_id: "scene.*"
```
Which looks like this:
![image](https://user-images.githubusercontent.com/36390762/54650538-17ee7780-4b03-11e9-8a2e-bc87b0fc0301.png)

Exactly what I want.

However, it is showing 
group.all_automations
group.scenes

Neither of those match the pattern......
