### ISSUE TITLE
include filter on custom time attribute

### ISSUE THREAD

**Issue by golles** [thomasloven/lovelace-auto-entities#120]
Hi Thomas, thank you for this great card!

I'm using the [p2000](https://github.com/cyberjunky/home-assistant-p2000) sensor which has a `time` attribute (sample value: `'2020-06-12T20:44:43'`) which I would like to run a time filter against, like with `last_changed` to only show the entity when that time isn't older than one hour.

Would it be possible to do this with `include` `attributes`? I couldn't find a way of doing this.

Would this be worth a feature or will this be too specific?

**Comment by thomasloven** [comment]
Dupplicate of #78

**Comment by golles** [comment]
Sorry @thomasloven, haven't seen issue #7 
I've managed to do a workaround like this:
```
  - type: 'custom:auto-entities'
    show_empty: false
    card:
      title: P2000 dichtbij
      type: entities
    filter:
      template: |
       {%if as_timestamp(now()) <= as_timestamp(state_attr('sensor.p2000_dichtbij', 'time')) + 7200 %}sensor.p2000_dichtbij{%endif%}
```
