### ISSUE TITLE
Unique does not remove duplicate entity if passing an options icon

### ISSUE THREAD

**Issue by nchieffo** [thomasloven/lovelace-auto-entities#121]
This is my lovelace code

```
type: 'custom:auto-entities'
card:
  type: entities
  title: Media players
filter:
  include:
    - entity_id: media_player.tv_lg_55lm660s
      options:
        icon: 'mdi:television'
    - domain: media_player
      state: playing
unique: true
```

The does `unique: true` option not remove `media_player.tv_lg_55lm660s` from the entity list generated by `domain: media_player`.
Instead if I remove the `icon: 'mdi:television'` code, the entity is removed correctly
