### ISSUE TITLE
Allow for Multiple Not: in filter

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#123]
I'm trying to make a card that lists all my contact sensors in one card, windows, doors, etc and I want to sort them by type and by name at the same time. I've got 90% of it sorted, but one last bit is getting me stuck. I have a sensor in my mailbox that I want to exclude from my door sensors section, and add in at the bottom on its own. If I try to do multiple not's, it ignores them completely and it doesn't work. A single not: works fine. If I could sort based on multiple options that would work as well. 

I'm trying to list my doors first, security system zones second, then my garage doors, then mailbox and finally closet doors. The issue is that the mailbox and closet doors are covered by the binary_sensor.*_door_sensor filter. Please let me know if you have a clever way to get the functionality I am looking for.

```
card:
  columns: 3
  show_state: false
  title: Windows and Doors
  type: glance
filter:
  include:
    - entity_id: binary_sensor.*_door_sensor
      not:
        - entity_id: binary_sensor.*_closet_door_sensor
         - entity_id: binary_sensor.mailbox_door_sensor
      sort:
        method: name
    - entity_id: binary_sensor.zone_*
      sort:
        method: name
    - entity_id: cover.*_garage_door
      sort:
        method: name
    - entity_id: binary_sensor.mailbox_door_sensor
    - entity_id: binary_sensor.*closet_door_sensor
type: 'custom:auto-entities'

```
