### ISSUE TITLE
How to append non-entity to end?

### ISSUE THREAD

**Issue by KTibow** [thomasloven/lovelace-auto-entities#124]
I use auto-entities with a footer at the bottom. It's kind of close though, so I want to use a `type: section`. Anybody know how I could try to do this? Would I need a fake entity?

**Comment by KTibow** [comment]
Never mind, I did this:
```yaml
  include:
    - type: section
      label: Birdcam sensors
    - entity_id: '*birdcam*'
    - name: '*Birdcam*'
    - type: section
      label: Light graph
```
Here's the whole code for anyone interested:
<details><summary>Expand</summary>

```yaml
card:
  show_header_toggle: false
  style: |
    ha-card {
        background-color: var(--primary-background-color);
        border-radius: 15px;
        margin: 20px;
        box-shadow: {% if is_state('sun.sun', 'above_horizon') %}-8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
          {% else %}-8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);{% endif %}
     }
  type: entities
  footer:
    type: graph
    entity: sensor.filtered_light_level
    detail: 2
filter:
  exclude:
    - domain: camera
  include:
    - type: section
      label: Birdcam sensors
    - entity_id: '*birdcam*'
    - name: '*Birdcam*'
    - type: section
      label: Light graph
type: 'custom:auto-entities'
unique: true
```

</details>
