### ISSUE TITLE
Cannot read property 'state' of undefined 

### ISSUE THREAD

**Issue by rbflurry** [thomasloven/lovelace-auto-entities#126]
I use the following config to show me a list of entities (lights and switches) but only if they are not unavailable. However while home assistant starts up or if an integration fails to start it results in the following error on the GUI because and entity in the list does not exist and therefor does not have a "state"

I am a missing a fix for this?

Cannot read property 'state' of undefined
```
card:
  show_header_toggle: false
  title: Controls
  type: entities
entities:
  - entity: switch.wink_front_porch_switch
  - entity: switch.wink_hallway_switch
  - entity: switch.wink_kitchen
  - entity: switch.wink_back_flood
  - entity: switch.powerpivot1_2
  - entity: switch.powerpivot1_1
  - entity: light.wink_bed_room
  - entity: light.wink_led_strip_bed
    name: Led Bed Strip
  - entity: switch.wink_basement
  - entity: switch.wink_zwaveoutlet
  - entity: switch.esp2
  - entity: switch.on_off_sonoff2
  - entity: switch.on_off_sonoff
  - entity: switch.side_spigot
  - entity: switch.circadian_lighting_circadian_lighting
  - entity: light.ge_daylight_140015df_1
  - entity: light.osram_lightify_a19_tunable_white_00094db0_3
  - entity: light.wink_hallway
  - entity: switch.bathroom_fan
  - entity: switch.esp6
filter:
  exclude:
    - state: una*
type: 'custom:auto-entities'
```
