### ISSUE TITLE
Error: Entities need to be an array

### ISSUE THREAD

**Issue by LouisMT** [thomasloven/lovelace-auto-entities#127]
I'm using the following configuration:

```
- type: custom:auto-entities
  card:
    type: glance
  entities:
    - sensor.trash_gft
    - sensor.trash_papier
    - sensor.trash_pmd
    - sensor.trash_restafval
  sort:
    method: attribute
    numeric: true
    attribute: next_pickup_in_days
```

But when I use this configuration, the card is not being shown at all, and the following errors are shown in the console:

```
Uncaught (in promise) 
Object { name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]" }

card glance Error: Entities need to be an array
```
