### ISSUE TITLE
Option for using regex_replace or similar template for items

### ISSUE THREAD

**Issue by markuskorbel** [thomasloven/lovelace-auto-entities#131]
Hi,

I'm using auto entities for multiple cards in my installation and one of them displays parcel tracking entities that are auto generated and updated but have a really long preface string that makes it really hard if not impossible to get the actual parcel title to fit on the screen.

![image](https://user-images.githubusercontent.com/6118673/89418804-746a2b00-d728-11ea-8baa-615923218911.png)

This was taken on my computer where it fits, but mobile devices or my pi touchscreen can't fit these, so I would like to add an option like this to the auto entities card:

regex_replace(find="Seventeentrack Package: ", replace="", ignorecase=True)

Hope this makes sense :) Also if there is a way of doing this that I missed - and I searched - please let me know.

Regards and thanks for this awesome addon,
Markus

**Comment by regystro** [comment]
That would be great. I'm facing exactly the same problem.
I've only been able to replace the friendly_name by the entity_id, as documented [here](https://github.com/thomasloven/lovelace-auto-entities#entity-options), this way:
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: sensor.seventeentrack_package_*
      options:
        name: this.entity_id
        secondary_info: last-changed
```

A possible approach could be: 
```
      options:
        name: {{ this.entity_friendly_name | regex_replace(find="Seventeentrack Package: ", replace="", ignorecase=True) }}
```
but as a non programmer, I don't know if it would be very difficult to add template parsing to lovelace-auto-entities.

Greetings.

**Comment by regystro** [comment]
Good news: I managed to make it work in conjunction with another custom card: [lovelace-card-templater](https://github.com/gadgetchnnel/lovelace-card-templater), this way:

```
type: 'custom:auto-entities'
card:
  title: Parcels
  type: entities
filter:
  include:
    - entity_id: sensor.seventeentrack_package_*
      options:
        type: 'custom:card-templater'
        entity_row:
          name_template: >-
            {{ state_attr('this.entity_id','friendly_name') |
            regex_replace(find="Seventeentrack Package: ", replace="",
            ignorecase=True)}}
          secondary_info: last-changed
```

The issue that pointed me in the right direction was [this one](https://github.com/gadgetchnnel/lovelace-card-templater/issues/13).
Hope this helps.
