### ISSUE TITLE
Performance issue - Entities Card

### ISSUE THREAD

**Issue by Morphy99** [thomasloven/lovelace-auto-entities#134]
I've been trying to use this to populate a card with all lights separated by rooms but for some reason this config is slowing the browser to a halt. I've tried playing around with different filters to achieve the same and I have another card for switches which works fine. The only difference with that one is that is it has less entities and it's filtered by entity_id not area.

```
card:
  show_header_toggle: true
  title: Lights
  type: entities
filter:
  include:
    - label: Lounge
      type: section
    - domain: light
      entity_id: light.lounge*
      not:
        entity_id: light.lounge_tv_backlight
    - style:
        background: grey
        height: 1px
      type: divider
    - area: Living Room
      domain: light
    - style:
        background: grey
        height: 1px
      type: divider
    - entity_id: switch.lamp_switch
    - label: Kitchen
      type: section
    - area: Kitchen
      entity_id: light.*
    - label: Bedroom
      type: section
    - area: Main Bedroom
      entity_id: light.*
    - area: Main Bedroom
      entity_id: switch.tm_bedroom_desk_light
    - label: Spare Bedroom
      type: section
    - area: Spare Bedroom
      entity_id: light.*
    - label: Hallway
      type: section
    - area: Hallway
      entity_id: light.*
    - label: Bathroom
      type: section
    - area: Bathroom
      entity_id: light.*
    - label: Outside
      type: section
    - area: Outside Back
      entity_id: light.*
type: 'custom:auto-entities'
```

This is the switch version which works ok:

```
card:
  show_header_toggle: true
  title: Appliances
  type: entities
filter:
  include:
    - label: Lounge
      type: section
    - domain: switch
      entity_id: switch.tm_lounge*
      not:
        entity_id: '*light*'
    - label: Kitchen
      type: section
    - domain: switch
      entity_id: switch.tm_kitchen*
      not:
        entity_id: '*light*'
    - label: Bedroom
      type: section
    - domain: switch
      entity_id: switch.tm_bedroom*
      not:
        entity_id: '*light*'
    - label: Spare Bedroom
      type: section
    - domain: switch
      entity_id: switch.tm_spare*
      not:
        entity_id: '*light*'
type: 'custom:auto-entities'
```

I've checked resources and the CPU on the running HA (RPi4) is fine same goes for Chrome browser. Although this does increase to 25% when it freezes. I can also see a performance slow on the HA Android companion APP.
