### ISSUE TITLE
The attribute battery not filtered

### ISSUE THREAD

**Issue by keteflips** [thomasloven/lovelace-auto-entities#139]
This show me nothing:

```
type: 'custom:auto-entities'
card:
  type: entities
  title: Battery warning
filter:
  include:
    - entity_id: '*contact'
      attributes:
        battery: "< 50"

```

But this works:

```
type: 'custom:auto-entities'
card:
  type: entities
  title: Battery warning
filter:
  include:
    - entity_id: '*contact'
      attributes:
        battery: 100
```

![image](https://user-images.githubusercontent.com/22074069/94995623-bdf7ba80-059f-11eb-8bfa-f921e3761a04.png)

How I can make this work?
