### ISSUE TITLE
Bug: auto-entities making dashboard unresponsive 

### ISSUE THREAD

**Issue by Armadill0** [thomasloven/lovelace-auto-entities#141]
Since the homeassistant upgrade to 0.116.0 and the following versions I have huge issues with auto-entities card on my dashboards. On most of them dashboards get unresponsive right when I want to switch to them. They simply don't load. Independent of Android/IOS app or the webinterface.

Unfortunately I am using this a lot on my dashboards. What can I do to help you to find the cause for this problem?

A somehow working configuration for auto-entities:
```
card:
  title: Super
  type: entities
filter:
  include:
    - attributes:
        fuel_type: e5
      entity_id: sensor.tankerkoenig*
sort:
  count: 5
  method: state
  numeric: true
type: 'custom:auto-entities'
```
But also this feels pretty slow. So I guess it is affected the same way but not that strong like the one below.

And a definitely not working configuration in my setup:
```
card:
  type: entities
filter:
  include:
    - area: EG
      entity_id: switch*
sort:
  method: name
  numeric: true
type: 'custom:auto-entities'
```
