### ISSUE TITLE
Auto-entities does not work with just entities

### ISSUE THREAD

**Issue by InduPrakash** [thomasloven/lovelace-auto-entities#142]
This declaration
```
        - type: custom:auto-entities
          card:
            type: entities
            title: Switches
          entities:
            - switch.aquarium_light
```

gives

```
chunk.cdf43a32e306acfdb2f4.js:1749 card custom:auto-entities TypeError: i.setConfig is not a function
    at _ (auto-entities.js?16:1)
    at auto-entities.js?16:1
    at b (auto-entities.js?16:1)
    at auto-entities.js?16:1
    at HTMLElement.setConfig (auto-entities.js?16:1)
    at s (chunk.cdf43a32e306acfdb2f4.js:1749)
    at chunk.cdf43a32e306acfdb2f4.js:1749
    at d (chunk.cdf43a32e306acfdb2f4.js:1749)
    at l (chunk.cdf43a32e306acfdb2f4.js:1749)
    at sr (chunk.c23d64825d253b823e6e.js:5810)
```

But this works

```
        - type: custom:auto-entities
          card:
            type: entities
            title: Switches
          entities:
            - switch.aquarium_light
          filter:
            include:
              - group: group.lights
```
