### ISSUE TITLE
Filter attributes with space not working

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-auto-entities#144]
Hi,

I'm unable to filter using attributes with a space.
Following code shows nothing:

```
filter:
  include:
    - entity_id: '*firmware_update*'
      attributes:
        'available version:': v1.8.0
```

Simone
