### ISSUE TITLE
Duplicates appear with "unique: true" in case of CSS-styling (card-mod)

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#146]
I have duplicates in my auto-entities list in case of using card-mod.

Here is a small example:

1. Without card-mod:
Here we have a list of sensor.battery_* entities, and two of them are placed on the top of the list (i.e. “static elements”):
```
type: 'custom:auto-entities'
card:
  type: entities
  title: example
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: true
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
      options:
        secondary_info: last-changed
      sort:
        method: state
        reverse: false
        ignore_case: false
        attribute: null
        first: 0
        count: 1000
        numeric: true
```
![изображение](https://user-images.githubusercontent.com/71872483/99919544-23aa2c80-2d2f-11eb-9db0-587bb8c5a9b7.png)

2. Now let’s apply style to the 1st static element:
```
type: 'custom:auto-entities'
card:
  type: entities
  title: example
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
    style: |
      :host {
        color: red;
      }
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: true
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
      options:
        secondary_info: last-changed
      sort:
        method: state
        reverse: false
        ignore_case: false
        attribute: null
        first: 0
        count: 1000
        numeric: true
```
Great, the style works fine!
But now we have a duplicate:
![изображение](https://user-images.githubusercontent.com/71872483/99919594-6a982200-2d2f-11eb-8ec1-73232ed3f88d.png)

Is it a bug?

**Comment by thomasloven** [comment]
If you change something about an entry, it's not the same as an unchanged entry.

See description of the `unique` parameter in the readme.

> `unique:` Whether to remove duplicate values after filtering and sorting. Set to `true` to remove exact duplicate entries. Set to `entity` to remove entries with the same entity id. Default: `false`.

**Comment by ildar170975** [comment]
> Set to `entity` to remove entries with the same entity id.

Does it mean that I should use this option?
Because in this case there duplicates too:

```
type: 'custom:auto-entities'
card:
  type: entities
  title: example
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
    style: |
      :host {
        color: red;
      }
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: true
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
      options:
        secondary_info: last-changed
      sort:
        method: state
        reverse: false
        ignore_case: false
        attribute: null
        first: 0
        count: 1000
        numeric: true
```
![изображение](https://user-images.githubusercontent.com/71872483/100525587-04018100-31d3-11eb-936b-99946b23c71f.png)

**Comment by thomasloven** [comment]
Could you please show the output in your browser console?

**Comment by ildar170975** [comment]
I am not sure if I am showing exactly what you asked.
![изображение](https://user-images.githubusercontent.com/71872483/100544856-b126d880-3269-11eb-84e0-44cbfabd1e4b.png)

**Comment by thomasloven** [comment]
Please upgrade to the latest version of auto-entities.

**Comment by ildar170975** [comment]
I have not upgraded "auto-entities" so far for a purpose: now I am debugging an automation with notification about available updates of lovelace components, and needed to have at least two pending updates (one was for "auto-entities", have been waiting for one more). It is OK, I will do it later, so I just updated "auto-entities".
Now after upgrade it works fine, no duplicates:
![изображение](https://user-images.githubusercontent.com/71872483/100552288-455b6480-3297-11eb-81c7-af41cb811e19.png)
Thank you very much for your efforts! It is very pleasant to know that people are working for community.

**Comment by ildar170975** [comment]
But there is one more issue with "unique: entity".
Please compare the cases:

1. unique: entity
No duplicates, but the 2nd section is missing:

![изображение](https://user-images.githubusercontent.com/71872483/100559142-77ce8700-32c2-11eb-80f2-d01e3ee65cac.png)

2. unique: true
With duplicates, both sections are displayed:

![изображение](https://user-images.githubusercontent.com/71872483/100559186-a2b8db00-32c2-11eb-958a-0cccf924116c.png)

**Comment by thomasloven** [comment]
Ok. That's a bug. I'll take a look at it.

**Comment by ildar170975** [comment]
Great job!

1. Case #1 - "unique: entity":
```
type: 'custom:auto-entities'
card:
  type: entities
  title: Проблема 146
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: entity
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
      options:
        secondary_info: last-changed
```
![image](https://user-images.githubusercontent.com/71872483/118729747-1df55580-b83f-11eb-9b79-579d6b1c3f6f.png)

Case #2 - "unique: true":
```
type: 'custom:auto-entities'
card:
  type: entities
  title: Проблема 146
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: true
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
```
![image](https://user-images.githubusercontent.com/71872483/118729956-79274800-b83f-11eb-8172-02dcaec52204.png)

Case #3 - "unique: entity":
```
type: 'custom:auto-entities'
card:
  type: entities
  title: Проблема 146
entities:
  - type: section
    label: static elements
  - entity: sensor.battery_cleargrass_2
    style: |
      :host {
        color: red;
      }
  - entity: sensor.battery_life360_papa
  - type: section
    label: auto elements
unique: entity
show_empty: true
filter:
  include:
    - domain: sensor
      entity_id: sensor.battery_*
```
![image](https://user-images.githubusercontent.com/71872483/118730210-e89d3780-b83f-11eb-96da-a092e71d45d4.png)
