### ISSUE TITLE
Sorting not working at all

### ISSUE THREAD

**Issue by RonnyAL** [thomasloven/lovelace-auto-entities#147]
Hello!

I'm working on implementing a garbage collection card, and thought this component would be useful for sorting the dates. As of now, I'm displaying template entities with formatted dates for readability. Behind the scenes I have sensors with valid datetime states. The latter are of course more suitable to sorting, but hopefully I'll figure out a solution where I can sort by actual datetimes yet display the formatted dates.

Anyway - in testing I haven't managed to sort the entities at all. Here's my current configuration:

```
type: 'custom:auto-entities'
sort:
  method: state
card:
  type: entities
  title: Tømmekalender
  entities:
    - entity: sensor.matavfall_template
      icon: 'hass:recycle'
    - entity: sensor.brennbart_template
      icon: 'mdi:trash-can'
    - entity: sensor.glass_metall_template
      name: Glass/metall
      icon: 'mdi:bottle-wine'
    - entity: sensor.plast_template
      icon: 'mdi:food-fork-drink'
    - entity: sensor.papir_template
      icon: 'hass:newspaper'
filter: '*'
```
This results in the following card:
![KdX5a3r](https://user-images.githubusercontent.com/26335298/100337938-427f1c00-2fd8-11eb-9dc8-d3000da1dc1d.png)

As you can see, entities simply show up in the order they were added.

I've cleared the browser cache and restarted Home Assistant for good measure.

Any ideas?
