### ISSUE TITLE
Not updating with new grid card

### ISSUE THREAD

**Issue by zbuh** [thomasloven/lovelace-auto-entities#148]
Latest version form HACS.

With this card, I have no issues. Immediately updates any change

```
type: 'custom:auto-entities'
show_empty: false
card:
  type: entities
  title: Lights on
filter:
  include:
    - domain: light
      state: 'on'
      options:
        secondary_info: last-changed
        tap_action:
          action: toggle
```

but with this, it only updates (hides or shows entities) with a refresh on the browser. State changes on the already show entities, are ok.

```
type: 'custom:auto-entities'
card:
  type: grid
  columns: 10
card_param: cards
filter:
  include:
    - domain: light
      options:
        type: button
      state: 'on'
show_empty: false
```

Checked for any JS errors, but didn't find any.
