### ISSUE TITLE
Area filter doesn’t work for entities with no device.

### ISSUE THREAD

**Issue by whatdaybob** [thomasloven/lovelace-auto-entities#149]
Hi, using the filter by area works great normally but with the latest addition of adding areas to entities directly in the release candidate for 1.0 it doesn't pick them up. 

Sorry, will add my examples later on as I'm doing this on my mobile whilst I still remember it's an issue.

**Comment by FoxxMD** [comment]
How are you filtering by area?

**Comment by whatdaybob** [comment]
> How are you filtering by area?

Its one of the standard filters

https://github.com/thomasloven/lovelace-auto-entities#filters

**Comment by FoxxMD** [comment]
Oops I missed it :sweat_smile: thanks!

**Comment by FoxxMD** [comment]
Ok...then I have the same problem as OP. I've got a bunch of scenes in an area but nothing is returned

```
type: custom:auto-entities
card:
  type: entities
unique: true
filter:
  include:
    - area: Living Room
      domain: scene
```
