### ISSUE TITLE
Template doesn't update the logbook card

### ISSUE THREAD

**Issue by Chris-V** [thomasloven/lovelace-auto-entities#155]
I'm trying to build a logbook card with a Jinja2 template and this basically does nothing.

In fact, there are two issues when using auto-entities with a the logbook card and a template:

1. `entities` is mandatory. otherwise I get a red config error.
2. The template result does not update the card.

Here's a very simple reproduction:

```yaml
- type: custom:auto-entities
  card:
    type: logbook
    title: House feed
  entities:
    - light.office
  filter:
    template: "{{ ['light.bookshelf'] }}"
```

Running on HA 2020.12.

Thank you for the awesome work!
