### ISSUE TITLE
Feature Request: filter by 'area_id'

### ISSUE THREAD

**Issue by fourwallz** [thomasloven/lovelace-auto-entities#156]
I'm trying to set up an auto-entities card and would like to be able to filter by 'area_id'.  Is that something that has been considered or is it even possible?

**Comment by FoxxMD** [comment]
+1 for this. I've got all my scenes and entities set up by area and would like to be able to auto populate all scenes for an area to a card. It's unfortunate areas seems like it was going to supersede groups and be manageable from the UI and then HA just kind of...forgot about them. Even doing things with area via node-red required a few extra steps instead of just like a normal attribute.

**Comment by FoxxMD** [comment]
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - area: "Living Room"
 ```
