### ISSUE TITLE
After update home-assistant to 2020.12.0, last-changed shows always 'Never'

### ISSUE THREAD

**Issue by ericvb** [thomasloven/lovelace-auto-entities#157]
This configuration did work in 0.118.5
```
type: 'custom:auto-entities'
card:
  type: entities
  title: Batterijniveau's
  show_header_toggle: false
  state_color: true
filter:
  include:
    - entity_id: '*battery*'
      options:
        type: 'custom:battery-entity-row'
        secondary_info: last-changed
    - entity_id: '*door_sensor*'
      options:
        type: 'custom:battery-entity-row'
        secondary_info: last-changed
```

After the update, I have always Never as last-changed.
I did try with last_changed like mentioned in de readme of this repository, but then there is nothing put on screen.
Did try also last_updated, but also nothing on screen.

Edit:
Apparently this problem due to an issue on the custom battery-entity-row plugin. See https://github.com/benct/lovelace-battery-entity-row/issues/9
