### ISSUE TITLE
`card_param` doesn't appear to be working

### ISSUE THREAD

**Issue by danrspencer** [thomasloven/lovelace-auto-entities#158]
VERSION: 1.7.0

I'm unable to get the `card_param` property to work with this card.

Even using the example directly from the docs:

```
type: custom:auto-entities
card:
  type: grid
card_param: cards
filter:
  include:
    - domain: sensor
      options:
        type: entity
```

Gives me:

```
entities:
  - entity: sensor.lights_on
    type: entity
  - entity: sensor.rooms_on
    type: entity
  - ...
type: grid
```
