### ISSUE TITLE
error: hours_to_show even though that isn't used in the card config

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#159]
more info:
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/228?u=mariusthvdb

for some reason, using this auto-entities card:

```
  - type: custom:auto-entities
    card:
      type: map
      title: Map Family abroad
    show_empty: false
    filter:
      include:
        - entity_id: person.*_address
          not:
            attributes:
              country_code: nl
```
throws an error about `hours_to_show` even though that isnt used in the config at all..

adding several map options:

```
  - type: custom:auto-entities
    card:
      type: map
      title: Map Family abroad
    show_empty: false
    filter:
      include:
        - entity_id: person.*_address
          not:
            attributes:
              country_code: nl
          options:
            aspect_ratio: 969
            dark_mode: false
            default_zoom: 14
```
adds an error on the dark_mode, but since it is set to false, which is default, I can live with deleting it (even though the error still is odd of course.

seems the show_when_empty (which these cards are at the moment) doesnt prevent the card to start looking for entity_id's 

changing to any other country_code (we are all in nl now) takes the error out and displays all entity_id's.

Also, taking out the 'not' option doesn't help. the issues is reversed in that case, showing the error on any other code than 'nl'.

to be 100% positive the error is on this card, I've tested that on an empty view.

Please have a look why the error on hours_to_show is displayed?
thanks

<img width="675" alt="Schermafbeelding 2020-12-18 om 12 12 30" src="https://user-images.githubusercontent.com/33354141/102616986-c12f2b00-4138-11eb-9cca-55aec5664a2b.png">

HA 2020.12.1 and latest auto-entities version 1.7.0

**Comment by ildar170975** [comment]
Tried to reproduce it.
Unfortunately, I have only "usual" person entities like "person.ildar", "person.mama" etc (no *_address) and without "country_code" attributes.
No errors are displayed.
![изображение](https://user-images.githubusercontent.com/71872483/103247017-7a320880-4976-11eb-9df7-1c53579bee6d.png)
Same latest HA version (docker installation) , latest auto-entities.

**Comment by thomasloven** [comment]
Please try version 1.8.0

**Comment by Mariusthvdb** [comment]
sorry I missed this, and yes, haven't seen these anymore lately, closing.
thanks

**Comment by Mariusthvdb** [comment]
so this is back in full glory, just noticed, and probably has never truly left, just forgot about it.

<img width="616" alt="Schermafbeelding 2021-03-19 om 13 00 52" src="https://user-images.githubusercontent.com/33354141/111777129-29fe7e80-88b3-11eb-85dd-523e02fa5714.png">

happening on a config:

```
  - type: custom:auto-entities
    card:
      type: map
      title: Map Family abroad
    show_empty: false
    filter:
      include:
        - entity_id: person.*_address
          not:
            attributes:
              country_code: nl
```

these entities are regular person entities, on which an AD script sets additional attributes

<img width="774" alt="Schermafbeelding 2021-03-19 om 13 03 15" src="https://user-images.githubusercontent.com/33354141/111777524-b27d1f00-88b3-11eb-8b73-e1a91c5d8aea.png">

If I use the other available config option

```
  - type: custom:auto-entities
    card:
      type: map
      title: Map Family abroad
    show_empty: false
    filter:
      include:
        - entity_id: person.*_address
#          not:
          attributes:
            country_code: '! nl'
```

no error is displayed, but the card is shown, with all person entities that are in fact in country_code: nl.... so the logic doesnt work correctly.

I have no clue where to start debugging this, please have another look?

**Comment by thomasloven** [comment]
Well, `! nl` doesn't work because "nl" is not a numerical value: https://github.com/thomasloven/lovelace-auto-entities#numerical-comparison

As for the errors. I've looked into it and would say that's actually a bug in the map card, and there's not much I can do to fix it with auto-entities.

I'll see to fixing it in core at some point, but it'll probably be a low priority bug.

Did I understand you correctly that this:
```
filter:
  include:
    - entity_id: 'person.*_address'
  exclude:
    - attributes:
        country_code: nl
```
`person`s where `country_code` is `nl` too?

**Comment by ildar170975** [comment]
Now I can see probably the same error:
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/329?u=ildar_gabdullin
There are errors:
![изображение](https://user-images.githubusercontent.com/71872483/111859885-23284800-8955-11eb-869e-0d138e7216b0.png)

**Comment by Mariusthvdb** [comment]
> Did I understand you correctly that this:
> 
> ```
> filter:
>   include:
>     - entity_id: 'person.*_address'
>   exclude:
>     - attributes:
>         country_code: nl
> ```
> 
> `person`s where `country_code` is `nl` too?

not really sure what you're asking here, think a few words got cut out, but yes, that configs doesnt work either nor does:
```
    filter:
      include:
        - entity_id: 'person.*_address'
      exclude:
        - entity_id: 'person.*_address'
          attributes:
            country_code: nl
```

I have also tested this with other entities, to see if it  was the AD addition causing the issue, but using template sensors:
```
  - type: custom:auto-entities
    card:
      type: map
      title: Family abroad
      style: |
        .card-header {background-color: var(--primary-color);}
    show_empty: false
    filter:
      include:
        - entity_id: binary_sensor.*_in_nl
          state: 'off'
      exclude:
        - entity_id: binary_sensor.*_in_nl
          attributes:
            country: None
```

results in the same error, while using this as an entities is ok. The issue must be with feeding 'nothing' to the Map card with auto-entities
