### ISSUE TITLE
FR: bulk rename option

### ISSUE THREAD

**Issue by RoboMagus** [thomasloven/lovelace-auto-entities#166]
It would be a great addition to have some sort of a bulk rename option added to the auto-entities, similar to what's been done in 'maxwroc/battery-state-card'.

I tend to group entities of the same device together, but Its a waste of space to have the name of the device repeated on every row. Being able to replace parts of entity names as a bulk renaming would cleanup such groupings a lot.

**Comment by bcutter** [comment]
**EXACTLY** what I was thinking right now! That feature would be awesome.

Example: (the black part would be the text I need, everything else before shall be removed)

![grafik](https://user-images.githubusercontent.com/13799156/107163395-86fc4000-69a9-11eb-917c-67954c5e6ceb.png)

See the `bulk_rename` option I use a lot as an inspiration:
https://github.com/maxwroc/battery-state-card#card-config

**Comment by edenhaus** [comment]
A workaround can be found in https://github.com/thomasloven/lovelace-auto-entities/issues/110#issuecomment-647013848

But this workaround is only working for cards like `entities`, but not for cards like `history-graph`. I think the best would be to support templates for all options similar to [lovelace-template-entity-row](https://github.com/thomasloven/lovelace-template-entity-row). @thomasloven What do you think about this idea?

**Comment by RoboMagus** [comment]
Thanks for pointing me to that workaround @edenhaus!
It might not be a perfect solution but it would already improve about 80% of my use cases.

**Comment by bcutter** [comment]
Nice workaround, would still love to see this as an config option!

**Comment by genebean** [comment]
+1 to the renaming from https://github.com/maxwroc/battery-state-card#card-config

**Comment by coom** [comment]
Hi,
+1 for the renaming option, as the workaround breaks some things like the unit, as you can see in this screenshot :

![image](https://user-images.githubusercontent.com/10179617/129541692-a8c39460-24cf-410c-acfc-0cc626b5d284.png)

Would be really nice if we can just add something like :
name: replace('battery', '') | replace ('Motion', '')

So we can remove the useless par of the entity friendly name.

**Comment by bcutter** [comment]
I can only add the big need once again: huge parts of my UI are filled with unnecessary text which is annoying especially on smaller screen devices.

Replacing strings would therefore be a perfect solution and totally awesome.

As other frontend integrations already use/offer this (code is on GitHub!), it can only be a "A small step for us developers, but a big step for the whole community" thing to integrate it here 😄

**Comment by chasebolt** [comment]
+1

**Comment by bcutter** [comment]
Unfortunately still no reaction, only more "I want/need that too" signs.

How can we support the maintainer(s) so he/they are able to add this feature?

**Comment by Weissnix4711** [comment]
+1

The workaround in #110 using `custom:template-entity-row` only works for the entities card.

I would like to set this up with mini-graph-card, but cannot. I have tried to add templating by using config-template-card, however the template is evaluated before `this.entity_id` is converted into the actual entity id. You would think the following would work:

```
type: custom:config-template-card
variables:
  fix_name: |
    entity_id => {
      return states[entity_id].attributes.pair;
    }
card:
  type: custom:auto-entities
  filter:
    include:
      - entity_id: sensor.bitfetch_.*busd
        options:
          name: ${fix_name('this.entity_id')}
  sort:
    method: state
    reverse: true
    numeric: true
  card:
    type: custom:mini-graph-card
entities:
  - idkwhattoputhere
```

But it does not. The string 'this.entity_id' is passed to the function instead of the actual entity id. Hence, it fails to find an entity with that name.

I have no other ideas. The only way I see for this to work is for auto-entities to add templating, or for mini-graph-card, and any other custom cards to do so.

**Comment by bcutter** [comment]
...or to just have a look how Battery State Card implemented this, maybe it can be adopted. I actually think it's a easy thing for Thomas.

https://github.com/maxwroc/battery-state-card#entity-filtering-and-bulk-renaming

**Comment by RoboMagus** [comment]
@thomasloven, would you reconsider a PR such as #103?

Though I have been using the workaround mentioned in this comment:
> A workaround can be found in [#110 (comment)](https://github.com/thomasloven/lovelace-auto-entities/issues/110#issuecomment-647013848)
> 
> But this workaround is only working for cards like `entities`, but not for cards like `history-graph`. I think the best would be to support templates for all options similar to [lovelace-template-entity-row](https://github.com/thomasloven/lovelace-template-entity-row). @thomasloven What do you think about this idea?

There are uses where other cards than `template-entity-row` have to be used,  e.g. when using graphs. For those uses there is still very much a use-case for bulk renaming entities that are provided to the underlying cards, which can only realistically be done (from my point of view) from within the auto entities scope.

**Comment by bcutter** [comment]
Can we please have the information **what is needed** to finally implement this feature after almost **2 years** of waiting?!?

Would e. g. some donation motivate one to add it?

There was already information given how other implement such feature. For a pro dev it should be a 15 minutes finger exercise...

**Comment by ildar170975** [comment]
@bcutter 
Developing HA & plugins is a voluntary job.
People are doing it in their spare time.
No one have a right to urge.
And everyone may become a developer within 2 years if he desire it so much & implement all needed features by himself.

**Comment by bcutter** [comment]
Partly agree with you. Time alone doesn't transform users (like me) to developers. Using tools is sometimes difficult enough, building them is a whole other story.

In https://github.com/thomasloven/lovelace-auto-entities/issues/166#issuecomment-934517692 I referenced another frontent integration which does _exactly_ what this FR from @RoboMagus is about. Honestly, looking at the source of that project and even trying to find the code which does the bulk_rename is beyond my capabilities. Not to speak of how to integrate it into lovelace-auto-entities.

I was just wondering and asking and even a donation seems to be no motivation, can't imagine why else the 👎 came from.

Let's face the facts: almost two years and possible solution (implementation example, mentioned above again) for developers lies before us, at least 13 others (users, too?) voted up 👍 for this FR.

Hopefully someone capable of implementing this feature will catch up on this, probably Thomas himself, who knows.

**Comment by ildar170975** [comment]
> Time alone doesn't transform users (like me) to developers. Using tools is sometimes difficult enough, building them is a whole other story.

Agree. Even me - a dev since 1996 - started to change some Lovelace card and failed )))
Never used these py, ts, js and others "yes, this is a language too".

> even a donation seems to be no motivation

Probably depends on a size of a donation )))). How can we measure a person's time in Euros?



> at least 13 others (users, too?) voted up

Sometimes it does not matter.
See, there is a "template" option - a universal way to implement almost anything.
Now 333 persons are asking about a new small option to get a result - which may be achieved by this universal "template" option.
Later another 333 persons will ask for another small option to get another result - which currently is also may be achieved by this "template" option.
This is infinite.

**Comment by bcutter** [comment]
Using template stuff is what I tried many times and even I got close
a) I never got close enough (meaning not having visual side effects or not running into limitations)
b) the level of complexity added to auto-entities is just mind blowing.

My latest status is at https://github.com/thomasloven/lovelace-auto-entities/issues/110#issuecomment-1221438175, this is where I gave up.

So having to use
```
          options:
            secondary: >
              {{ state_attr(config.entity, 'last_triggered') | relative_time }}
            type: custom:template-entity-row
            name: >
              {{ state_attr(config.entity, 'friendly_name') | replace('Switch-Control_', '') }}
            toggle: true
            active: "{{ is_state(config.entity, 'on') }}"
```
which still fails for the static secondary_info information is just **way too complicated** compared to a native bulk rename like
```
bulk_rename:
  - from: "Battery Level" # simple string replace (note: "to" is not required if you want to remove string)
    to: "sensor"
```
(https://github.com/maxwroc/battery-state-card#entity-filtering-and-bulk-renaming).

**Comment by bcutter** [comment]
Meanwhile I managed to almost rebuild my use-case used in this issue, at last by
- adding more text replaces in an ugly manner ("pipe party")
- setting the icon color again

Unfortunately, still:
- a) A LOT of work for only one card
- b) with the need of applying icon colors based on the filtered entities (thanks to https://developers.home-assistant.io/blog/2022/12/07/entity-color-changes/, see list here at https://github.com/thomasloven/lovelace-template-entity-row/issues/95#issuecomment-1370289973) it makes using this now completely impossible and
- c) I discovered an update issue:
while the standard way (normal auto-entities) updates frequently, the template based one does not update its values (in this case: `secondary`), e. g.:
_(top: default, bottom: templated one)_
![grafik](https://user-images.githubusercontent.com/13799156/211384764-266307b4-c3e3-4d25-8ce3-cb841d3184d3.png)

____________

Full card with default auto-entities:
```
type: custom:collapsable-cards
title: 🔲 Übersicht Switch-Controls (bis 2023-01-09 - STANDARD ohne Bulk Rename)
defaultOpen: desktop-only
buttonStyle: 'font-size: medium'
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: null
      state_color: true
      show_header_toggle: false
    entities: null
    filter:
      include:
        - entity_id: automation.switch_control*
          options:
            secondary_info: last-triggered
      exclude:
        - name: zzzOLD*
    show_empty: true
    unique: true
    sort:
      method: last_triggered
      reverse: true
```

Template based auto-entities with "bulk" renaming the hard way:
```
type: custom:collapsable-cards
title: 🔲 Übersicht Switch-Controls
defaultOpen: desktop-only
buttonStyle: 'font-size: medium'
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: null
      state_color: true
      show_header_toggle: false
    entities: null
    filter:
      include:
        - entity_id: automation.switch_control*
          options:
            secondary: >
              Vor {{ state_attr(config.entity, 'last_triggered') | relative_time
              | replace ('seconds','Sekunden') | replace ('minutes','Minuten') |
              replace ('hours','Stunden') | replace ('days','Tage') | replace
              ('weeks','Wochen') }}
            type: custom:template-entity-row
            name: >
              {{ state_attr(config.entity, 'friendly_name') |
              replace('Switch-Control_Switch', '') }}
            toggle: true
            active: '{{ is_state(config.entity, ''on'') }}'
            card_mod:
              style:
                state-badge:
                  $: |
                    ha-state-icon { color: #ffc107 !important;}
      exclude:
        - name: zzzOLD*
    show_empty: true
    unique: true
    sort:
      method: last_triggered
      reverse: true
```
____________

**So, guys: templating just to get rid of text in the entities is NOT AN OPTION!** I only discovered those 3 pointed disadvantages. I still encourage smart people to implement a bulk rename option DIRECTLY in auto-entities as initially requested by @RoboMagus.

I mean, the last update brought so many small improvements (including useless ones like the `and` operator :-) ), can we please focus on this feature?

**Comment by thomasloven** [comment]
I just had a flash of inspiration!

Here's a bit of yaml that displays every entity in the `Kitchen` area but removes the first word in its name:

```yaml
type: custom:auto-entities
filter:
  include:
    - area: Kitchen
card_param: input
card:
  type: custom:auto-entities
  card:
    type: entities
  filter:
    template: |
      {% set ns = namespace(retval=[]) %}
      {% for e in config.input %}
        {% set ns.retval = ns.retval + [
          {
            "entity": e.entity,
            "name": (state_attr(e.entity,"friendly_name").split()[1:] | join())
          }
        ] %}
      {% endfor %}
      {{ ns.retval }}
```

**Comment by igorsantos07** [comment]
Another reason why the `custom:template-entity-row` trick doesn't work in all scenarios: it depends on the final card accepting those custom rows - `glance`, for instance, doesn't 🤷

**Comment by bcutter** [comment]
No I don't. It just proves one more time this is way to complicated. Out of the box is still the way to do this, saving so many people so much time.

**Comment by RoboMagus** [comment]
@lichenophile, For most uses of removing the common friendly name part of auto-entities I've setup a [decluttering-card](https://github.com/custom-cards/decluttering-card) (See example below). But use of this string replacement could be altered to your usecase 😉.

```yaml
wifi_plug_card:
  card:
    type: custom:vertical-stack-in-card
    title: '[[name]]'
    cards:
      - type: entities
        entities:
          - type: custom:auto-entities
            card:
              type: custom:fold-entity-row
              padding: 0
              head: 
                type: section
                label: Info
            filter:
              include:
                - entity_id: 'sensor.[[entity_part]]*'
                  options:
                    type: custom:template-entity-row
                    name: "{{ state_attr(config.entity, 'friendly_name') |  replace('[[trim_name]]', '') | replace('_', ' ') }}"
```

Which is then used like this:
Where `trim_name` is the common part of the friendly name that you'd want to remove for all entities.
```yaml
      type: custom:decluttering-card
      template: wifi_plug_card
      variables:
        - name: TV Plug
        - trim_name: "NEO Coolcam 2"
        - entity_part: neo_coolcam_2
```

**Comment by igorsantos07** [comment]
Sorry to bother once again, but... Why is it so hard to implement this feature? The only response from the maintainer was a very complex (and dirty) templating workaround.

I mean, isn't it similar to what's done in the Battery State Card?

This is paramount for a clean dashboard with a warnings card.

**Comment by bcutter** [comment]
I bet this one will still exist 3 more years.

I'd even pay someone to implement this. Others too, I'm sure about that.

Absolute killer feature. Man that would finally boost all my dashboards MASSIVELY.

So frustrating sitting and waiting, looking that there's a probably easy to adopt (copy & paste) solution someone "just" needs to implement here...

**Comment by FoxxMD** [comment]
@lichenophile add a separator string to the `join()` function IE `join(' ')`

```
"name": (state_attr(e.entity,"friendly_name").split()[1:] | join(' '))
```

**Comment by deadsmiily** [comment]
You can change the name of the Entity if you go to "filters" -> options -> add: name: <your name>

![Screen01](https://github.com/thomasloven/lovelace-auto-entities/assets/103827477/d32ca319-fd77-4ce9-894e-f642f0c886aa)

**Comment by bcutter** [comment]
> You can change the name of the Entity if you go to "filters" -> options -> add: name: <your name>
> 
> 
> 
> ![Screen01](https://github.com/thomasloven/lovelace-auto-entities/assets/103827477/d32ca319-fd77-4ce9-894e-f642f0c886aa)
> 
> 

Not sure if either I don't get your solution or you didn't get the issue.

Renaming one entity as proposed does not fit the requirement of renaming **many** entitie**s**, does it?

**Comment by deadsmiily** [comment]
> > You can change the name of the Entity if you go to "filters" -> options -> add: name: <your name>
> > 
> > 
> > 
> > ![Screen01](https://github.com/thomasloven/lovelace-auto-entities/assets/103827477/d32ca319-fd77-4ce9-894e-f642f0c886aa)
> > 
> > 
> 
> Not sure if either I don't get your solution or you didn't get the issue.
> 
> Renaming one entity as proposed does not fit the requirement of renaming **many** entitie**s**, does it?

You are absolutely right. I misunderstood the threat, sorry.

**Comment by igorsantos07** [comment]
And here we are again, spending hours and hours battling with Jinja's restrictive templates (you can edit anything BUT a dict) to try to edit a freaking dict... My objective is to feed further options to the resulting card without having to re-type everything, or having to configure options inside the terrible JSON-like syntax from the template.

Anyone has any guess on why this doesn't work? The resulting string in Dev Tools > Template seems to be the same as @thomasloven's [comment](https://github.com/thomasloven/lovelace-auto-entities/issues/166#issuecomment-1382930506).

```yaml
type: custom:auto-entities
card_param: input
card:
  type: custom:auto-entities
  filter:
    template: |
      {% set ns = namespace(entities=[]) %}
      {% for e in list %}
        {% set ns.entities = ns.entities + [
          dict(e.items(), name=(
            state_attr(e.entity,"friendly_name")
            |replace('CPU percent', '')
            |trim
          ))
        ] %}
      {% endfor %}
      {{ ns.entities }}
  card:
    type: entities
filter:
  include:
    - entity_id: '*_cpu_percent'
      integration: hassio
```

Other template tries I made which also have the same result:
```jinja
{% set ns = namespace(entities=[]) %}
{%- for e in list -%}
  {%- set entry = e|items|list -%}
  {%- set entry = entry + [("name",state_attr(e.entity,"friendly_name")
        |replace('CPU percent', '')
        |trim
  )] -%}
  {%- set ns.entities = ns.entities + [dict.from_keys(entry)] -%}
{%- endfor -%}
{{ ns.entities }}
```

I also tried `namespace(**e)` and go from there, which would be more natural in Jinja... But then it seems `auto-entities` doesn't accept a list of Namespaces as entities list (sort of expected, I guess?) and I found no way to turn a namespace into the usual dict.

Either result

**Comment by bcutter** [comment]
Bump and +1 for a 4 years old, 30 upvotes and therefore "most desired" feature.

**Comment by VermiumSifell** [comment]
Quite useful
```
type: custom:auto-entities
filter:
  include:
    - and:
        - label: Lights
        - or:
            - domain: light
            - domain: switch
        - area: Living Room
      options: {}
  exclude: []
card_param: input
card:
  type: custom:auto-entities
  card:
    type: entities
  filter:
    template: |
      {% set ns = namespace(retval=[]) %}
      {% for e in config.input %}
        {% set ns.retval = ns.retval + [
          {
            "entity": e.entity,
            "name": (state_attr(e.entity,"friendly_name").replace(area_name(e.entity),"") | join())
          }
        ] %}
      {% endfor %}
      {{ ns.retval }}
```

**Comment by bcutter** [comment]
Couldn't manage to adopt this. Gave a template based variant another try yesterday (one attempt every few weeks) and needed to give up after 20 minutes. That stuff is just way too complicated folks, you really need to be a programming guy instead of a normal smart home user doing a bit on the frontend. For example I could not manage to render the secondary information "last changed", while I had one for automation entities with "last triggered". Ah it's pure frustration, every single piece is hard work.

And I have so many auto-entities cards all over all my dashboards and views, it's just way too much work to switch them all - even it would work with template based ones and I could read and understand all that Jinja stuff half a year later.

**Just give us a native "friendly name REPLACE option" finally. Thank you 🙏🏼**

**Comment by BorisVolkovyski** [comment]
> Quite useful
> 
> ```
>         {% set ns.retval = ns.retval + [
>           {
>             "entity": e.entity,
>             "name": (state_attr(e.entity,"friendly_name").replace(area_name(e.entity),"") | join())
>           }
>         ] %}
> ```

Great thanks for the idea!!
I was looking for solution to make an automated list of installed addons with versions.
And with your approach I cam make exactly what I want )

Maybe it will be useful for someone.
List of installed addons 
 - with device pictures (not icons)
 - without annoying "Update" (name was taken from corresponding device)
 - with installed version on the right side instead of useless 'no update'-like info

```type: custom:auto-entities
card:
  type: entities
  title: Addons versions
  icon: mdi:toy-brick-outline
  show_header_toggle: false
filter:
  template: >-
    {% set STATES = states | selectattr('entity_id', 'in',
    integration_entities('hassio'))  -%}

    {%- for STATE in STATES 
      if(STATE.entity_id.endswith('_update')) -%}
      {%- set ENTITY_ID = STATE.entity_id -%}
      {%- set DEVICE_NAME = device_attr(device_id(STATE.entity_id), 'name') -%}
      {{
        { 'entity': ENTITY_ID,
          'name': DEVICE_NAME,
          'type': 'attribute',
          'attribute': 'installed_version'
        } }},
    {%- endfor %}
  exclude:
    - name: Home Assistant Core*
    - name: Home Assistant Supervisor*
    - name: Home Assistant Operating System*
sort:
  method: name
```

**Comment by dcapslock** [comment]
You can use the undocumented (for now) `eval_js` option. This simply takes a JSON stringified version of the resulting list with options, and runs eval() across it, before parsing JSON back for final output. This allows simple `${}` javascript expressions through which you can do your bulk rename.

e.g.

```yaml
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - options:
        eval_js: true
        name: >-
          ${state.attributes.friendly_name.replace('Lights','').replace('Light','').trim()
          }
      area: kitchen
  exclude: []
```

**Comment by bcutter** [comment]
> undocumented (for now)

Does this mean
a) not yet documented but will be documented soon or
b) undocumented but at the moment working without knowing if this is the case in future

?

Cause besides this "feature" being as easy usable as possible, it needs to be reliably stable too before one can start to invest hours in tweaking one's dashboards.

**Comment by dcapslock** [comment]
A) stable and will be documented

**Comment by bcutter** [comment]
Great. And why not downsizing it to something simple as

```
bulk_rename:
  - from: " Battery Level"
    to: ""
```

?

**Comment by bcutter** [comment]
> Great. And why not downsizing it to something simple as
> 
> ```
> bulk_rename:
>   - from: " Battery Level"
>     to: ""
> ```
> 
> ?

@dcapslock

**Comment by dcapslock** [comment]
Current `eval_js` is quite versatile but also means that it need not be structured in any way, with users able to use as they wish. In my view, introducing a `bulk_rename` option would need further options to allow the user to define what they are renaming e.g. is it friendly_name or another attribute? Or just a wrapper around eval_js at the option level for which the config is not much different than what `eval_js` gives, and much less versatile.

Anyhow, I am not getting response from Thomas on assisting to maintain auto-entities, so I am diverting my efforts to another solution I am in early stages on developing. It would have a `map` step/option where you would be able to do what you desire.

**Comment by exetico** [comment]
> You can use the undocumented (for now) `eval_js` option. This simply takes a JSON stringified version of the resulting list with options, and runs eval() across it, before parsing JSON back for final output. This allows simple `${}` javascript expressions through which you can do your bulk rename.
> 
> e.g.
> 
> type: custom:auto-entities
> card:
>   type: entities
> filter:
>   include:
>     - options:
>         eval_js: true
>         name: >-
>           ${state.attributes.friendly_name.replace('Lights','').replace('Light','').trim()
>           }
>       area: kitchen
>   exclude: []

Interesting.

Have you documented what kind of variables are exposed in the eval_js scope?

I've used this to replace the device name, which works great:

```yaml
type: custom:auto-entities
filter:
  include:
    - options:
        eval_js: true
        name: ${state.attributes.friendly_name.replace(device,'').trim() }
      entity_id: /^.(.*)user_1$/
  exclude: []
```

So for people using ESP Home and want to remove the friendly device name, from their attibutes, this is one way of doing it.

From this:

<img width="1005" height="663" alt="Image" src="https://github.com/user-attachments/assets/41e5d1be-f654-4df5-8dce-7876366627e9" />

To this:
<img width="1047" height="685" alt="Image" src="https://github.com/user-attachments/assets/bca3a8b4-beaf-46a3-ad32-8d7d82f3a109" />

Using regex are also a option (ofc):

```yaml
type: custom:auto-entities
filter:
  include:
    - options:
        eval_js: true
        name: ${state.attributes.friendly_name.replace(device,'').replace(/user 1/gi,'Tobias').trim() }
      entity_id: /^.(.*)user_1$/
  exclude: []
```
