### ISSUE TITLE
url template in hold_action doesn't work

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#167]
using:
```
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.github_repos_in_use
              options: &github_options
                tap_action:
                  action: more-info
                hold_action:
                  action: navigate
                  navigation_path: /ui-settings/weblinks
```

works fine. Adding a hard coded url like
```
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: group.github_repos_in_use
              options: &github_options
                tap_action:
                  action: more-info
                hold_action:
                  action: url
                  url_path: https://github.com/thomasloven/lovelace-auto-entities/releases/tag/1.7.0
```

works fine too. Having the auto_entities card auto set the url_path to:

```
                hold_action:
                  action: url
                  url_path: >
                    {{state_attr(config.entity,'latest_release_url')}}
```

makes the browser go to another view in the config, albeit with this address:

`/%7B%7Bstate_attr(config.entity,'latest_release_url')%7D%7D`

figuring this was the template-entity-row syntax, I also tried:
```
                  url_path: >
                    {{state_attr('this.entity_id','latest_release_url')}}
```
which seems more promising, as it urls to
`/%7B%7Bstate_attr('sensor.github_auto_entities','latest_release_url')%7D%7D`
still within the Instance of mydomain etc etc though...

Arent we allowed to do this, or is this a user error, and should I use another syntax

thanks for having a look
