### ISSUE TITLE
Add option to generate one card per entity in the entities list

### ISSUE THREAD

**Issue by JanZimmer** [thomasloven/lovelace-auto-entities#170]
It would be nice to have the option to generate *one card per entity* in the resulting entities list, instead of one card for all entities.

**Comment by rousveiga** [comment]
Creating one `vertical-stack` or `grid` and filling it with `entity` cards works; it doesn't seem to work with `light` or `gauge`, though. Will update if I get it to work with those.

**Comment by JanZimmer** [comment]
Could you provide an example?

**Comment by rousveiga** [comment]
There is one in the readme:

```yaml
type: custom:auto-entities
card:
  type: grid
card_param: cards
filter:
  include:
    - domain: sensor
      options:
        type: entity
```

You can replace `type: grid` with `type: vertical-stack`.

**Comment by JanZimmer** [comment]
Okay, this is very limited, though.

My idea was, to be able to, e.g., create one history-graph per entity which would require a bit more than replacing the paramter of the card which is to be populated.

**Comment by rousveiga** [comment]
I saw in another issue that you can combine `auto-entities` with `layout-card` to get that outcome. This has worked for me (based off of an example in the readme of `layout-card`):

```yaml
type: custom:auto-entities
filter:
  include:
    - domain: light
      options:
        type: light 
card:
  type: custom:layout-card
```

Haven't tried it with cards other than `light` yet but it doesn't seem like it would cause any issues.

**Comment by rousveiga** [comment]
I got it!

```yaml
      - type: custom:auto-entities
        filter:
          include:
            - domain: sensor
              area: Living room
              attributes:
                device_class: "temperature"
              options:
                type: history-graph
                entities:
                  - this.entity_id
        card:
          type: custom:layout-card
          layout: vertical
```
