### ISSUE TITLE
Template filter causes Glance card to not populate / render in 1.8.0 and prevents entire view from being displayed in 1.8.1

### ISSUE THREAD

**Issue by bcmitri** [thomasloven/lovelace-auto-entities#171]
I have the following lovelace card that works exactly as expected in version 1.7.0:
```card:
  columns: 3
  show_name: false
  style: |
    ha-card {  border-style: solid; border-width: 2px; border-color: black;}   
  type: glance
filter:
  exclude:
    - state: No_Game
    - state: unknown
  include:
    - entity_id: sensor.toronto_game_status
  template: >
    {%if 'Toronto' not in state_attr('sensor.boston_home_score','friendly_name')
    %}sensor.boston_home_score{%endif%}

    {%if 'Toronto' not in state_attr('sensor.boston_away_score','friendly_name')
    %}sensor.boston_away_score{%endif%}

    {%if 'Toronto' not in state_attr('sensor.boston_home_score','friendly_name')
    and 'Toronto' not in state_attr('sensor.boston_away_score','friendly_name')
    %}sensor.boston_game_status{%endif%}

    {%if 'Boston' not in state_attr('sensor.toronto_home_score','friendly_name')
    %}sensor.toronto_home_score{%endif%}

    {%if 'Boston' not in state_attr('sensor.toronto_away_score','friendly_name')
    %}sensor.toronto_away_score{%endif%}        
show_empty: false
type: 'custom:auto-entities'
```

After upgrading to 1.8.0 ( and clearing my cache), the glance card is not rendered, despite there being entities that match the filter.  After upgrading to 1.8.1 ( and clearing my cache), the entire view with that code fails to render.

Other views that include more straightforward filters seem to be unaffected.

**Comment by RichardUUU** [comment]
I'm also having a problem. Even the simplist auto-entry card will kill some of my views, some of the time i.e. when a view includes an auto-entry card, nothing on the view is visible. Comment out the auto-entry card and the view works again

I've tried to identify a pattern with different cards, different computers, different browsers, incognito windows, completely wiping cache, and only including one auto-entry card in the view. The only pattern is, if a view is dead on a certain computer, it is always dead on that computer, even though it might be visible on a different computer or the Android app.

**Comment by Zendio** [comment]
Same issues here. Had to uninstall auto-entities to get my UI back. I also tried installing 1.7.0 but it didn't work either. The issue seemed to start after installing HA core-2021.3.2

**Comment by Anwen747** [comment]
I am also having a similar issue since updating auto-entities from 1.7.0 to 1.8.1 today.  I am running HA 2021.1.5.  I also updated several other HACS plugins today (including card-mod, slider-entity-row, fold-entity-row).  I don't use a template in auto-entities, but I have the same behavior with most of my view disappearing. I have three vertical stacks; the first one shows, but the second and third do not.  The auto-entities cards are in the second vertical stack.  If I comment them out, the view works.

I have tried just using one auto-entities card, but it still doesn't work.  This is the code for that card - I didn't previously have the quotes around the binary sensors with wild cards and it worked in 1.7.0; I put them in but it didn't make any difference.

```
      - type: custom:auto-entities
        card:
          type: glance
        filter:
          include:
            - entity_id: "binary_sensor.*_door"
            - entity_id: "binary_sensor.*_window*"
            - entity_id: "binary_sensor.*_water"
            - entity_id: binary_sensor.cellar_garage_sensor_status
              state: "off"
            - entity_id: binary_sensor.upstairs_doors_sensor_status
              state: "off"
            - entity_id: binary_sensor.bedroom_sensor_status
              state: "off"
            - entity_id: binary_sensor.dallas01_status
              state: "off"
            - entity_id: binary_sensor.alarm_sounding_status
              state: "on"
          exclude:
            - entity_id: binary_sensor.house_windows
              state: "off"
        show_empty: false
```

**Comment by VDRainer** [comment]
Similar issue here.
Total empty view.
Revert to 1.8.0 solved it for me.
```
          - type: custom:auto-entities
            card:
              type: entities
              title: Abfallkalender
            entities:
              - entity: sensor.waste_restmuell_text
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ {entity}.attributes.relativ ]]"
              - entity: sensor.waste_gelbe_tonne_text
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ {entity}.attributes.relativ ]]"
              - entity: sensor.waste_papier_text
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ {entity}.attributes.relativ ]]"
              - entity: sensor.waste_biomuell_text
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ {entity}.attributes.relativ ]]"
              - entity: sensor.waste_problemmuell_text
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ {entity}.attributes.relativ ]]"
            filter:
              exclude:
                - state: "Unbekannt"
            sort:
              method: attribute
              attribute: timestamp
```
