### ISSUE TITLE
gap before and after an auto-entities card in stack-in-card

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#173]
Not sure if this is caused any the auto-entities, or the stack-in-card, but since auto-entities changed, please have a look:

using a card config frame like:
```
type: custom:stack-in-card
keep:
  background: true
cards:

  - type: custom:hui-element
    card_type: markdown
    content: >
      etcetc content
  - type: horizontal-stack
    cards:
      - type: picture-entity
        etcetc
# small visible gap here
  - type: custom:auto-entities
    card:
      type: entities
      title: Volgende ophaaldata
    filter:
      exclude:
        - entity_id: sensor.afvalwijzer*next*
        - entity_id: sensor.afvalwijzer*to*

      include:
        - entity_id: sensor.afvalwijzer_*
          options:
            type: custom:template-entity-row
            etcetc
# small visible gap here
  - type: entities
    show_header_toggle: false
    entities:
     - entity: input_boolean.trash_reminder
       secondary_info: last-changed
       etc etc
```
the gaps surrounding the central auto-entities card have suddenly appeared:

<img width="461" alt="Schermafbeelding 2021-03-09 om 09 14 22" src="https://user-images.githubusercontent.com/33354141/110444538-711f8f00-80bd-11eb-86c4-81621e74500f.png">

didn't change the card config, not the underlying integrations. Only possible options would be the HA instance version 2021.3.2 here or the auto-entities card? Stack in card hasn't changed either, and this has never been happening.

taking out the auto-entities section makes the gap go away.

please have a look?
thanks!

**Comment by Mariusthvdb** [comment]
update on this:
using the hui-element card in this particular section:
```
  - type: custom:hui-element
    card_type: custom:auto-entities
    card:
      type: entities
      title: Volgende ophaaldata
```

also makes the gaps go away. Please let me know if this is to be expected now? I don't know which change to which (card) is responsible for this changed behavior in config.
