### ISSUE TITLE
UI not updating 1.8.x

### ISSUE THREAD

**Issue by Zendio** [thomasloven/lovelace-auto-entities#176]
The frontend wont update correctly using this code:

```
  - card:
      type: entities
    filter:
      include:
        - entity_id: binary_sensor.*motion*
          last_changed: < 60
          options:
            secondary_info: last-changed
    show_empty: false
    sort:
      count: 1
      method: last_changed
    type: 'custom:auto-entities'
```

With no changes made to the code, this one worked before updating HA and Auto-Entities.
