### ISSUE TITLE
Sorting by Last Changed and Count Still Not Behaving as Before

### ISSUE THREAD

**Issue by juan11perez** [thomasloven/lovelace-auto-entities#180]
Using the below configuration entities do not render in "last changed" order. If I use count 10 they wont appear. If I use count 100, so they all appear, I can see the activated sensors at the end of the card. 
I tried the reverse:true option and same result.

```
  - type: custom:auto-entities
    card:
      type: glance
      columns: 10
      show_state: false
 
    filter:
      include:
      - domain: binary_sensor
        attributes:
          device_class: motion
      - domain: binary_sensor
        attributes:
          device_class: door   
    sort:
      method: last_changed #last_triggered #
      count: 10
    reverse: true
```

![Screenshot_2021-03-14_09-43-13](https://user-images.githubusercontent.com/30061229/111058726-c4bd1e80-84a9-11eb-8c0e-fd8eec706a85.png)

**Comment by bcutter** [comment]
I discovered the same bug. It´s in the `count` option, doesn´t matter if sorting method is last_changed, last_updated or last_triggered. Elements magically disappear (being sorted to the end of a row) when using count. See https://github.com/thomasloven/lovelace-auto-entities/issues/186 for another example.

**Comment by thomasloven** [comment]
Try release 1.9.0

**Comment by juan11perez** [comment]
@thomasloven thank you. I tried 1.9.1 and no change. The card doesn't filter by count.

**Comment by thomasloven** [comment]
Could you put the following in Dev Templates [![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/)
```yaml
{% for s in states.binary_sensor %}
{{s.last_changed}}
{% endfor %}
```

and post the output here?

**Comment by thomasloven** [comment]
And `reverse` goes inside of `sort`, btw.

```yaml
sort:
  ...
  reverse: true
```

Not
```yaml
sort:
  ...
reverse: true
