### ISSUE TITLE
 HA Android Companion App not rendering cards with "Type: section" and "sort:"

### ISSUE THREAD

**Issue by Morphy99** [thomasloven/lovelace-auto-entities#182]
With the fix of performance in #134 it seems my card isn't being loaded at all in HA Android Companion App and stops all other cards ordered after it from showing too. Works fine on Chrome in Windows. 

It seems the problem occurs when using a type: section and sort at the same time:

```
type: 'custom:auto-entities'
card:
  show_header_toggle: true
  title: Lights
  type: entities
filter:
  include:
    - domain: light
    - type: section
      label: test
    - entity_id: switch.*light
sort:
  method: name
```

Removing either works OK

Let me know if you think the issue is with the App and I'll open a bug there.
