### ISSUE TITLE
Repeating options not working for attributes

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-auto-entities#183]
Using the https://github.com/thomasloven/lovelace-auto-entities#repeating-options does not work as expected for my case.

What I want to achieve:
**Reduce lines of code.**

I have

```
type: 'custom:auto-entities'
card:
  type: entities
  title: "Open doors, windows etc."
  state_color: true
  show_header_toggle: false
filter:
  include:
    - domain: binary_sensor
      attributes:
        device_class: door
      state: 'on'
      options:
        secondary_info: last-changed
    - domain: binary_sensor
      attributes:
        device_class: window
      state: 'on'
      options:
        secondary_info: last-changed
    - domain: binary_sensor
      attributes:
        device_class: garage_door
      state: 'on'
      options:
        secondary_info: last-changed
    - domain: binary_sensor
      attributes:
        device_class: lock
      state: 'on'
      options:
        secondary_info: last-changed
  exclude: null
show_empty: false
unique: true
sort:
  method: last_changed
  reverse: true
```

So instead of having a full block with same filter options (domain is always binary_sensor, state is always on, options are always the same, only attribute `device_class` is different) I wanted to use the repeating options as documented at https://github.com/thomasloven/lovelace-auto-entities#repeating-options.

BUT it does not work. Doesn´t matter what kind of syntax I use, I end up with a card not showing up at all. I really tried everything.

NO:
```
    - domain: binary_sensor
      attributes:
        device_class 1: door
        device_class 2: window
      state: 'on'
      options:
        secondary_info: last-changed
```

NO:

```
    - domain: binary_sensor
      attributes:
        - device_class 1: door
          device_class 2: window
      state: 'on'
      options:
        secondary_info: last-changed
```

NO:

```
    - domain: binary_sensor
      attributes:
        - device_class 1: door
        - device_class 2: window
      state: 'on'
      options:
        secondary_info: last-changed
```

NO:

```
    - domain: binary_sensor
      - attributes 1:
        device_class:
      - attributes 2:
        device_class 2: window
      state: 'on'
      options:
        secondary_info: last-changed
```

**Does this not work for attributes?** Or am I doing something wrong (syntax)? How to shrink this?

**Comment by thomasloven** [comment]
Filters are AND.
You're trying to match things that are both a `door` and a `window`.

**Comment by bcutter** [comment]
Makes sense, thanks for clarifying. So there's no OR option. Therefore it doesn't work for ALL options but is (as stated in the docs) especially/mainly useful for state filter.

**Comment by thomasloven** [comment]
Try
```yaml
domain: binary_sensor
or:
  - attributes:
      device_class 1: door
  - attributes:
      device_class 2: window
state: 'on'
options:
  secondary_info: last-changed
```
