### ISSUE TITLE
Passing a friendlyname instead of a entity_id to the card

### ISSUE THREAD

**Issue by gcorgnet** [thomasloven/lovelace-auto-entities#185]
Hi, I am trying to display a number of custom cards based on a given filter.
This custom card has a "title" paramter, to which I would like to pass the friendly name of the entity being displayed.

I have found how to pass the EntityId by using `this.entity_id` but is there a way to display something more human readable?

Thanks

```
card:
  show_header_toggle: false
  title: Temperatures
  type: entities
filter:  
  include:
    - entity_id: sensor.*emperature*
      options:
        type: 'custom:tempometer-gauge-card'
        style: thermometer
        title: this.entity_id
        min: 15
        max: 30
        severity:
          green: 22
          yellow: 24
          red: 27
show_empty: false
type: 'custom:auto-entities'
```
