### ISSUE TITLE
Count option in sorting skips elements

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-auto-entities#186]
I use the following to show last 5 triggered automations:

```
type: 'custom:auto-entities'
card:
  type: entities
  title: "\U0001F916 Last triggered automations"
  state_color: false
  show_header_toggle: false
filter:
  include:
    - domain: automation
      options:
        secondary_info: last-triggered
  exclude: null
show_empty: false
unique: false
sort:
  method: last_triggered
  reverse: true
  count: 5
```

Unfortunately, this does miss or skip entities which definitely match the filter (double checked by logbook and developer tools). Made me think I´m nuts but finally I could track it down:
- I tested with "domain: automation" and "entity_id: 'automation.*' but that makes no difference.
- Also the created card does not make any difference (tested entities and logbook).
- **The missed elements are shown when `  count: 5` is removed or set to a high number, e. g. 100. Then it´s shown at the bottom end of the list.**

Here you can see the missed one:
![grafik](https://user-images.githubusercontent.com/13799156/114286471-4c715b00-9a5f-11eb-9431-8c1bf4ad84e3.png)

I think there´s a **bug with the count** function. Unfortunately I can´t provide any more debug information.
