### ISSUE TITLE
Sorting of hard-coded entities does not seem to work

### ISSUE THREAD

**Issue by cnrd** [thomasloven/lovelace-auto-entities#187]
Hi

I am trying to setup a list of entries that will sort by a date, but nothing seem to change order, no matter what I choose as the sorting method.

```yaml
entities:
  - entity: sensor.renoweb_240_l_beholder_til_mad_og_restaffald
  - entity: sensor.renoweb_rod_miljoboks
  - entity: sensor.renoweb_storskrald_villa
  - entity: sensor.renoweb_indsamling_af_haveaffald_saekke_og_beholder
  - entity: sensor.renoweb_240_l_metal_og_glas
  - entity: sensor.renoweb_240_l_plast_og_papir
  - entity: sensor.renoweb_indsamling_af_pap_lost_og_beholder
type: 'custom:auto-entities'
card:
  type: entities
  title: Affald
sort:
  method: attribute
  attribute: next_pickup_date
```

Is the sorting supposed to work with hard-coded entities?
