### ISSUE TITLE
Map errors on empty list of filtered entities

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#189]
using
```
        - type: custom:auto-entities
          show_empty: false
          card:
            type: map
            default_zoom: 4
          filter:
            template: |
              {% set km = states('input_number.quakes_near')|float %}
              {% set location = states('input_select.quakes_near') %}
              {% for s in states.geo_location|selectattr('attributes.source','eq','usgs_earthquakes_feed') %}
              {% if distance(s.entity_id,location) < km %}
                {{- s.entity_id -}}{{',' if not loop.last else ''}}
              {% endif %}
              {% endfor %}
```

95% of the time the map wont show, while the template is providing a list of geo_location entities.
Error in the log:
```
Error: Either entities or geo_location_sources must be specified
```

<img width="611" alt="Schermafbeelding 2021-04-21 om 23 04 42" src="https://user-images.githubusercontent.com/33354141/115620945-2026cb80-a2f6-11eb-9900-9a15c3dbb33c.png">

<img width="1362" alt="Schermafbeelding 2021-04-21 om 17 17 52" src="https://user-images.githubusercontent.com/33354141/115578376-87785780-a2c5-11eb-8f12-fc2268e8c9d9.png">

every now and then I see it pop up:

<img width="451" alt="Schermafbeelding 2021-04-21 om 16 57 59" src="https://user-images.githubusercontent.com/33354141/115578415-9232ec80-a2c5-11eb-8378-b4b061baeb41.png">

this card is part of a bigger conditional entities card, which all show, except for the map, which is the small red line obviously:

<img width="505" alt="Schermafbeelding 2021-04-21 om 17 19 08" src="https://user-images.githubusercontent.com/33354141/115578576-b55d9c00-a2c5-11eb-8ffb-2cfece6902ea.png">

I've also made this template into an attributes_template of another sensor, so the backend would do the work, but that doesn't make a difference.
```
{{state_attr('sensor.earthquakes_near','raw_list')}}
```
can't we do this?

**Comment by Mariusthvdb** [comment]
rewrite the title, as the above config could be mitigated using another template, and following issue seems to indicate a simpler cause:

auto-entities errors on using type: Map, when the filter doesnt result in entities, and the show_empty: false is set:
```
  - type: custom:auto-entities
    card:
      type: map
      title: Map Family abroad
      style: |
        .card-header {background-color: var(--primary-color);}
    show_empty: false
    filter:
      include:
        - entity_id: person.*_address
      exclude:
        - attributes:
            country_code: nl
```

results in the identical error as in the opening post:
<img width="537" alt="Schermafbeelding 2021-05-10 om 11 24 41" src="https://user-images.githubusercontent.com/33354141/117637707-5c757b00-b182-11eb-8c2c-2ee49c5ad8eb.png">

none of the entities are abroad (all have the attributes `country_code: nl`), so these are all excluded, leaving an empty list. 
This leads to the error, even though `show_empty: false` is set.
