### ISSUE TITLE
Feature Request: show "None" when empty

### ISSUE THREAD

**Issue by Spiffo** [thomasloven/lovelace-auto-entities#190]
You already have the "show_empty: false" option, but I would like to show the empty card but with a "None" text (in header or footer?) if no entities match the filter.

**Comment by thomasloven** [comment]
That's not feasible since the way to display an empty entity - if AT ALL possible - would differ for every type of card that exists, built-in or custom.

**Comment by tensiondriven** [comment]
I had a similar desire and came here to see if anyone else had requested this.

This could be achieved by displaying a different card using the same title and an optional string - Basically a "dumb" card that would just display "None" or a specified string when no entities were included.  Optionally a title could be set, so you wouldn't have to interrogate an existing card to get its title (if that's how it works under the hood (I actually don't know)).

```
show_empty_title: "Detected Entities"
show_empty_message: "Nothing to see here"
```

**Comment by mechanarchy** [comment]
I'm also wondering about this. We already have the `card` property which dictates what's shown normally; could a `card_empty` property be added to do the same when there are no entities?

In this situation, the user would have to completely specify the `card_empty` properties, there'd be no intelligent behaviour from `auto-entities` - as if the `auto-entities` card did not exist in the first place, and the dashboard contained only the `card_empty` configuration instead.

Here's a hypothetical example:
```
type: custom:auto-entities
card:
  type: vertical-stack
  title: System updates
card_param: cards
card_empty:
  type: markdown
  title: System updates
  content: |-
    You're all good! No updates required.
filter:
  include:
    - domain: update
      state: on
      options:
        type: custom:mushroom-update-card
        entity: this.entity_id
```
