### ISSUE TITLE
"count" option works only for global sort options

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#194]
Let's create a list of sensors with an `"unknown"` state:
```
type: vertical-stack
cards:
  - type: 'custom:auto-entities'
    card:
      type: entities
    unique: true
    show_empty: true
    filter:
      include:
        - domain: sensor
          state: unknown
          sort:
            method: name
            reverse: false
            ignore_case: true
            first: 0
            count: 5
            numeric: false
```
The output shows all sensors, not 5 as supposed:
![image](https://user-images.githubusercontent.com/71872483/118497161-7d634080-b72d-11eb-9d32-24a891ec8a25.png)

Then let's move the "sort" options to the “root” level:
```
type: vertical-stack
cards:
  - type: 'custom:auto-entities'
    card:
      type: entities
    unique: true
    show_empty: true
    filter:
      include:
        - domain: sensor
          state: unknown
    sort:
      method: name
      reverse: false
      ignore_case: true
      first: 0
      count: 5
      numeric: false
```
Now it works:
![image](https://user-images.githubusercontent.com/71872483/118497335-a683d100-b72d-11eb-8ff5-574795716ff6.png)
