### ISSUE TITLE
How to setup for pollen/health

### ISSUE THREAD

**Issue by henrikrox** [thomasloven/lovelace-auto-entities#200]
This works with entity filter

```
type: entity-filter
entities:
  - entity: sensor.pollen_00_today
  - entity: sensor.pollen_01_today
  - entity: sensor.pollen_02_today
  - entity: sensor.pollen_03_today
  - entity: sensor.pollen_04_today
  - entity: sensor.pollen_05_today
state_filter:
  - Low
  - Medium
  - High
card:
  type: glance
  title: Pollenvarsel i dag
```

How do i do this with your card so i can use card mod and use colors, tried everything, cant get it to work,
