### ISSUE TITLE
[howto] How do I only include the top level of devices?

### ISSUE THREAD

**Issue by ChrisWeiss** [thomasloven/lovelace-auto-entities#201]
I'm trying to make a card that lists all of my devices that are "unavailable", regardless of type (`switch`, `light`, `sensor`, etc.).

The issue I'm running into is that if I have a device with multiple child entities (for instance, an Aeon Multisensor) that is "unavailable", an entry is also created for each of it's child entities (IE - battery level, temperature, humidity, etc). I would like to only show the parent device

How would I go about doing this? I tried `unique: entity`, but that didn't seem to work.

An example of the definition I'm messing with:
```
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: Problem Children
  show_header_toggle: false
  unique: entity
filter:
  include:
    - state: unavailable
exclude: []
```
