### ISSUE TITLE
Enhancement: Allow passing additional card options on entities and at top level

### ISSUE THREAD

**Issue by iprak** [thomasloven/lovelace-auto-entities#203]
Currently one can define card `options` on filters but not on entities themselves. I locally modified auto-entities to allow `card options` to be defined at top level and overridden at entities and group level. I can submit a pull request if this enhancement sounds useful.

```
- type: custom:auto-entities
  card:
    type: entities
  card_options:
    entity: this.entity_id
    type: "custom:secondaryinfo-entity-row"
    style: |
      :host {--paper-item-icon-color: {% set value=state_attr(config.entity,"trending") %}{% if value=="up" -%} green {% elif value=="down" -%} red {% else %} var(--paper-item-icon-color)) {% endif %}; }
  entities:
    - entity: sensor.total_stocks
      name: Gain
      options:
        secondary_info: "[[ {entity}.attributes.cost_basis ]]"
  filter:
    include:
      - group: group.favorites
        options:
          secondary_info: "[[ {entity}.attributes.symbol ]]"
```

**Comment by thomasloven** [comment]
> Currently one can define card options on filters but not on entities themselves.

Yes you can. In exactly the same way as any other entities list of any other card.
Or, for that matter, in exactly the way you're doing it in your own example (??).

```yaml
type: custom:auto-entities
card:
  type: entities
entities:
  - entity: sensor.total_stocks
    name: Gain
    secondary_info: "[[ {entity}.attributes.cost_basis ]]"
    type: "custom:secondaryinfo-entity-row"
    style: |
      :host {--paper-item-icon-color: {% set value=state_attr(config.entity,"trending") %}{% if value=="up" -%} green {% elif value=="down" -%} red {% else %} var(--paper-item-icon-color)) {% endif %}; }
filter:
  include:
    - group: group.favorites
      options:
        secondary_info: "[[ {entity}.attributes.symbol ]]"
        type: "custom:secondaryinfo-entity-row"
        style: |
          :host {--paper-item-icon-color: {% set value=state_attr(config.entity,"trending") %}{% if value=="up" -%} green {% elif value=="down" -%} red {% else %} var(--paper-item-icon-color)) {% endif %}; }
```

Or if you don't like typing things twice:
```yaml
type: custom:auto-entities
card:
  type: entities
entities:
  - entity: sensor.total_stocks
    name: Gain
    <<: &options
      secondary_info: "[[ {entity}.attributes.cost_basis ]]"
      type: "custom:secondaryinfo-entity-row"
      style: |
        :host {--paper-item-icon-color: {% set value=state_attr(config.entity,"trending") %}{% if value=="up" -%} green {% elif value=="down" -%} red {% else %} var(--paper-item-icon-color)) {% endif %}; }
filter:
  include:
    - group: group.favorites
      options: *options

**Comment by iprak** [comment]
I was not aware of the 2nd syntax, that is pretty neat.

Would it be possible to define different `secondary_info` in that case?

**Comment by thomasloven** [comment]
Oh, sorry. I missed that they were different.
Just move them out of the anchor ([more info](https://github.com/thomasloven/hass-config/wiki/Misc-tricks#node-anchors)).
```yaml
<<: &options
  type: ...
secondary_info: First template

...

options:
  <<: *options
  secondary_info: Second template

```
