### ISSUE TITLE
card type: picture-entity doesn't work

### ISSUE THREAD

**Issue by Mearman** [thomasloven/lovelace-auto-entities#204]
Not 100% there isn't something wrong in my config, but I think this is an issue that `picture-entity` can't be used as the card type?

![Screenshot_20210617_210743](https://user-images.githubusercontent.com/1331872/122465709-54460200-cfb0-11eb-9384-bb4582880e5e.png)

```
type: custom:auto-entities
card:
  type: picture-entity
filter:
  include:
    - domain: camera
  exclude: []
```
