### ISSUE TITLE
Wildcard doesn't work in attributes filter

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#209]
trying to filter entities which have an attribute `custom_name` and a certain string in that attribute doesn't work when using the * in a string.
```
    filter:
      include:
        - attributes:
            custom_name: '*_custom'
```

yields nothing in the card, except the title. No error in inspector either.

if I use:
```
    filter:
      include:
        - attributes:
            custom_name: '*'
```

it shows all entities with an attribute `custom_name:` set, point blank. (btw, is this the only way we can auto-generate cards to show a certain attribute?)

so we either have all, or none?

please have a look? thanks.

**Comment by thomasloven** [comment]
Cannot reproduce

**Comment by ildar170975** [comment]
Works for me:
```
type: custom:auto-entities
card:
  type: entities
unique: true
filter:
  include:
    - domain: device_tracker
      attributes:
        source_type: rout*
sort:
  count: 5
```
![изображение](https://user-images.githubusercontent.com/71872483/154860316-70e73fe0-3734-4279-a1e9-2c9db9c7acb5.png)
