### ISSUE TITLE
Wildcards in string quoted, - quoted removed by Lovelace

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-auto-entities#210]
I am trying to combine this card with the custom:flex-table-card, displaying only certain entities that is unavailable. 
Looks like it picks up the correct entites but, cant get it to work with the "option: state:....".

Maybe because the wildcards Lovelace removes the  "":

```
type: custom:auto-entities
filter:
  include:
    - domain: light
      options:
        state: unavailable
    - entity_id: switch.*plug*
      options:
        state: unavailable
    - entity_id: binary_sensor.smoke_detector_alarm_smoke_detected*
      options:
        state: unavailable
    - entity_id: binary_sensor.flood_water_alarm_water_leak_detected*
      options:
        state: unavailable
card:
  type: custom:flex-table-card
  title: Unavailable sensors/lights/plugs
  columns:
    - name: Entity
      data: friendly_name
    - name: State
      data: state
```
![image](https://user-images.githubusercontent.com/35527507/125272863-9abb2200-e30c-11eb-8917-4724755aeafb.png)

Cant get this to work either:

```
type: custom:auto-entities
filter:
  include:
    - domain: switch
card:
  type: custom:flex-table-card
  title: Unavailable sensors/lights/plugs
  columns:
    - name: Entity
      data: friendly_name
    - name: State
      data: state
  filter:
    template: "{states.switch | selectattr('state', '==', 'unavailable') | list}}"
```
