### ISSUE TITLE
include: filter seems to be OR whereas documentation alludes to it being ALL

### ISSUE THREAD

**Issue by danielbrunt57** [thomasloven/lovelace-auto-entities#211]
If I add `include:`'s to the filter, they seem to be behaving as if I had them listed under an `or:`
The way I read the documentation, they should default to AND.
I.e. If I use:
```
type: custom:auto-entities
card:
  type: entities
  title: Low Batteries
filter:
  include:
    - domain: sensor
    - name: '*[Bb]attery*'
  exclude:
    - state: '>90'
    - state: off
    - state: discharging
sort:
  method: state
  reverse: false
  numeric: true

```
I get ALL sensors **_AND_** all entities where `[Bb]attery` is in the name.  
![image](https://user-images.githubusercontent.com/49846893/127598642-8d0ce38e-0c4f-48fb-b953-650efb681882.png)

What I want is all Sensors which have `[Bb]attery` in the name.
To achieve that, I've had to code this using a bunch of `exclude:`'s:
```
type: custom:auto-entities
card:
  type: entities
  title: Low Batteries
filter:
  include:
    - name: '*[Bb]attery*'
  exclude:
    - domain: automation
    - domain: input_text
    - domain: group
    - domain: device_tracker
    - entity_id: sensor.vog_l04_battery_health
    - entity_id: sensor.shower_motion_linkquality
    - state: '>90'
    - state: off
    - state: discharging
    - name: "*[Tt]emperature"
sort:
  method: state
  reverse: false
  numeric: true
```
![image](https://user-images.githubusercontent.com/49846893/127598893-70694b54-d005-49bc-b18c-b9d76a752523.png)

If filter: include: is now OR'ing the entries and this is by design, can we get an `and:` option?

**Comment by danielo515** [comment]
Yep, this behaviour is very confusing

**Comment by vhartmann** [comment]
I'm not sure whether the documentation changed since you opened the issue, but there's a section explaining the difference between AND & OR filters: https://github.com/thomasloven/lovelace-auto-entities#repeating-options

**Comment by danielbrunt57** [comment]
I don't know either but that is a subtle difference in hyphenation I probably missed before.  I'll have another go at it, thanks!

**AND**
```
filter:
  include:
    - state 1: "> 100"
      state 2: "< 200"
```
**OR**
```
filter:
  include:
    - state: "< 100"
    - state: "> 200"
```
