### ISSUE TITLE
Feature Request: collapse

### ISSUE THREAD

**Issue by Toukite** [thomasloven/lovelace-auto-entities#212]
Hello,
Would it be possible to add a collapse option ?
Same way than what is done here: https://github.com/maxwroc/battery-state-card

**Comment by WhistleMaster** [comment]
You could use `custom:fold-entity-row` and the following code as an example:

```
type: entities
title: Batteries
entities:
  - filter:
      include:
        - entity_id: '*battery_level*'
          state: < 25
        - attributes:
            battery: < 25
        - attributes:
            battery_level: < 25
    show_empty: true
    type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: Low Battery Devices
```
