### ISSUE TITLE
Error in numeric sorting

### ISSUE THREAD

**Issue by tcastberg** [thomasloven/lovelace-auto-entities#218]
There appears to be an error in numeric sorting for decimals. It would appear that devices with more decimals get counted as bigger numbers.

F.ex.: when sorting power consumption i get the following.
device 1: 4.7W
device 2: 0.16W
device 3: 0.9W

**Comment by filikun** [comment]
Now mine does not have more decimals but I have some random numeric sorting as well and I guess these problem could be the same. 

![image](https://user-images.githubusercontent.com/9947929/136344186-c27f545d-a861-4f21-a815-d6e219900a52.png)
![image](https://user-images.githubusercontent.com/9947929/136344205-02266f19-7b1a-4cc2-983c-bc5bfea2d9b7.png)

**Comment by jchhenderson** [comment]
I have the same issues with simple dates:
![Screenshot 2021-11-16 at 16 44 00](https://user-images.githubusercontent.com/34644672/142028002-ad441e63-bc55-426c-80c0-74903e00919c.png) ![Screenshot 2021-11-16 at 16 42 01](https://user-images.githubusercontent.com/34644672/142027677-35badb4e-4da4-4260-812f-a5ada9d1900b.png)

**Comment by ildar170975** [comment]
Do not confirm this for a state:
```
type: custom:auto-entities
card:
  type: entities
show_empty: false
filter:
  include:
    - entity_id: sensor.battery*
sort:
  method: state
  reverse: false
  numeric: true
```
![изображение](https://user-images.githubusercontent.com/71872483/145661254-d05f67c0-b4e1-43b6-bb52-ed49114abc33.png)
