### ISSUE TITLE
Does not work with state-switch card

### ISSUE THREAD

**Issue by drinfernoo** [thomasloven/lovelace-auto-entities#219]
Trying to include an `auto-entities` card in `state-switch` makes the card fail to appear.

Something like this:
```yaml
type: custom:state-switch
entity: hash
default: p1
states:
  p1:
    type: entities
    entities:
      - light.bedroom
      - light.living_room_lamp
  p2:
    type: custom:auto-entities
    card:
      type: entities
    entities:
      - light.aaralyn
      - switch.christmas_lights
```
When `p2` should be showing, no card is shown. It doesn't seem to matter which method `entity:` is set to (I've tried with `hash`, `user`, an entity ID, etc...), nor what parameters are used in the `auto-entities` card.

This appears to be the same issue as https://github.com/thomasloven/lovelace-state-switch/issues/59.
