### ISSUE TITLE
Always include/show some entities?

### ISSUE THREAD

**Issue by jonohunt** [thomasloven/lovelace-auto-entities#22]
Is it possible to create a card with this that **always shows** some entities, along with filtering other entities?

I tried with this (and a few variations) but didn't work

```
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: "Office"
    - filter:
        include:
          - entity_id: scene.office_off
          - entity_id: switch.imac_power
          - entity_id: switch.synology_power
          - entity_id: script.reboot_ubuntu_server
    - filter:
        include:
          - entity: light.office_ceiling_light
          - entity: light.office_wall_lights
          - entity: light.office_lamp
          - type: divider  
          - entity: switch.office_fan
      exclude:
      - state: "off"
      - state: "unavailable"
```

Ideally I'd like to show cards for each room, and always show certain scenes, scripts etc. but hide other lights and switches. I could then activate scenes from that card, or activate a popup card from displayed scenes or scripts to turn on lights individually.

If not possible please consider adding it as a feature request in the future :)

**Comment by thomasloven** [comment]
You could wrap auto-entities in another auto-entities

```yaml
type: custom:auto-entities
filter:
  include:
    - dynamic things
  exclude:
    - filter out dynamic things
  card:
    type: custom:auto-entities
    filter:
      include:
        - things to always include
    card:
      type: entities
```

Haven't tested it, but I *think* this should work...
card:

**Comment by jonohunt** [comment]
Sorry for the delay getting back to you on this! I'm on holiday at the moment and have limited internet access.

I've tried this, but it wouldn't work for me:






```
- type: custom:auto-entities
  show_empty: true
  card:
    type: entities
    title: "Testing"
    show_header_toggle: false
  filter:
    include:
      - entity_id: light.office_light
      - entity_id: light.landing_light
      - entity_id: light.hall_lamp
      - entity_id: light.outside_light
    exclude:
      - state: "off"
      - state: "unavailable"
    card:
      type: custom:auto-entities
      card:
        type: entities
      filter:
        include:
          - entity_id: light.desk_light
```

Also, I tried 'show_empty: true' in a normal auto-entities card (without wrapping multiple auto-entities) and it doesn't show the card until I turn on a light that's a listed entity.

Does that work OK for you?

**Comment by thomasloven** [comment]
Take another look at that indentation, and the order of things.
You can also try the new `not:` filter.

```yaml
filter:
  include:
    - entity_id: light.always_show_me
    - entity_id: light.show_me_sometimes
      not:
        - state: "off"
          state 2: "unavailable"
```
