### ISSUE TITLE
sort: reverse: true doesn't work on last_changed

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#221]
<img width="163" alt="Schermafbeelding 2021-09-29 om 23 14 57" src="https://user-images.githubusercontent.com/33354141/135349540-fec36a41-59f9-440f-9afd-aa08ad2f5a48.png">

```
      - type: custom:auto-entities
        card:
          type: entities
          <<: *mod
        show_empty: false
        filter:
          include:
            - entity_id: device_tracker.*_bt
              state: not_home
              options:
                secondary_info: last-changed
        sort:
          method: last_changed
          reverse: true
```

doesnt sort the entities in reverse order. Of all sorts and reverse variants in my config, this is the only not working. Dont know why I only noticed it just now, and dont think any update or recent change caused this. Seems like a bug?

please have a look? thanks!
