### ISSUE TITLE
Sorting doesn't respect options

### ISSUE THREAD

**Issue by joshuaspence** [thomasloven/lovelace-auto-entities#223]
The following card seems to sort based on the entity's name rather than `options.name`. I'm not sure if this is expected but I found it confusing.

```
  - type: 'custom:auto-entities'
    card:
      type: 'entities'
    filter:
      include:
        - entity_id: 'device_tracker.josh_laptop'
          options:
            name: 'C'
        - entity_id: 'device_tracker.josh_laptop'
          options:
            name: 'B'
        - entity_id: 'device_tracker.josh_laptop'
          options:
            name: 'A'
    sort:
      method: 'name'
```

**Comment by ildar170975** [comment]
I guess that sorting is performed by jinjia2 on the server side, but `name` option is provided on the frontend side.

Since you have only 3 (or 30) entities and you are providing the `name` option for every row - no sense to use `auto-entities` then.

**Comment by joshuaspence** [comment]
The example l posted above is a smaller code snippet to reproduce the bug. My actual configuration is different, but most of the configuration isn't relevant to the bug so I ommitted it.

**Comment by ildar170975** [comment]
I got your point.
There is one more example:
```
    type: custom:auto-entities
    card:
      type: entities
    entities:
      - entity: sensor.battery_cleargrass_2
        name: 123
      - entity: sensor.battery_life360_papa
        name: 123
    unique: entity
    show_empty: true
    filter:
      include:
        - domain: sensor
          entity_id: sensor.battery_*
    sort:
      method: name
```
Here the `name` option is not used for sort.
