### ISSUE TITLE
Feature request: support for "entity:" in e.g. chart series

### ISSUE THREAD

**Issue by AleXSR700** [thomasloven/lovelace-auto-entities#225]
I really love the idea of auto-entities and this is an awesome card!

I was creating a card in thread on the HA forum using `apexcharts-card` and `custom-config-card` to create a dynamically changeable plot.

The huge downside being, that I have to manually define the `input_select.sensors_to_show`. I think this is were auto-entities could come in and make this far more convenient and future proof.

Would it be possible to use auto-entities to define variables on-the-fly?

For this to work the auto-entities card would need to support "entity" instead of just "entities".

In this case and probably many other graph cards, entities would be part of a series with a sub "entity"

```
series:
  entity:
    - entity_1
    - entity 2
```

My current code is
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_select.days_back_to_show
        name: Number Of Days To Show
      - entity: input_select.sensors_to_show   #this is what auto-entities would need to supply
        name: Select Sensor
  - type: custom:config-template-card
    entities:
      - input_select.days_back_to_show
      - input_select.sensors_to_show
    variables:
      sensor: states['input_select.sensors_to_show'].state
      span: states['input_select.days_back_to_show'].state+'d'
      days: |
        -states['input_select.days_back_to_show'].state+'d'+'1d'
    card:
      type: custom:apexcharts-card
      graph_span: ${span}
      span:
        start: day
        offset: ${days}
      series:
        - entity: ${sensor}
          stroke_width: 2
          group_by:
            func: raw
```
So auto-entities could alternatively also create a variable if that would be easier to implement.
