### ISSUE TITLE
Support for shared/common options

### ISSUE THREAD

**Issue by danielo515** [thomasloven/lovelace-auto-entities#226]
Hello, as usual thanks for this awesome integration.
I have a situation where I have to setup multiple include filters, all with the same configuration option but with different requirements for being included: area, domain, etc

I am a bit tired of copy-pasting the same values over the several include entities. Is there a way to setup them on a root place and then just use the include to define what to include?

here is my example:

```yaml
type: custom:auto-entities
card:
  type: grid
  title: Salón
  columns: 6
  square: false
card_param: cards
filter:
  exclude:
    - name: poe*
  include:
    - domain: binary_sensor
      area: Salón
      options:
        type: custom:button-card
        show_state: true
        style: 'ha-card { box-shadow: none;}'
    - area: Salón
      domain: switch
      options:
        type: custom:button-card
        style: 'ha-card { box-shadow: none;}'
        show_state: true
    - area: Salón
      domain: light
      options:
        type: custom:button-card
        style: 'ha-card { box-shadow: none;}'
        hold_action:
          action: more-info

```
