### ISSUE TITLE
cannot add multiple dividers when unique is true

### ISSUE THREAD

**Issue by tomeeka** [thomasloven/lovelace-auto-entities#228]
Cannot add multiple dividers when unique is true.
Can you make an exception for "type: divider"?

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - entity_id: binary_sensor.zw_thermostat_*
    - entity_id: input_boolean.zw_thermostat_*
    - type: divider
    - entity_id: sensor.zw_thermostat_temperature
    - entity_id: sensor.zw_thermostat_humidity
    - type: divider
    - entity_id: sensor.zw_thermostat_*
      sort:
        method: entity_id
  exclude: []
unique: true

```
Thanks!

**Comment by ildar170975** [comment]
Confirm this.
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - entity_id: input_number.test_n*
    - entity_id: input_boolean.test_*
    - type: divider
    - entity_id: sensor.xiaomi_cg*
    - entity_id: sun.sun
    - type: divider
    - entity_id: person.i*
      sort:
        method: entity_id
unique: true
```
![image](https://user-images.githubusercontent.com/71872483/143329262-77e8284a-6155-4d80-a15c-0c80b83b95ea.png)

Only with using `unique: false` all dividers are shown.

**Comment by Mariusthvdb** [comment]
aware this is not a fix for the core divider, but you could use custom:text-divider-row, which would make it unique because of the text you set for that?

```
  filter:
    include:
      - entity_id: sensor.*_[[type]]
        not:
          entity_id: '*buiten*'
        sort:
          method: name
      - type: custom:text-divider-row
        text: Buiten
      - entity_id: '*buiten_*_[[type]]'
        sort:
          method: name
```
