### ISSUE TITLE
Template does not work with 'state' or 'states'

### ISSUE THREAD

**Issue by superx3man** [thomasloven/lovelace-auto-entities#231]
```
  - type: custom:auto-entities
    filter:
      template: "{{states.cover.dining_room_blinds.entity_id}}"
    card:
      type: glance
```
results in error of `jinja2.exceptions.UndefinedError: 'state' is undefined`

i'm using lovelace_gen also in the same file.
