### ISSUE TITLE
`auto-entities` inserts extraneous `entity` option into the destination card

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#234]
Let's create a stack of graph cards.

Here is one graph card w/o auto-entities:
```
type: custom:apexcharts-card
series:
  - entity: sensor.cleargrass_1_co2
graph_span: 1h
```
![image](https://user-images.githubusercontent.com/71872483/143331216-c7cda166-77ee-41b3-9ef2-f24553ef180e.png)

The code for the stack:
```
type: custom:auto-entities
card:
  type: vertical-stack
  title: auto-stack
unique: true
show_empty: true
card_param: cards
filter:
  include:
    - entity_id: sensor.cleargrass_1_*
      options:
        type: custom:apexcharts-card
        series:
          - entity: this.entity_id
        graph_span: 1h
```
The output:
![image](https://user-images.githubusercontent.com/71872483/143331885-5709c6d6-139e-4cbe-b58a-21c1d529a789.png)

Seems that `auto-entiites` inserts an `entity` option into the destination card.
Since `apexcharts-card` does not accept extraneous options - the error is shown.

The error is not shown when using with `history-graph` card since the `history-graph` accepts extraneous options:
![image](https://user-images.githubusercontent.com/71872483/143332116-4019b1f5-c6dd-425c-bcb3-0c11fac7397a.png)

But the `apexcharts-card` gives an error:
![image](https://user-images.githubusercontent.com/71872483/143332234-c6f8709a-ffcc-4bf1-93d6-57c53873290e.png)
