### ISSUE TITLE
FR: add integration/device entities to filter options

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#235]
given the new power of `{{integration_entities('Philips Hue')}}` and [{{device_entities(device_id('Philips Hue'))}}](https://next.home-assistant.io/docs/configuration/templating/#devices) (and the demise of many attributes we could use before to determine to which integration an entity belonged before, please add both integration and device to the filter options.

So maybe we can use
```
filter:
  include:
    - integration: Philips Hue
      entity_id: *temperature
```

or
```
filter:
  include:
    - device:
        device_id: Philips Hue
```

thanks for considering
