### ISSUE TITLE
Sorting with negative amounts

### ISSUE THREAD

**Issue by iwanvandaele** [thomasloven/lovelace-auto-entities#236]
The sorting on negative amounts is not working:

![image](https://user-images.githubusercontent.com/56552821/144296444-a45a92b5-7934-46a2-8cfc-d63594ec4222.png)

sort:
  method: state
  reverse: true
  numeric: true

Regards,
Iwan Vandaele

**Comment by ildar170975** [comment]
Do confirm this:
```
  - type: custom:auto-entities
    card:
      type: entities
    show_empty: false
    filter:
      include:
        - entity_id: input_number.test_negative*
    sort:
      method: state
      reverse: false
      numeric: true
```
```
  test_negative_1: &ref_test_nagative_values
    min: -10000
    max: 10000
    step: 0.1
    mode: box
  test_negative_2: *ref_test_nagative_values
  test_negative_3: *ref_test_nagative_values
  test_negative_4: *ref_test_nagative_values
  test_negative_5: *ref_test_nagative_values
  test_negative_6: *ref_test_nagative_values
  test_negative_7: *ref_test_nagative_values
  test_negative_8: *ref_test_nagative_values
  test_negative_9: *ref_test_nagative_values
  test_negative_10: *ref_test_nagative_values
  test_negative_11: *ref_test_nagative_values
  test_negative_12: *ref_test_nagative_values
  test_negative_13: *ref_test_nagative_values
```
![изображение](https://user-images.githubusercontent.com/71872483/145662096-cf63079d-2dcb-44a0-bf8b-fe03dc129104.png)
