### ISSUE TITLE
options not functional on Map card

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#241]
using a simple auto-entities with a map card showing the persons not home:

```
        - type: custom:auto-entities
          card:
            type: map
          show_empty: false
          filter:
            include:
              - domain: person
                options:
                  hours_to_show: 48
                  dark_mode: true
                not:
                  state: home
```
neither of the options is processed, and the Maps shows a light background, and no traces.

testing the core map card with verbose entities:

```
  - type: map
    entities:
      - person.me
    hours_to_show: 48
    dark_mode: true
```

works just fine.

please have a look?

__EDIT__

My huge pardon, and a just as big user error here.... sorry. completely misplaced the options, which simply go under the type: map...

```
        - type: custom:auto-entities
          card:
            type: map
            hours_to_show: 48
            dark_mode: true
```
is all there is to it.

Again: sorry.
