### ISSUE TITLE
FR: allow entity_id for numeric state trigger

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#242]
please consider allowing a config like:

```
        filter:
          include:
            - entity_id: sensor.*_actueel
              state: '> input_number.power_threshold' # or states('input_number.power_threshold')
```

which would prevent some more complex templating (including iterating over all states.sensor.), like:
```
        filter:
          template: >
            {% set threshold = states('input_number.power_threshold')|float %}
            {% set ns = namespace(above_threshold=[]) %}
            {% for s in states.sensor
             |selectattr('entity_id', 'search', '_actueel')
             if s.state|float > threshold %}
            {% set ns.above_threshold = ns.above_threshold + [s.entity_id] %}
            {% endfor %}
            {{ns.above_threshold}}
```

https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger allow us to do that since some time, would be great if auto-entities could follow suit in that regard.

**Comment by thomasloven** [comment]
Templates are very heavy lifting for the frontend. That's why there's only a single template filter which will have to do everything.

**Comment by Mariusthvdb** [comment]
maybe I didnt phrase correctly, but I didnt mean to ask for templating, I was thinking to these numeric triggers:
```
automation:
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature
```

to be used as:
```
        filter:
          include:
            - state: '> input_number.power_threshold'
```
