### ISSUE TITLE
FR: dynamic filter

### ISSUE THREAD

**Issue by tj551955** [thomasloven/lovelace-auto-entities#246]
I'm trying to create a list with a dynamic filter like so:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - attributes:
        fuel_type: '{{ states("input_select.fuel_type").lower() }}'
      options:
        type: custom:button-card
        styles:
          card:
            - background-color: yellow
  exclude: []
```
The statement `'{{ states("input_select.fuel_type").lower() }}'` returns a string but unfortunately one have to add a static string instead.
Would it be possible to implement this dynamic behaviour?

Cheers.
