### ISSUE TITLE
Auto-entities doesn't work with many columns inside layout-card

### ISSUE THREAD

**Issue by Spirituss** [thomasloven/lovelace-auto-entities#248]
Here is my lovelace config:

```
views: 
- title: Auto 
  visible:
    - user: xxxxx
  cards:
    - type: custom:layout-card 
      layout_type: vertical
      layout:
        # width: 300
        max_cols: 3
      cards:           
        - type: custom:auto-entities
          show_empty: true
          show_header_toggle: false
          card:
            title: New
            type: entities 
            show_header_toggle: false
          filter:
            include:
              - domain: automation
        - type: custom:auto-entities
                ...
        - type: custom:auto-entities
                ...
```

I would like to output auto-entities in 3 vertical colums, that’s why I use tags ‘layout_type: vertical’ and ‘layout: max_cols: 3’, but it doesn’t work with auto-entities unlike entities card or many others. Lovelace shows only 1 column.

See also https://community.home-assistant.io/t/how-to-show-auto-entities-in-layout-card-in-3-columns/381700.
