### ISSUE TITLE
It is possible to get the icon of the entity_id?

### ISSUE THREAD

**Issue by Klagio** [thomasloven/lovelace-auto-entities#25]
I have this code, and works well: when the listed entity_id have power above 2 are shown in the card. Unfortunately are shown not with its icon, but with the generic FLASH icon, is it possible to change this?
```

      - id: power_on
        type: custom:auto-entities
        show_empty: true
        card:
          type: entities
          title: Switch consuming power
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.dining_room_ac_power"
              state: "> 2"
            - entity_id: "sensor.guest_room_ac_power"
              state: "> 2"

```
