### ISSUE TITLE
configs with attributes throw error

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#251]
on the new version 1.10.0 I am seeing a lot of:
```
Unhandled Promise Rejection: TypeError: t.startsWith is not a function. (In 't.startsWith("$$")', 't.startsWith' is undefined)
```

<img width="557" alt="Schermafbeelding 2022-02-20 om 17 03 19" src="https://user-images.githubusercontent.com/33354141/154851924-b8766be5-3df0-4dea-a73a-99f38cc02ce0.png">

and I havent found a specific card yet, because it throws on many views....

as simple as:
```
  - type: custom:auto-entities
    card:
      type: entities
      title: Hue groups
      show_header_toggle: false
    show_empty: false
    filter:
      include:
        - attributes:
            is_hue_group: true
```

yep that seems to be it, all config with attributes are erroring:

```
      exclude:
        - attributes:
            last_triggered: null
```

or 
```
          not:
            attributes:
              current: 0
```

and these cards dont show.
