### ISSUE TITLE
Alternative to show_header_toggle?

### ISSUE THREAD

**Issue by GollyJer** [thomasloven/lovelace-auto-entities#255]
I'm attempting to replace the lower card with the upper one.

<img width="362" alt="Screen Shot 2022-02-28 at 11 57 17 PM" src="https://user-images.githubusercontent.com/689204/156129732-0f7b2b4f-5b59-4a4c-8312-5a493a780230.png">

Is it possible to mimic the `show_header_toggle` functionality when using `auto-entities` to build the list of lights?

Here's the current code with the header toggle not working.
```yaml
type: entities
entities:
  - type: custom:auto-entities
    filter:
      include:
        - domain: light
          area: Dining Room
    card:
      type: custom:fold-entity-row
      head:
        type: custom:slider-entity-row
        entity: light.dining_room_light_group
    sort:
      method: entity_id
title: Dining Room
show_header_toggle: true
```
