### ISSUE TITLE
Custom element doesn't exist: auto-entities.

### ISSUE THREAD

**Issue by lpwevers** [thomasloven/lovelace-auto-entities#257]
I installed auto-entities 1.10.1 using HACS. However, when adding a card and try to use it I get the following error: "Custom element doesn't exist: auto-entities."

Below is the code for the card I'm trying to add.
```
type: custom:auto-entities
card:
  type: glance
  show_state: true
  show_name: true
  title: Afvalkalender
  show_icon: true
  state_color: false
filter:
  include:
    - entity_id: sensor.afvalinfo_*
  exclude:
    - state: unknown
    - entity_id: sensor.afvalinfo_today
    - entity_id: sensor.afvalinfo_tomorrow
sort:
  method: atribute
  attribute: days_until_collection_date
  numeric: true
```
I'm running Home Assistant 2022.3.0 on Home Assistant OS 7.4.

**Comment by rmurfster** [comment]
I'm having the same issue.

**Comment by rmurfster** [comment]
I just clicked on Create Card and saw the "custom:auto-entities" as an option.  I successfully created my card with the following code:
```
type: custom:auto-entities
show_empty: true
card:
  type: glance
  title: Lights On
filter:
  include:
    - domain: light
      state: "on"
  exclude: []
  options:
    tap_action:
      action: toggle
```
