### ISSUE TITLE
Get entity ieeeAddr state and add buttons

### ISSUE THREAD

**Issue by svh1985** [thomasloven/lovelace-auto-entities#258]
Hello,

I'm trying to list the Z2M devices that have OTA Updates available and add the ability to initiate an update.

Listing the devices works great, but now I want to add a button and publish via the mqtt.publish service the ieeeAddr.

I came up with the code below, which works, publishes if I click the row, but it publishes the value "entity.ieeeAddr" not its real device ieeeAddr. Is there a way to get that value?

Also is it possible to change the toggles below with "Update" buttons?
<img width="391" alt="image" src="https://user-images.githubusercontent.com/5213210/156893920-4bd3ff8a-03e7-4464-94e0-9a54663e62de.png">

Thanks!

```
type: custom:auto-entities
card:
  type: entities
  title: OTA updates
  show_header_toggle: false
filter:
  include:
    - domain: light
      options:
        secondary_info: last-changed
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: zigbee2mqtt/bridge/request/device/ota_update/update
            payload: entity.ieeeAddr
      attributes:
        update_available: true
```
