### ISSUE TITLE
Sorting entities ala Monster Card

### ISSUE THREAD

**Issue by IAmTheDude** [thomasloven/lovelace-auto-entities#26]
Thanks for this update to the Monster Card, moved most of mine over to AutoE.

The one thing I am missing from the MC is the way it 'sorts' as explained at the bottom of the docs on MC:

>Entities are displayed in the card in the order they are matched by the include filters. I.e. to get >a specific order, detailed filters must precede more general ones.

> The following example will display sensor.my_sensor followed by all other sensors in alphabetical order:
> ```
> - type: custom:monster-card
>   card:
>     type: entities
>   filter:
>     include:
>       - entity_id: sensor.my_sensor
>       - entity_id: sensor.*
> ```

What Im finding is the `sensor.*` would ignore the set entities above it and only display the rest.

AutoE displays the top three then the rest in alphabetical order _including_ the top three again.

MC Example:
```
card:
  show_header_toggle: false
  title: Container - Switch Off
  type: entities
filter:
  include:
    - entity_id: switch.ha_docker_homeassistant
      state: 'on'
    - entity_id: switch.ha_docker_node_red
      state: 'on'
    - entity_id: switch.ha_docker_mosquitto
      state: 'on'
    - entity_id: switch.ha_docker_*
      state: 'on'
type: 'custom:monster-card'
```
This would display the top three and _only_ the remaining switches, not including the top three.

I have a second MC as the above that filters on 'off' so the ones I have set are always at the top rather than alphabetical.

If you could implement that it would be brill :)

Thanks again (and hope that all makes sense)
