### ISSUE TITLE
Only populate unique entity names by last updated

### ISSUE THREAD

**Issue by ChipWolf** [thomasloven/lovelace-auto-entities#260]
I'm looking for a way to populate a card with uniquely [display] named entities by their last update time.

My use case is populating entities of domain `device_tracker` on the `map` card.
There are multiple entities with the same display name from different integrations _(notably the mobile app and the iCloud integrations)_.
I'd like the most recently updated entities to show on the map, no more than one of each display name.

Thanks!

Current config:

<img width="309" alt="Screenshot 2022-03-10 at 12 27 32" src="https://user-images.githubusercontent.com/3164166/157661666-2b319eac-3de9-428c-8ceb-93a4c171d36c.png">

```yaml
type: custom:auto-entities
show_empty: false
card:
  type: map
  default_zoom: 13
  hours_to_show: 12
  aspect_ratio: '16:9'
  geo_location_sources:
    - all
filter:
  include:
    - domain: device_tracker
  exclude:
    - state: home
unique: entity
```
