### ISSUE TITLE
Is the integration: Times of the day (tod) - supported?

### ISSUE THREAD

**Issue by cinghialino** [thomasloven/lovelace-auto-entities#261]
Hello, I have a few binary_sensors made with the integration `tod` [https://www.home-assistant.io/integrations/tod/](url)

but when I'm using the auto-entities card set up as example, it doesn't seem to find any sensor `on`

```
type: custom:auto-entities
filter:
  include:
    - integration: tod
  exclude: []
show_empty: true
sort:
  method: last_changed
card:
  show_name: true
  show_icon: true
  show_state: true
  type: glance
  title: Times of the Day
```

is this integration supported?

**Comment by ildar170975** [comment]
Try using this:
```
    filter:
      template: '{{integration_entities("tod") }}'
```

**Comment by cinghialino** [comment]
This worked, thank you. Still wondering about the other way.

```
type: custom:auto-entities
filter:
  template: '{{integration_entities("tod") }}'
  exclude: 
    - state: off
show_empty: true
sort:
  method: last_changed
card:
  show_name: true
  show_icon: true
  show_state: true
  type: glance
  title: Times of the Day 
```
