### ISSUE TITLE
Feature request: hide value

### ISSUE THREAD

**Issue by sigitm** [thomasloven/lovelace-auto-entities#263]
Hello,
I have an auto-entities widget where I include only certain binary sensors with 'on' state .

Therefore, I don't need to read "On" (or "Connected", "Unlocked" etc.. based on its domain) for every row.

I'd like to have an option to hide sensor values. All the horizontal row space would be used to show the sensor icon and description.

It would be useful when horizontal space is not much (e.g. on mobile phones).

Here's a mockup:

now:
![image](https://user-images.githubusercontent.com/17519086/158653530-0021e929-bc3a-43d0-bbc4-e7f033b74585.png)

with hidden values
![image](https://user-images.githubusercontent.com/17519086/158653552-ff6967a1-3b9e-4a8b-ae32-716ddbe9e598.png)

Thanks

**Comment by ildar170975** [comment]
Could be already achieved by:
- template-entity-row
- card-mod

```
type: vertical-stack
cards:
  - type: custom:auto-entities
    <<: &ref_settings
      card:
        type: entities
      entities: []
      sort:
        count: 5
    filter:
      include:
        - domain: device_tracker
  - type: custom:auto-entities
    <<: *ref_settings
    filter:
      include:
        - domain: device_tracker
          options:
            type: custom:template-entity-row
            entity: this.entity_id
            state: ''
  - type: custom:auto-entities
    <<: *ref_settings
    filter:
      include:
        - domain: device_tracker
          options:
            card_mod:
              style:
                hui-generic-entity-row $: |
                  .text-content:not(.info) {
                    display: none;
                  }
```
![изображение](https://user-images.githubusercontent.com/71872483/158693148-01bc95b1-b32e-40e5-96a5-2289f811b7c6.png)
