### ISSUE TITLE
attributes filter 'entity_id' doesn't work (on domain light)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#267]
trying to select all light groups (light entities that contain an attribute 'entity_id' I tried the straightforward filter but is doesnt work:

```
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - domain: light
              attributes:
                entity_id: '*'
```

<img width="530" alt="Schermafbeelding 2022-03-31 om 09 52 12" src="https://user-images.githubusercontent.com/33354141/161005395-d754f0b0-2314-4eec-8212-b31884f7afb1.png">

this is surprising because a straight copy of that for domain scene and attribute 'group_name' works just fine:
```
          - type: custom:auto-entities
            card:
              type: entities
            filter:
              include:
                - domain: scene
                  attributes:
                    group_name: '*'
```
What is working, is this template filter:
```
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          template: >
            {{states.light|selectattr('attributes.entity_id','defined')
              |map(attribute='entity_id')|list}}
```

<img width="514" alt="Schermafbeelding 2022-03-31 om 09 50 57" src="https://user-images.githubusercontent.com/33354141/161005146-5aade536-4a25-4372-95ab-70759d3acbb8.png">

please have a look why this doesnt work, and if it can be fixed. It would allow for much easier configuration in the options....

Maybe related?
https://github.com/home-assistant/core/issues/68836 was fixed in https://github.com/home-assistant/core/pull/68875

in dev tools state:

<img width="1290" alt="Schermafbeelding 2022-03-31 om 09 49 37" src="https://user-images.githubusercontent.com/33354141/161004943-15a81e64-5079-4fcd-b7dc-f875e38f8dd8.png">

for testing purposes I did:
```
          include:
            - attributes:
                entity_id: '*'
```
and then becomes apparent that only a mere fraction (20) of the (121) states with attribute 'entity_id' get selected. 

<img width="815" alt="Schermafbeelding 2022-03-31 om 09 59 45" src="https://user-images.githubusercontent.com/33354141/161006699-d73e47ce-3418-4728-aa9c-dcbcea03cd98.png">

what's more, trying to use option on a template config like:
```
        filter:
          template: >
            {% for l in states.light|selectattr('attributes.entity_id','defined') %}
            {{
              {
              'type': 'custom:slider-entity-row',
              'entity': l.entity_id
              }
            }}
            {%- endfor %}
```

which shows the list correctly in dev tools template, again shows an empty card in the frontend, and no errors in console

**Comment by Mariusthvdb** [comment]
Missed the section on Stringification:
this works:
```
  - type: custom:auto-entities
    card:
      type: entities
      title: Group lights auto
    filter:
      include:
        - domain: light
          attributes:
            entity_id: '$$*'
          options:
            type: custom:slider-entity-row
            toggle: true
```
