### ISSUE TITLE
FR: Add expand on nested groups (lights, switches etc)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#268]
now we have core expansion in nested groups (lights/switches/binary_thresholds etc) please consider adding support for that in auto-entities filter, with the group functionality:

```
        filter:
          include:
            - group: light.all_lights_only
              options:
                secondary_info: last-changed
```

however still only shows the first level of nesting

<img width="492" alt="Schermafbeelding 2022-03-31 om 12 43 24" src="https://user-images.githubusercontent.com/33354141/161037473-bf5b478f-738a-47f0-a430-d8ec14abb1e7.png">

and takes no advantage of the possibility https://github.com/home-assistant/core/pull/68875 brings us.

we still need to do:
```
        filter:
          include:
            - group: group.main_inside_lights
              options:
                secondary_info: last-changed
            - group: group.outside_flood_lights
              options:
                secondary_info: last-changed
            - group: group.terrace_outdoors_spots
              options:
                secondary_info: last-changed
            - group: group.guest_inside_lights
              options:
                secondary_info: last-changed
            - group: group.plafond_spots
              options:
                secondary_info: last-changed
```

or with the now fully capable light groups replacements. of those 'old' groups

```
        filter:
          include:
            - group: light.main_inside_lights
              options:
                secondary_info: last-changed
            - group: light.outside_flood_lights
              options:
                secondary_info: last-changed
            - group: light.terrace_outdoors_spots
              options:
                secondary_info: last-changed
            - group: light.guest_inside_lights
              options:
                secondary_info: last-changed
            - group: light.plafond_spots
              options:
                secondary_info: last-changed
```

please consider adding this new functionality (both for regular nested groups, as the modern variants)?
thanks!
