### ISSUE TITLE
"grid-area" under "view_layout" is not working 

### ISSUE THREAD

**Issue by rgogada** [thomasloven/lovelace-auto-entities#276]
"grid-area" under "view_layout" is not working .
its just ignoring this setting and rendering a 2 column grid

here is the code

```
  - type: 'custom:auto-entities'
    filter:
      include:
        - domain: camera
          options:
            type: custom:webrtc-camera
            entity: this.entity_id
            view_layout:
              grid-area: '{{ states.this.entity_id.entity_id.split(".")[1] }}'
    card:
      type: 'custom:layout-card'
      layout_type: custom:grid-layout
      layout:
        grid-template-columns: repeat(2, minmax(auto, 400px))
        grid-template-rows: auto
        grid-template-areas: '"frontyard frontyard" "entrance sideyard" "study stairs" "lounge backyard" "porch garage"'
        margin: auto
      cards: []

```
