### ISSUE TITLE
[FR] Management of more than 1 attribute

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-auto-entities#279]
Is there a way exclude/include more than 1 attribute ?
Like:

```yaml
  include:
    - domain: binary_sensor
      state: 'on'
      not:
        attributes:
          - device_class: connectivity
          - device_class: plug
```

If not, can you consider adding it as a feature ?

Thx in advance,

Simone

**Comment by ildar170975** [comment]
You may use several filters for one list:
```
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - domain: sensor
          attributes:
            device_class: temperature
          sort:
            count: 3
        - domain: sensor
          attributes:
            device_class: humidity
          sort:
            count: 3
```
![image](https://user-images.githubusercontent.com/71872483/163884228-f7d713d4-1ba6-43aa-874b-cbff22789eed.png)

**Comment by chemelli74** [comment]
> You particular case may be rewritten as:
> 
> ```
>   - type: custom:auto-entities
>     card:
>       type: entities
>     filter:
>       include:
>         - domain: binary_sensor
>           state: 'on'
>       exclude:
>         - attributes:
>             device_class: connectivity
>         - attributes:
>             device_class: plug
> ```

I would like to exclude only when "on" and not when "off" ;-)
This is why I need to filter inside the include and not in the exclude block.

Simone

**Comment by ildar170975** [comment]
> would like to exclude only when "on" and not when "off" ;-)

I think that my solution does what you need.

**Comment by ildar170975** [comment]
> cannot see how your solution can achive this goal

Have you tested my solution?

**Comment by chemelli74** [comment]
> > cannot see how your solution can achive this goal
> 
> Have you tested my solution?

I did, but just reading the code I can see that there is no `binary_sensor` on `off` mode, which is one of the request.

Simone

**Comment by ildar170975** [comment]
> I did

Did you get correct results in the output?

It is strange that I am trying to convince you to accept the solution.

**Comment by chemelli74** [comment]
> > I did
> 
> Did you get correct results in the output?

No, otherwise I would have a solution ;-)

> It is strange that I am trying to convince you to accept the solution.

It is, but I think you didn't get the point.

Let's try to make a full code sample:

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Active problems
  show_header_toggle: false
  state_color: true
filter:
  include:
    - domain: binary_sensor
      state: 'on'
      not:
        attributes:
          device_class: connectivity
    - domain: binary_sensor
      state: 'off'
      attributes:
        device_class: connectivity
      options:
        style: |
          :host {
            --paper-item-icon-color: var(--paper-item-icon-active-color)
    - domain: binary_sensor
      state: 'off'
      attributes:
        device_class: plug
      options:
        style: |
          :host {
            --paper-item-icon-color: var(--paper-item-icon-active-color)
sort:
  method: state
  reverse: true
  numeric: true
```

The above is nearly working; still need to exclude `binary_sensor` with state `off` and device_class `plug`

Simone
