### ISSUE TITLE
feature request: templating...

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#28]
Now you have adopted templating on the -mod cards, please consider adding this to the auto-entities-card:

```
    filter:
      include:
        - state: >
            {{in ['playing', 'idle', 'paused']}}
          domain: media_player
```
thanks!
