### ISSUE TITLE
[Feature request] sort method: device

### ISSUE THREAD

**Issue by AleXSR700** [thomasloven/lovelace-auto-entities#280]
Hello Thomas,
I am using your auto-entites a lot and really love the extreme convenience it adds to home assistant.

I am currently trying to imitate the default dashboard's ability to automatically add all new entities to a card. I want to have separate dashboards per area which I can then navigate to (rather than seeing all areas in the one big overview dashboard).

The only problem right now: the sorting is not really good and I cannot get it to sort properly.

```
type: custom:auto-entities
card:
  type: entities
  title: Living Room
  show_header_toggle: false
filter:
  include:
    - area: living_room
sort: 
  method: entity_id
```
The sort method would need to be 'device' instead of 'entity_id' or any other current option. I tried name, entity_id, domain etc. 

Would it be possible to add 'device' as sort method?

Thank you
Alex
