### ISSUE TITLE
Content of card not showing in Homeassistant App or in Chrome on cell phone

### ISSUE THREAD

**Issue by DirkStorck** [thomasloven/lovelace-auto-entities#281]
Hi,

I have created a card 

```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  color_gradient:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  icon: mdi:battery
  positions:
    icon: 'off'
    indicator: inside
    name: inside
  columns: 1
show_empty: false
filter:
  include:
    - entity_id: '*batterie*'
    - entity_id: '*battery*'
  exclude:
    - entity_id: '*temperature*'
    - entity_id: '*health*'
    - entity_id: '*state*'
    - entity_id: '*alarm*'
sort:
  method: state
  numeric: true
```
![grafik](https://user-images.githubusercontent.com/2306190/165079715-5ea671b7-2748-4eff-8fa4-6a42f39e0e23.png)

that card gets displayed without a problem on my dashboard if I open the dashboard in my web browser on my PC
![grafik](https://user-images.githubusercontent.com/2306190/165079973-fb00cedd-65fc-4871-bb6e-035c5145058a.png)

But If I open the same dashboard in Home Assistant app it is completely missing 

![grafik](https://user-images.githubusercontent.com/2306190/165080322-eb995b67-a20b-4fd5-a43e-453f9675cecf.png)

the same behavior if I open the app in chrome browser on my cell phone
