### ISSUE TITLE
Map may be not displayed if placed inside auto-entities

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#286]
Check this card:
```
type: custom:auto-entities
card:
  type: map
  title: Map Family abroad
show_empty: true
filter:
  include:
    - entity_id: person.*
```
The card is supposed to be displayed as below:
![изображение](https://user-images.githubusercontent.com/71872483/170589883-c8e44a84-8a1a-4475-ba7a-c04aa8bb75f2.png)

But most of time it is displayed as:
![изображение](https://user-images.githubusercontent.com/71872483/170589961-a260e0b8-fb23-4e61-9061-a59b2e925be8.png)

Th BUG mentioned here:
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/452?u=ildar_gabdullin
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801/329

**Comment by fanuch** [comment]
Do you get a different result with this?

```
type: custom:auto-entities
card:
  type: map
show_empty: true
filter:
  include:
    - domain: person
```
