### ISSUE TITLE
Feature Request: add filter for device_class

### ISSUE THREAD

**Issue by disforw** [thomasloven/lovelace-auto-entities#288]
Looking to add a filter option for device_class soon can group all moisture devices, or motions for example.

**Comment by disforw** [comment]
Sorry, just figured it out .. closing

**Comment by Dreanaught** [comment]
For my future self. The filter is:
```
filter:
  include:
    - attributes:
        device_class: temperature
```
