### ISSUE TITLE
bulk rename entites

### ISSUE THREAD

**Issue by Kilowatt-W** [thomasloven/lovelace-auto-entities#289]
Hello there,

thx for you nice work, I really like it.

I would have an idea 👍 
maybe its possible to make something like a bulk-rename for filtered entities ?

```
bulk_rename:
  - from: "battery"
  - to: ""
  - from: WIFI
  - to: "WLAN"
```

When I select some entities its most of the time with the same useless text in the display like :

WIFI Signal xxx
WIFI Signal xx1
.
..

This information could be removed because its always the same.

I saw this feature in the _custom:battery-state-card_ and find it really usefull.

Maybe you can get it from there or implement something similar ?

Greetings from Austria

Kilowatt
