### ISSUE TITLE
Unable to use include with an boolean attribute

### ISSUE THREAD

**Issue by guillaumelamirand** [thomasloven/lovelace-auto-entities#29]
Hi

I am trying to display a entities card from **zwave domain** with attribute **is_failed to true** using this settings :
```
card:
  title: 'Z-Wave Modules Down'
  type: entities
  show_header_toggle: false
filter:
  include:
    - domain: zwave
      attributes:
        is_failed: true
      options:
        secondary_info: last-changed
show_empty: true
type: 'custom:auto-entities'
```
Unfortunatly it is not working, the card doesn't show up even if no entities are matching the filter. I even tries with ``` is_failed: '= true'```, ``` is_failed: '! false'```, nothing seams to work as expected.

I do some test with other attribute as boolean type (is_wake, is_ready) it seams that the "true" "false" value are used for testing it the attribute is present.

Anyway thanks for your custom card !

**Comment by thomasloven** [comment]
Hi.

Please try this with the latest version and let me know if there's still a problem. I can't reproduce it.

**Comment by guillaumelamirand** [comment]
Hi,

Still not working. If I tried with is_failed: false or is_ready: false which should not find any module, nothing is displayed even with 'show_empty: true'.

**Comment by thomasloven** [comment]
Just to make things clear before I pour a lot of time into this...

Is this unique to when you're using boolean attributes?
Do you have other auto-entities cards in your interface that *do* show up when they are empty?

**Comment by WhistleMaster** [comment]
Same issue here. The following was working with monster-card:

```
card:
  type: glance
filter:
  exclude:
    - state: 'off'
    - state: unavailable
    - entity_id: '*group*'
    - attributes:
        is_deconz_group: false
  include:
    - domain: light
      options:
        tap_action:
          action: toggle
show_empty: false
type: 'custom:auto-entities'
```

**Comment by guillaumelamirand** [comment]
Yes I

> Just to make things clear before I pour a lot of time into this...
> 
> Is this unique to when you're using boolean attributes?
> Do you have other auto-entities cards in your interface that _do_ show up when they are empty?

Yes I have some other card which are displayed when empty. The issue is only when I used boolean attributes.

**Comment by WhistleMaster** [comment]
I did go back to monster-card, which is working fine with Boolean attributes in the mean time.

**Comment by ConinoxConinox** [comment]
I'm here because I have the exact same problematic.
I'd like to have a card displaying my problematic zwave nodes.
In the template editor, `{{states.zwave.salle_manger_oeil.attributes.is_ready}}` give me `False`

If I try : 
```
- type: custom:auto-entities
      card:
        type: entities
        title: Zwave non fonctionnels
      filter:
        include:
          - domain: zwave
            attributes:
              is_ready: False
```

My card is empty.

And if I try : 
```
- type: custom:auto-entities
      card:
        type: entities
        title: Zwave non fonctionnels
      filter:
        include:
          - domain: zwave
            
       exclude:
         - attributes:
              is_ready: True
```

My card is full with all my nodes.

I've tried with `false`, `"false"`, `False`, `"False"` and same thing with true.

**Comment by thomasloven** [comment]
Since I'm still unable to reproduce this problem, could anyone please provide an example configuration of an entity where things don't work?
Is it unique to zwave?

**Comment by WhistleMaster** [comment]
The following does not work:

```
card:
  type: glance
filter:
  exclude:
    - state: 'off'
    - state: unavailable
    - entity_id: '*group*'
    - attributes:
        is_deconz_group: false
  include:
    - domain: light
      options:
        tap_action:
          action: toggle
show_empty: false
type: 'custom:auto-entities'
```
