### ISSUE TITLE
Skip first 'X' does not work without count

### ISSUE THREAD

**Issue by IIStevowII** [thomasloven/lovelace-auto-entities#291]
Hi,

I would like to display everything except the first X entries, but it seems the `first` parameter does not work without the `count` parameter. (As i don't know what the total amount is, I can't fill in a Count). Ofcourse a work-around for this is to just add `count: 999999` but it would be nice if `first` would work like a `skip` when not using `count`.

Below example will display the two entities (of the two available):
```
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: sensor.prullenbak_*
          sort:
            method: attribute
            attribute: days
            numeric: true
            reverse: false
            first: 1
    card:
      type: entities
```
![afbeelding](https://user-images.githubusercontent.com/4059224/175322415-2d402bbe-ef11-4912-a7f5-b058279b0069.png)

The following will correctly skip the first one and only display one entity:
```
  - type: custom:auto-entities
    filter:
      include:
        - entity_id: sensor.prullenbak_*
          sort:
            method: attribute
            attribute: days
            numeric: true
            reverse: false
            first: 1
            count: 999
    card:
      type: entities
```
![afbeelding](https://user-images.githubusercontent.com/4059224/175322372-c23826b7-3ba5-4edd-b3b1-e54e410ccff8.png)
