### ISSUE TITLE
picture-entity not working

### ISSUE THREAD

**Issue by blaickgaming** [thomasloven/lovelace-auto-entities#297]
I know that this topic was already brought up in another [issue](https://github.com/thomasloven/lovelace-auto-entities/issues/204). Still, even after following the links that were provided in the answer, there weren't any examples that explained what was missing. 

I tried to follow the instructions in this [example](https://github.com/thomasloven/lovelace-layout-card#use-with-entity-filters), but it doesn't seem to work as it should:

```
type: custom:auto-entities
filter:
  Include:
    - domain: camera
      state: recording
card:
  type: custom:layout-card
  layout_type: masonry
  cards:
    - type: picture-entity
      show_state: false
      show_name: false
```

It's only showing me the default card by displaying the current state, which doesn't help when trying to see a camera.
