### ISSUE TITLE
battery state is not "full"

### ISSUE THREAD

**Issue by h4nc** [thomasloven/lovelace-auto-entities#3]
What a great component to track battery states. This already works fine with battery that report a certain value.

However netatmo devices report their state in "full" and other states I don't know yet (because all are full).

Is it possible to add the possibilty to for a "not_state".

something like this 

```
filter:
  include:
    - domain: sensor
      not_state: "full"
```

or is this already possible, maybe like this?

```
filter:
  include:
    - domain: sensor
      state: "! full"
```
