### ISSUE TITLE
Show empty not functioning for entities card

### ISSUE THREAD

**Issue by tomlut** [thomasloven/lovelace-auto-entities#30]
Show empty functions correctly for a glance card:
```
type: 'custom:auto-entities'
show_empty: true
card:
  type: glance
  title: Doors Open
filter:
  include:
    - entity_id: "binary_sensor.*door"
      state: 'on'
```

![Screenshot_2019-10-29 Home Assistant(1)](https://user-images.githubusercontent.com/10679300/67732171-9c688780-fa4e-11e9-899b-9369803e3e1c.png)

But not for an entities card:
```
type: 'custom:auto-entities'
show_empty: true
card:
  type: entities
  title: Doors Open
filter:
  include:
    - entity_id: "binary_sensor.*door"
      state: 'on'
```
![Screenshot_2019-10-29 Home Assistant](https://user-images.githubusercontent.com/10679300/67732223-bd30dd00-fa4e-11e9-9c12-d2de1634e11e.png)

Note that `binary_sensor.*door` was quoted but the UI editor strips out the quotes when the card is saved and then opened again for editing.
