### ISSUE TITLE
How to make it work with custom:history-explorer-graph

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [thomasloven/lovelace-auto-entities#306]
Hi,

is there any way to make this gem work with the https://github.com/alexarch21/history-explorer-card?

I get the following entity data for the history explorer card:

```yaml
entities:
  - entity_id: "123"
 ```

whereas I need something like this:

```yaml
graphs:
  - type: "line"
     entities:
       - entity: "123"
```

Any chance I can make a convertion? I saw card_params, but this is not sufficient?
