### ISSUE TITLE
Repeated blank tiles

### ISSUE THREAD

**Issue by sam-ward** [thomasloven/lovelace-auto-entities#31]
I have just setup auto-entities to show the battery level of all my battery powered devices (using a custom:bar-card).  Initially it displays fine, but then some time later it will draw a number of additional "empty card outlines".  If I hover over one of the empty cards, it actually contains the same contents as the original card, just everything is invisible. The below screenshot tries to show what I am seeing.  If you look closely you can see the outline of the additional cards.

![image](https://user-images.githubusercontent.com/765012/68485953-1ed91e80-027b-11ea-83c2-faba907613ec.png)

**Comment by sam-ward** [comment]
Should have also added, this is the config of the card:
```
type: 'custom:auto-entities'
card:
  type: 'custom:bar-card'
  columns: 1
  height: 20
  title_position: inside
  align: split
  rounding: 0px
  severity:
    - value: 30
      color: '#bf4040'
    - value: 60
      color: '#bf9540'
    - value: 100
      color: '#40bf40'
  unit_of_measurement: '%'
  width: 100%
  title_style:
    font-size: 12px
  value_style:
    font-size: 10px
filter:
  include:
    - entity_id: sensor.*_battery
  exclude:
    - entity_id: sensor.*iphone*
show_empty: false
unique: true
```
