### ISSUE TITLE
"Filter, Exclude, Not" not working

### ISSUE THREAD

**Issue by niecore** [thomasloven/lovelace-auto-entities#313]
Hello,

I am expecting that the following card would list me all temperature and illuminance sensors from the area `office` but instead humidity/temperature sensors off all rooms are listed:

```
type: custom:auto-entities
card:
  type: glance
filter:
  include:
    - domain: sensor
      attributes:
        device_class: temperature
    - domain: sensor
      attributes:
        device_class: illuminance
  exclude:
    - entity_category: diagnostic
      not: 
        area: office
```

The `not` special parameter within the exclude section is not working for me.
