### ISSUE TITLE
Can't remove state from display

### ISSUE THREAD

**Issue by MikeGuest** [thomasloven/lovelace-auto-entities#314]
Hi.

Think i'm doing this right. I have an auto-entities card for devices with status unknown. I want to save some screen real-estate by removing the display of the status 'unavailable' - as I already know that information otherwise the device would not be in my list

The list should contain all members of a group plus all temperature sensors (excluding my curtains which inexplicably present as temperature sensors) (Excluding sensors with a state >-100 excludes all except unavailable)

However show_state does not appear to do anything
```
  - type: custom:auto-entities
    card:
      title: Offline
      type: entities
      show_state: false
    filter:
      include:
        - group: binary_sensor.group_monitor_binary_sensors 
        - domain: sensor
          attributes:
            device_class: temperature
      exclude:
        - state: "off"
        - state: "on"
        - state: ">-100"
        - name: "*Curtain*"
    show_empty: true 
```    
    
![Capture](https://user-images.githubusercontent.com/12844043/199248337-4c54be5e-2858-433d-9c5b-02e08bea5af5.PNG)
