### ISSUE TITLE
Support for new tile card

### ISSUE THREAD

**Issue by bkbilly** [thomasloven/lovelace-auto-entities#319]
The new Tile card released by Home Assistant 2022.11.0 doesn't show anything if I write something like this:
```yaml
type: custom:auto-entities
filter:
  include:
    - device: AlarmPI
  exclude: []
sort:
  method: state
  reverse: false
  ignore_case: false
  numeric: false
show_empty: true
card:
  type: tile
```

If I leave the card type as `entities` which is the default it works perfectly.

It would be nice to show the new tile cards.

**Comment by jason0x43** [comment]
The issue here is that `custom:auto-entities` doesn't create a bunch of whatever is provided to `card` (that threw me off for a while, too). Rather, it provides a list of entity IDs to the `entities` property of whatever card type is specified in `card`.

By default, it uses an Entities card. It will create a single Entities card and set that card's `entities` property to be the auto-created list of entities.

Tile cards only work with a single entity, so they can't be used as the base `card` for `custom:auto-entities`.

Entity-level properties can be specified using filter options. I was able to use the tile card in a grid layout by specifying it in the filter options. The layout below has `custom:auto-entities` populate a `custom:layout-card` with Tile cards for my temperature and humidity sensors.

```yaml
type: custom:auto-entities
card:
  type: custom:layout-card
  layout_type: custom:grid-layout
  layout:
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr))
    grid-template-rows: auto
    cards: []
  filter:
    include:
      - domain: sensor
        entity_id: '/.*(temp|humidity).*/'
        options:
          type: tile
```

**Comment by bkbilly** [comment]
Thanks for the recommendation!

**Comment by alexwohlbruck** [comment]
here's a variant of @bkbilly's that doesn't require any other custom cards:

```yaml
type: custom:auto-entities
show_empty: false
sort:
  method: friendly_name
card:
  type: grid
  columns: 2
  square: false
  card_margin: 4px
filter:
  include:
    - domain: light
      state: 'on'
      options:
        type: tile
card_param: cards
```

<img width="496" alt="Screenshot 2024-12-29 at 10 46 46 AM" src="https://github.com/user-attachments/assets/82a881b2-bccd-4444-9e45-55d3d51c76fc" />

**Comment by goetzc** [comment]
> ```yaml
> type: custom:auto-entities
> show_empty: false
> card:
>   type: grid
>   columns: 2
>   square: false
> filter:
>   include:
>     - domain: light
>       state: 'on'
>       options:
>         type: tile
> card_param: cards
> ```
> 
> <img alt="Screenshot 2024-12-29 at 10 46 46 AM" width="496" src="https://private-user-images.githubusercontent.com/10440826/399172009-82a881b2-bccd-4444-9e45-55d3d51c76fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMTExMDQsIm5iZiI6MTc0MDAxMDgwNCwicGF0aCI6Ii8xMDQ0MDgyNi8zOTkxNzIwMDktODJhODgxYjItYmNjZC00NDQ0LTllNDUtNTVkM2Q1MWM3NmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjIwVDAwMjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYWUwMGYxNmRmNDgyMTY0OGY1YjA0NDM3NzY0NWRiNzE5OTE2ZjVmZjZhMzE4ZjU1MDVlZmU4YjAwMTBiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YoSmKw7c6z8VRVwbotON1TP_PA-WcOHXOq6jOFJroUc">
> 
>
> something like this should be added to the examples list as I think it is a very nice use case

That's very helpful, thanks. Agree that it should be added to a easier to find examples section.

**Comment by goetzc** [comment]
BTW is it possible to automatically short the items by area?

**Comment by BlakeTrebelhorn** [comment]
> Does anyone know a way to disable the state colour in this configuration? I tried adding `state_color: false` wherever i could and it didn't seem to work!

it's `color: disabled`, this is what i got working, thanks to this thread:

```yaml
type: custom:auto-entities
show_empty: false
card:
  type: vertical-stack
filter:
  include:
    - options:
        type: tile
        name:
          - type: area
          - type: entity
        state_content: brightness
        vertical: false
        features_position: inline
        features:
          - type: light-brightness
      domain: light
      state: "on"
  exclude:
    - options: {}
      label: dummylight
    - options: {}
      label: group
card_param: cards

```
