### ISSUE TITLE
show_empty doesn't work with template-entity-row

### ISSUE THREAD

**Issue by shaymdev** [thomasloven/lovelace-auto-entities#322]
I'm using template-entity-row to show entities that "need attention". Each row has its own condition (if garbage day is today, if the vacuum sensors need cleaning, if a window was left open, etc).

If there are no entities "needing attention" I want the whole card to disappear.

I'm trying to use the auto-entities card to achieve this but the way it triggers "empty" or not doesn't work with the way template-entity-row hides its row based on condition. 
 
 Is there another way to achieve what I'm hoping for? If not does this seem like a reasonable enhancement to the auto-entities card?

**Comment by ildar170975** [comment]
Do not observe the same.

Card:
```
type: custom:auto-entities
card:
  type: entities
  title: title
show_empty: false
filter:
  include:
    - domain: person
      state: xxxxxx
      options:
        type: custom:template-entity-row
```

When `state: xxxxxx` line is removed:
![image](https://user-images.githubusercontent.com/71872483/207762899-cb5caf7e-ca90-40b3-938e-6e81a04641e1.png)

With this line:
![image](https://user-images.githubusercontent.com/71872483/207762946-2522c437-505e-417d-8f65-810b41530bbd.png)

**Comment by shaymdev** [comment]
You're right, I should have included some code! That will probably be the quickest to show you guys that I'm doing it wrong 😆 
It's likely that what you say about the condition being too complex and that I need to do some template filter is the case... but I'm pretty new to this stuff and don't know my way around too well.

Here's my code as it stands now. 

```
type: custom:auto-entities
card:
  type: entities
  title: Need Attention
entities:
  - type: custom:template-entity-row
    entity: sensor.recycle_day
    condition: '{{state_attr(''sensor.recycle_day'', ''days'') <= 1}}'
  - type: custom:template-entity-row
    entity: sensor.garbage_day
    condition: '{{state_attr(''sensor.garbage_day'', ''days'') <= 1}}'
  - type: custom:template-entity-row
    entity: input_boolean:thermostats_enabled
    icon: mdi:thermometer
    state: Thermostat is disabled
    condition: '{{is_state(''input_boolean.thermostats_enabled'', ''off'')}}'
  - type: custom:template-entity-row
    name: Robo Vacuum
    icon: mdi:robot-vacuum
    state: Replace main brush
    condition: '{{state_attr(''vacuum.robo'', ''main_brush_left'') <= 1}}'
  - type: custom:template-entity-row
    name: Robo Vacuum
    icon: mdi:robot-vacuum
    state: Replace side brush
    condition: '{{state_attr(''vacuum.robo'', ''side_brush_left'') <= 1}}'
  - type: custom:template-entity-row
    name: Robo Vacuum
    icon: mdi:robot-vacuum
    state: Replace filter
    condition: '{{state_attr(''vacuum.robo'', ''filter_left'') <= 1}}'
  - type: custom:template-entity-row
    name: Robo Vacuum
    icon: mdi:robot-vacuum
    state: Clean sensors
    condition: '{{state_attr(''vacuum.robo'', ''sensor_dirty_left'') <= 1}}'
  - type: custom:template-entity-row
    entity: sensor.samba_backup
    condition: '{{is_state(''sensor.samba_backup'', ''FAILED'')}}'
show_empty: false
```

![image](https://user-images.githubusercontent.com/3431219/208516607-f9e3d55a-a858-4f3d-b918-8e235060f6cb.png)
