### ISSUE TITLE
Exclude filter doesn't show up in the UI

### ISSUE THREAD

**Issue by Kisty** [thomasloven/lovelace-auto-entities#331]
Adding an exclude filter doesn't seem to be supported. Am I missing something?

Auto Entities Card: 1.12.0
Home Assistant Core: 2023.1.1

**Comment by david-steg** [comment]
I juste used "exclude filter" with:

> Auto Entities Card: 1.12.1
> Home Assistant Core: 2023.1.1

and it works just fine.
my exemple:
```
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: Templates
        filter:
          include:
            - entity_id: /sensor.tp_/
          exclude:
            - state: unavailable
```
