### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by david-steg** [thomasloven/lovelace-auto-entities#332]
Hello

I'm trying to sort the entitities by Battery Level or by Name, but none of them works.
The entities List look like this:
![image](https://user-images.githubusercontent.com/71213394/211152209-021973f3-252f-4146-af2d-3f5045e96a93.png)
and the card: 
```
- type: custom:auto-entities
        card: 
          type: entities
          title: Battery
        filter:
          include:
            - name: /BATTERY/
        sort:
          methode: attribute
          numeric: true
```

I tried multiple sort: name, entity_id, state. But none of them have any impact on the list.

I don't know if this is a Bug or a mistake from my side.

Thank You.
