### ISSUE TITLE
else does not work for custom button card

### ISSUE THREAD

**Issue by sroebert** [thomasloven/lovelace-auto-entities#334]
I am trying to display a custom button card in the case that auto entities is not displaying any entities. The button however does not show up. I do not see any error in the console either.

```
type: custom:auto-entities
else:
 type: custom:button-card
 entity: some_entity_id
```

If I put the same button code outside of auto-entities, it works correctly. Also if I use a normal entity card in `else` it works correctly. Any idea what I can do to fix or debug this?
