### ISSUE TITLE
Feature: Remove borders

### ISSUE THREAD

**Issue by metbril** [thomasloven/lovelace-auto-entities#335]
I have an auto-entities card inside a fold-entity-row. That card has borders that show up in the unfolded view. See example images and yaml.

Is it possible to move the border around the auto-entities card (with an additional parameter)?

```yaml
type: entities
entities:
  - entity: sensor.yaml_config_lines
  - type: custom:fold-entity-row
    head: sensor.count_entities
    entities:
      - type: custom:auto-entities
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - entity_id: sensor.count_*
          exclude:
            - entity_id: sensor.count_entities
            - state: '= 0'
        sort:
          method: name
```
![image](https://user-images.githubusercontent.com/559346/212729638-bcfaba9b-8536-46bf-b3a2-087defa2730a.png)

![image](https://user-images.githubusercontent.com/559346/212729694-d9ac7233-3e78-41aa-a6cd-e36a3a9e626a.png)
