### ISSUE TITLE
Using "* ago" or similar to filter on state (timestamp)

### ISSUE THREAD

**Issue by mario-tux** [thomasloven/lovelace-auto-entities#337]
I'm using standard "Certificate Expiry" sensors (https://www.home-assistant.io/integrations/cert_expiry) to check problematic and "expiring soon" Let's Encrypt certificates. In the state I got the timestamp (format like `2023-04-15T15:43:56+00:00`). 
I don't understand if I can use the documented attributes "* ago" filters also for `state` like:
```
filter:
  include:
    - entity_id: sensor.cert_expiry_timestamp_*
      state: '> 30 days ago'
```
I want to use something like "with a timestamp state smaller than 30 days from now". Is it already supported or possibile?

Thanks
