### ISSUE TITLE
filter entities having / not having specific attribute 

### ISSUE THREAD

**Issue by Akinetopsia1** [thomasloven/lovelace-auto-entities#341]
For example i am trying to list device_tracker entities of a given source_type only if the friendly_name attribute is present and set to something, while **ignoring those without that attribute**. 

Conversely on a second card i'd want to match **only** those of the same source_type this time **without** that attribute

**Comment by bkbilly** [comment]
I was just looking for the same thing for the Steam integration and I've come up with this:
```yaml
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - integration: steam_online
      attributes:
        game: "! None"
    - integration: steam_online
      not:
        attributes:
          game: "! None"
```

The 1st include shows the entities that have the attribute `game` and the 2nd shows the ones that don't have the game attribute.
