### ISSUE TITLE
sort by area not working?

### ISSUE THREAD

**Issue by prankousky** [thomasloven/lovelace-auto-entities#345]
Hi,

I have a card displaying all my `light` entities; it will work when I sort by `friendly_name`, but not by `area`; what am I doing wrong? Code and screenshots below. 

According to the documentation, this should work, [right](https://github.com/thomasloven/lovelace-auto-entities#sorting-entities)? It says 

> method: Required One of domain, entity_id, name, device, **area**, state, attribute, last_changed last_updated or last_triggered.

Thank you in advance for your help :)

### friendly_name

```yaml
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
      show_header_toggle: false
    filter:
      include:
        - domain: light
          options:
            secondary_info: last-changed
      exclude:
        - entity_id: '*screen'
        - entity_id: '*brightness'
        - entity_id: '*backlight'
        - entity_id: '*gruppe*'
        - entity_id: '*zeitschaltung*'
        - entity_id: '*test'
    sort:
      method: friendly_name
      reverse: false
    show_empty: true
```
![image](https://user-images.githubusercontent.com/11297070/219639005-53298200-2f70-4163-90b1-c30ca2712ad4.png)

### area

```yaml
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
      show_header_toggle: false
    filter:
      include:
        - domain: light
          options:
            secondary_info: last-changed
      exclude:
        - entity_id: '*screen'
        - entity_id: '*brightness'
        - entity_id: '*backlight'
        - entity_id: '*gruppe*'
        - entity_id: '*zeitschaltung*'
        - entity_id: '*test'
    sort:
      method: area
      reverse: false
    show_empty: true
```

![image](https://user-images.githubusercontent.com/11297070/219639303-bc46f1f5-599a-4821-bbe2-c8c54b65e088.png)
