### ISSUE TITLE
Sort: area not working?

### ISSUE THREAD

**Issue by kylepyke** [thomasloven/lovelace-auto-entities#347]
I've successfully created a list of entites, and all sort methods work except for `area`, which returns an empty list. Reverting the sort to `name` or any other method works correctly. Can anyone advise?

**Comment by kylepyke** [comment]
Sorry!

Here is my code:

```
type: entities
entities:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
    filter:
      include:
        - domain: light
      exclude:
        - hidden_by: user
        - state: 'off'
        - entity_id: light.*_lights
    sort:
      method: last_changed
```
This works, but changing the last line to `method:area` produces an empty card.
