### ISSUE TITLE
Long shot, but is there any way to feed the entities list into a Mushroom Chips card?

### ISSUE THREAD

**Issue by kylepyke** [thomasloven/lovelace-auto-entities#349]
This is one of my all-time favorite additions to HA. Thank you SO much for your work on this!

I love using the popular [Mushroom chips card](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/chips.md), because of it's customization and sleek interface options. I'm assuming it's impossible, but figured I'd ask those with more coding knowledge than me– is it possible to feed the auto-entities list into a Chips card? I've copied examples of caode below.

Common entities card:

```
type: entities
entities:
  - entity: switch.livingroom_humidifier
  - entity: light.living_room_lamp
  - entity: switch.living_room_speakers
title: Entities Example
```
Mushroom Chips card:

```
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: switch.livingroom_humidifier
  - type: entity
    entity: light.living_room_lamp
  - type: entity
    entity: switch.living_room_speakers
```

Thanks!!
