### ISSUE TITLE
What about "when" option?

### ISSUE THREAD

**Issue by darkkatarsis** [thomasloven/lovelace-auto-entities#35]
In the previous version of the card it was possible to show the entity when it meets the requirements of another status. Is it possible to add such functionality?

**example:** 

```
         - type: custom:monster-card
            card:
              type: entities
            filter:
              include:
                - entity_id: light.ambilight
                  options:
                    type: "custom:slider-entity-row"
                    toggle: true
            when:
              entity: media_player.samsungtv
              state: 'on'
```

**Comment by tatunts** [comment]
Hello! Yes, I am also interested on that too. Any workaround for that? Thanks!

**Comment by thomasloven** [comment]
There are better ways to get that functionality.

https://www.home-assistant.io/lovelace/conditional/

**Comment by tatunts** [comment]
Thanks @thomasloven!

I can see the conditional as a great solution.

Sorry to bother you but would mind taking a look at this card? I cannot figure out how make it to work:

```yaml
- entities:
    - binary_sensor.estado_do_bridge
    - input_boolean.zigbee_permit_join
    - type: conditional
      conditions:
        - entity: input_boolean.zigbee_permit_join
          state: 'on'
      card:
        type: entities
        entities:
          - timer.zigbee_permit_join
  show_header_toggle: false
  title: ZigBee
  type: entities
```

I get this:

![image](https://user-images.githubusercontent.com/25224882/68813437-8f55b600-0654-11ea-8fa0-9f1fa7ec6942.png)

Testing just the conditional part on a separated new manual card it works but not like this. I had something similar working before, using the when function.

Thanks a lot!

**Comment by darkkatarsis** [comment]
You cant use conditional card inside entities

**Comment by thomasloven** [comment]
Yes, you can, with `type: custom:hui-conditional-card`
https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality

But I admit the configuration will become pretty involved to get it right.

I'll reconsider.

**Comment by roblandry** [comment]
I had no idea this was possible as i was still using monster-card for this use purpose also. However after reading this, it is working great and i can sunset monster-card.

My working example:
```
- type: 'custom:hui-conditional-card'
  conditions:
    - entity: input_select.config
      state: Light
  card:
    type: custom:auto-entities
    card: 
      type: entities
      title: Light
    show_empty: true
    unique: true
    sort: 
      method: name
    filter:
      include:
        - domain: light
    entities:
      - entity: light.bathroom
      - entity: light.bathroom_light
```

**Comment by SBado** [comment]
Well, for the time being, here's a small patch. All credits go to rhodges ([here](https://community.home-assistant.io/t/is-there-an-easy-way-to-hide-entity-on-a-lovelace-card-based-on-state-of-another-entity/105065/7) his post on Home Assistant communit forum). I'm using it right now and it's working fine, but proper testing is needed:

```
diff --git a/src/filter.js b/src/filter.js
index 33db425..6d09686 100644
--- a/src/filter.js
+++ b/src/filter.js
@@ -139,6 +139,37 @@ export function entity_filter(hass, filter) {
             break;
           }
 
+        case "when":
+          {
+            for (var i = 0; i < value.length; i++) {
+              var val = value[i];
+              if (val.entity_id) {
+                const whenEntity = hass.states[val.entity_id];
+                if (whenEntity) {
+                  if (val.state) {
+                      if(!match(val.state, whenEntity.state))
+                        return false;
+                  }
+                  if (val.attributes) {
+                    for(const [k, v] of Object.entries(val.attributes)) {
+                      let attr = k.trim();
+                      let entityAttribute = whenEntity.attributes;
+                      while(attr && entityAttribute) {
+                        let step;
+                        [step, attr] = attr.split(":");
+                        entityAttribute = entityAttribute[step];
+                      }
+                      if(entityAttribute === undefined || (v !== undefined && !match(v, entityAttribute)))
+                        return false;
+                      continue;
+                    }
+                  }
+                }
+              }
+                       }
+            break;
+          }
+
         default:
           return false;
       }
```

Example usage:
```
  - type: custom:auto-entities    
    card:
      type: entities
      title: Test
      show_header_toggle: false
    filter:
        include:
          - entity_id: input_boolean.alarm_mode
          - entity_id: input_boolean.vacation_mode
          - entity_id: light.back_door_lights
            when:
              - entity_id: input_boolean.alarm_mode
                state: 'on'
```
In this example, light.back_door_lights will only be visible when input_boolean.alarm_mode is “on”.
