### ISSUE TITLE
Question: Is it possible to exclude depending of helper value?

### ISSUE THREAD

**Issue by sweede-se** [thomasloven/lovelace-auto-entities#354]
I wish to exclude all entities with a value lower then a input_number helper. Is that possible?

**Comment by ildar170975** [comment]
Possible only by using the "template" option.

**Comment by mindgam3s** [comment]
not really as you have to built the whole entity filter yourself then ..
if there would be support for placeholders or jinja templating inside the 'filter: include: state: ' block this would be really awesome!

eg:

```
type: custom:auto-entities
show_empty: false
card:
  title: critical batteries
  type: entities
  card_mod:
    style: |
      ha-card {
        --paper-item-icon-color: red;
      }
filter:
  include:
    - attributes:
        device_class: battery
      state: **< {{ states(input_helper.battery_treshold_critical) }}**
    - attributes:
        device_class: battery
      state: 'on'
  exclude: []
sort:
  method: state
  reverse: false
  numeric: true
```
