### ISSUE TITLE
Feature request: Possibility to add a Title to the auto-entities card

### ISSUE THREAD

**Issue by mathiasolofsson87** [thomasloven/lovelace-auto-entities#361]
It would be great to be able to add a title to the auto-entities card.

My use case is that I have for example 3 different auto-entities cards to keep track of any available updates to HA or integrations, checking if any battery powered devices are low on battery, if any devices are unavailable. all these auto-entities cards are set to be hidden if no entities match the filters.

Above the auto-entities cards I have a separate card with a title "Battery Status" "Updates" or "unavailable devices". However I cant conditionally hide the title card based on the auto-entities card. So when the auto-entities card is hidden, the title still displays. If I could add the title on the auto-entities card directly it would automatically be hidden together with the auto-entities card.

<img width="412" alt="Screenshot 2023-05-11 at 10 46 57" src="https://github.com/thomasloven/lovelace-auto-entities/assets/125729109/ad6cd656-b415-4e02-b51a-e455c52fe526">

**Comment by BebeMischa** [comment]
```
type: custom:auto-entities
show_empty: true
card:
  type: entities
  title: Lights on
  show_header_toggle: false
filter:
  include:
    - domain: light
  exclude:
    - state: 'off'
    - state: unavailable
```

This give s me a card with title:

![afbeelding](https://github.com/thomasloven/lovelace-auto-entities/assets/73079275/044cc067-8eb0-4484-8f1b-4b87798962b9)


Hope, that may help you ;-)
