### ISSUE TITLE
Custom element does not exist: auto-entities

### ISSUE THREAD

**Issue by JeffCrum1** [thomasloven/lovelace-auto-entities#362]
I just started getting this error.
HA 2023.5.3
Just added Piper and Wisper add-ons.

The error is on Windows 10 in Edge browser.  Works fine on our Android phones.  So, the wife is not yelling at me :)

What can I give you to help diagnose?

Here is the code.  It has been working for weeks.  the two add-ons is the only change that started giving the error:
```
type: custom:auto-entities
unique: true
show_empty: false
card:
  type: entities
filter:
  template: >-
    {%- for team in integration_entities("teamtracker") -%}
        {{{"type": "custom:teamtracker-card","entity": team }}},
    {%- endfor -%}
  exclude:
    - entity_id: '*team_tracker*'
options: null
sort:
  method: last_changed
  attribute: date
  reverse: true
  numeric: false
  ignore_case: false
```
