### ISSUE TITLE
Feature Request - Sort by a 2nd value

### ISSUE THREAD

**Issue by daloki83** [thomasloven/lovelace-auto-entities#367]
I created this config with all of my sensors for power meassurements including a switch to turn them on/off. But what ever i try, i'm not able to sort by the "power"-entitie/value. It always uses the state from the switch. Is there any way to do this or if not to implement?
```
type: custom:auto-entities
card:
  type: entities
  state_color: false
sort:
  method: state
  reverse: true
  numeric: false
  ignore_case: false
  ip: false
entities:
  - entity: switch.arbeit
    type: custom:multiple-entity-row
    toggle: true
    state_color: true
    entities:
      - entity: sensor.arbeit_energy_power
        name: ' '
  - entity: switch.fritz_box7590ax
    type: custom:multiple-entity-row
    toggle: true
    state_color: true
    entities:
      - entity: sensor.fritz_box7590ax_energy_power
        name: ' '
```
![Screenshot 2023-06-09 234048](https://github.com/thomasloven/lovelace-auto-entities/assets/29686097/ad52f052-5f91-482c-b6d8-6f8110556d9c)

**Comment by ildar170975** [comment]
Probably this is same as https://github.com/thomasloven/lovelace-auto-entities/issues/363 - i.e. about 2nd sort method.
You may use more than 1 sorting method when using a `template` option.

**Comment by daloki83** [comment]
Okay, but I cannot find and example or explanation for that. Could you provide a sample please?

**Comment by ildar170975** [comment]
For instance:
```
    filter:
      template: >-
        {{ states.binary_sensor |
           selectattr('entity_id','search','battery_charging') |
           sort(reverse=false,attribute='entity_id') |
           sort(reverse=false,attribute='state') |
           map(attribute='entity_id') | list }}
```

**Comment by daloki83** [comment]
Hmm not really working for me. I added:
```
filter:
  template: >-
    {{ states.sensor | selectattr('entity_id','search','_power') |
    sort(reverse=true,attribute='entity_id') |
    sort(reverse=false,attribute='state') | map(attribute='entity_id') | list }}
```
and he added every sensor with a power attribute to the rest of my sensors. I think i could exclude unwanted sensors, but how could i than bring back the Power-Switch button

**Comment by daloki83** [comment]
Made it now this way for all devices so....can be closed here


```
type: custom:auto-entities
card:
  type: entities
  state_color: false
entities:
  - entity: sensor.arbeit_energy_power
    name: Arbeit
    type: custom:multiple-entity-row
    entities:
      - entity: switch.arbeit
        name: ' '
        toggle: true
        state_color: true
```
![Screenshot 2023-06-11 091538](https://github.com/thomasloven/lovelace-auto-entities/assets/29686097/efdfd766-607b-4b69-87f1-b72f2edf8a0b)

**Comment by prankousky** [comment]
I am trying to achieve this as well. I would like to sort my sensors **first** by state (`display "on" at the top), then by **either** friendly_name **or** last_changed (so "on" still on top, but sorted by 2nd sort, then "off" underneath, also sorted by 2nd sort).

This is my code; what would I have to add / change to get the results I need?

```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
    filter:
      include:
        - entity_id: binary_sensor.draussen_einfahrt_motion_3
          options:
            secondary_info: last-changed
        - entity_id: binary_sensor.draussen_einfahrt_motion_2
          options:
            secondary_info: last-changed
        - entity_id: binary_sensor.oben_bad_occupancy_aqara_presence
          options:
            secondary_info: last-changed
        - entity_id: binary_sensor.*_presence_presence
          options:
            secondary_info: last-changed
        - entity_id: '*_occupancy'
          options:
            secondary_info: last-changed
        - entity_id: '*motion'
          options:
            secondary_info: last-changed
        - entity_id: binary_sensor.blink_keller_motion_detected
          options:
            secondary_info: last-changed
      exclude:
        - entity_id: '*global*'
        - entity_id: switch.*
        - state: unavailable
        - entity_id: automation.*
    sort:
      method: state
      reverse: true
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
    filter:
      include:
        - entity_id: '*tuer_contact'
          state: 'on'
          options:
            secondary_info: last-changed
        - entity_id: '*fenster_contact'
          state: 'on'
          options:
            secondary_info: last-changed
      exclude: []
```

Screenshot

As you can see, these are sorted by state. But other than that, it seems randomly. They are neither sorted by alphabet, nor by last_changed. 

![grafik](https://github.com/thomasloven/lovelace-auto-entities/assets/11297070/491dd20a-36b4-4665-bb9c-bf10bc42c949)
