### ISSUE TITLE
Is it possible to filter by unset values?

### ISSUE THREAD

**Issue by igorsantos07** [thomasloven/lovelace-auto-entities#370]
I didn't find in the docs if it's possible to filter by an empty or unset field/attribute. I tried leaving the value empty, as `''`, as `null` or `undefined` (I know this ain't JS, but...), to no avail.

Is that possible? If not, maybe a new `unset` option (which would work similarly to `or`, having anything inside it, but ignoring values) could be created?

**Comment by ildar170975** [comment]
> I tried leaving the value empty, as `''`, as `null` or `undefined`

Tried with all these & `none`, does not work.
The only way seems to be using a `template` option:
```
type: custom:auto-entities
card:
  type: entities
filter:
  template: >-
    {{ states.binary_sensor | rejectattr('attributes.device_class','defined') | map(attribute='entity_id') | list }}
sort:
  count: 15
```

**Comment by dcapslock** [comment]
This is posisble using both 'not' and '$$'

e.g. Looking for light entities which are not a group. The `$$*` matches where JSON.stringify of the field has a value. An empty field has not value so this will not match. Include this as `not` and job done :-)

```yaml
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: light
      not:
        attributes:
          entity_id: $$*
  exclude: []
```
