### ISSUE TITLE
auto-entities working together with mini-media-player?

### ISSUE THREAD

**Issue by kalle2000** [thomasloven/lovelace-auto-entities#372]
Hi,

I am trying to populate my media players using auto-entities. I want to use the [mini-media-player](https://github.com/kalkih/mini-media-player) card.

However I am struggling to get my multiple entities displayed (error: You need to specify the required entity option):

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/16741825/209b6f03-9f90-4252-a7ec-c2debb345202)

What am I missing here?
Thanks for the help.

**Comment by ildar170975** [comment]
> What am I missing here?

Start with posting a code, not a picture of it.

**Comment by ildar170975** [comment]
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/c5929636-b0f9-48db-9cde-8d810b1c9a46)

```
    type: custom:auto-entities
    card:
      type: vertical-stack
    card_param: cards
    filter:
      include:
        - domain: media_player
          options:
            type: custom:mini-media-player
```
