### ISSUE TITLE
Cannot exclude MacBook model from list of batteries

### ISSUE THREAD

**Issue by stevegroom** [thomasloven/lovelace-auto-entities#375]
Setting up a card to show all batteries, I exclude some device models that I do not want to see, but cannot set a generic rule to exclude MacBook running the HomeAssistant app.

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Batteries
  state_color: true
filter:
  exclude:
    - device_model: ZBMINIL2
    - device_model: Smart-UPS_1000
    - device_model: '*iPad*'
    - device_model: '*iPhone*'
    - entity_id: sensor.macbook_pro_steve_internal_battery_level
    - entity_id: sensor.macbook_pro_steve_internal_battery_state
  include:
    - entity_id: sensor.*battery*
sort:
  method: state
  reverse: false
  numeric: true
```

In the filter exclude section I tried to exclude device_model: Mac14,10 and '*Mac*' etc, but did not succeed in suppressing entities of my MacBook Pro from the results. In the end I had to explicitly exclude by entity_id
