### ISSUE TITLE
"Integration" filter: not all entities are listed (possibly only entities with unique_ids)

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#377]
Consider these templates:
```
{{ integration_entities("scrape") }} 
{{ integration_entities("history_stats") }} 
{{ integration_entities("derivative") }}  
```
All of them give lists of entities related to these integrations.

But none of them work with auto-entities.

Derivative (3 made in yaml, 1 in UI) - gives 1 entity created in UI:

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/83a9d55b-f78c-4b14-99a0-f5a0c18f48bc)

history_stats (15..20 entities) - gives only 3 (for which I intentionally defined unique_ids):

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/b66f23b6-3373-42cf-9bb7-270e09c8734f)

Scrape (2 entities) - gives only 1 (for which I intentionally defined unique_id):

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/ec6cd565-a788-4eee-a853-2504fad0b504)

My guess is: auto-entities gives only entities with unique_id defined if the `integration` filter is defined.

**Comment by Jeppedy** [comment]
And using **template: "{{integration_entities('Supervisor')}}"** works in auto-entities when used as a template filter, but not when I use "Supervisor" in the "integration: " filter.

Enabling only the template filter works, but the include / integration filter does not.
```
type: custom:auto-entities
card:
  type: entities
  title: Add-on Updates (auto)
filter:
  template: "{{integration_entities('Supervisor')}}"
  include:
    - integration: "Supervisor"
  exclude: []
sort:
  method: friendly_name

```

**Comment by ildar170975** [comment]
> And using template: "{{integration_entities('Supervisor')}}" works in auto-entities when used as a template filter, but not when I use "Supervisor" in the "integration: " filter.

Like I said.

**Comment by erkr** [comment]
I like to chime in: I noticed the same issue that not all entities are included. It's not the unique_id! It's yaml vs UI configuration.

I add this very simple filter:
``` 
    filter:
      include:
       - integration: group
``` 
Only the entities that are created via the UI are shown (helpers-group), not the ones I created in yaml

**Comment by ildar170975** [comment]
>  It's not the unique_id! It's yaml vs UI configuration.

All entities created in UI have unique-id ))).

**Comment by erkr** [comment]
I added unique_id's in yaml:

light groups:
 - platform: group
   name: Lampen tuin
   unique_id: lampen_tuin
   entities:
    - light.1
    - light.2
    - light.3
    - light.4

**Comment by ildar170975** [comment]
Yes, same I did in my setup:
added `unique_id` for a `history_stats` sensor defined in yaml - then this sensor was shown with this filter:

![Image](https://github.com/user-attachments/assets/8c471bdf-11b5-4d3e-bc6d-0b0bb1fb548e)

**Comment by erkr** [comment]
Well that is weird, for my group integration adding the unique id in yaml doesn't include them in the card. All yaml defined groups are missing (only get them with the template)

**Comment by ildar170975** [comment]
> light groups:

Are you sure that this entity eas created?

**Comment by erkr** [comment]
Yes!

**Comment by ildar170975** [comment]
Well, here is my test:
```
light:
  - platform: group
    name: some lights
    entities:
      - light.kitchen_ceiling
      - light.bathroom_ceiling
    # unique_id: fsdlfjseljflsekfjslek-fjslefjflsfs

light groups:
  - platform: group
    name: some lights xxx
    # unique_id: fsdfsfdfdfkfjslek-fjsl44efjflsfs
    entities:
      - light.kitchen_ceiling
      - light.bathroom_ceiling
```
which creates 2 groups w/o unique_id (& thus not editable in UI):

![Image](https://github.com/user-attachments/assets/bc0814e1-e910-4421-ba76-37a20a950fe2)

And these entities are not seen for auto-entities:

![Image](https://github.com/user-attachments/assets/c6bb49c6-40f0-47f0-99a4-573135a02d8f)

Then uncomment `unique_id` lines in yaml, reload groups.
Entities becomes editable:

![Image](https://github.com/user-attachments/assets/c776672a-59ed-492e-8eef-e824d629ad9b)

and occur in auto-entities:

![Image](https://github.com/user-attachments/assets/46e687dd-6681-4d08-acc0-1552351bfdae)
