### ISSUE TITLE
Terrible performance on Fire Tablets

### ISSUE THREAD

**Issue by madasus** [thomasloven/lovelace-auto-entities#379]
Hello,

I've been trying to figure out why my fire tablets are running slowly (i know - they are always slow) but i believe it is being caused by the auto-entities card.  When I remove it from my dashboard the performance returns to normal.

I am running v1.12.1

Here is my YAML.  Any ideas why this might be causing slowness? I have a lot of entities in my instance and the goal of this it to show me open security related items (doors, windows, garage doors, etc)

Is there a good way to optimize?

Thank you

M

```
type: custom:auto-entities
card:
  type: entities
  title: House Security
filter:
  include:
    - device: omnilink
      domain: binary_sensor
      state: 'on'
    - domain: cover
      state: open
    - domain: lock
      state: unlocked
    - domain: lock
      state: locking
  exclude:
    - domain: binary_sensor
      attributes:
        device_class: motion
    - entity_id: binary_sensor.light_sensor
    - entity_id: binary_sensor.generator_on
    - entity_id: cover.*somfy_shade*
sort:
  method: last_updated

```
