### ISSUE TITLE
Unique option not filtering duplicates

### ISSUE THREAD

**Issue by OppyLock** [thomasloven/lovelace-auto-entities#38]
Migrating from monster card, where it filtered duplicates by default.
I added in the unique: true parameter, but i still get duplicate media_player.plex entities.

```
card:
  show_header_toggle: false
  title: Media Players
  type: entities
filter:
  include:
    - entity_id: 'media_player.plex*'
      options:
        artwork: cover
        group: true
        hide:
          power_state: false
          progress: false
          runtime: false
          volume: false
        icon: 'mdi:plex'
        idle_view:
          when_idle: true
        info: scroll
        type: 'custom:mini-media-player'
    - domain: media_player
      options:
        artwork: cover
        group: true
        hide:
          power_state: false
          progress: false
          runtime: false
          volume: false
        idle_view:
          when_idle: true
        info: scroll
        type: 'custom:mini-media-player'
  exclude:
    - state: idle
    - state: 'off'
    - state: unavailable
    - entity_id: media_player.ua55c8000_samsung_dtv_rcr
show_empty: false
unique: true
type: 'custom:auto-entities'
```

**Comment by thomasloven** [comment]
I assume you get one 
```yaml
entity_id: media_player.plex_whatever
artwork: cover
group: true
hide:
  power_state: false
  progress: false
  runtime: false
  volume: false
icon: 'mdi:plex'
idle_view:
  when_idle: true
info: scroll
type: 'custom:mini-media-player'
```

and one
```yaml
entity_id: media_player.plex_whatever
artwork: cover
group: true
hide:
  power_state: false
  progress: false
  runtime: false
  volume: false
idle_view:
  when_idle: true
info: scroll
type: 'custom:mini-media-player'
```

Those are two unique entries, since they have different `icon:` settings.

I suggest trying the `not:` filter in the second `include` item.

```yaml
not:
  entity_id: media_player.plex_*
```
