### ISSUE TITLE
Feature request: Title

### ISSUE THREAD

**Issue by luigixx73** [thomasloven/lovelace-auto-entities#380]
Posibility of showing a title for empty and non empty as header, for instance:
"Active elements" or  "Disabled elements".
I can do the second using "else" card but not the first when there is any included element.

**Comment by luigixx73** [comment]
I've solved the issue using a grid card with "title" for the "included" entities and "else" with a markdown when it is empty.

**Comment by ildar170975** [comment]
The `auto-entities` card does this:
-- generates a list of items (could be just `entity_id`s or complex dicts)
-- passes this list into a user-defined "destination" card
nothing else. 
**Other customizations like "add a header" are to be defined on that "destination" card's level.**
Some "header" is a part of cards which can have "headers" (like "Entities card"), many cards (which can be used as a "destination") do not have headers.

**Comment by AlexKalopsia** [comment]
```
- type: custom:stack-in-card
        cards:
        - type: picture
          image: /local/pic_entrance.png
        - type: custom:auto-entities
          title: Office
          show_header_toggle: false
          card: 
            type: grid
            square: false
          card_param: cards
          filter:
            include:
              - domain: scene
                entity_id: scene.office_*
                options:
                  type: button
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: this.entity_id
```

<img width="510" height="354" alt="Image" src="https://github.com/user-attachments/assets/f31da8e4-0bc6-4868-a527-fae9259999b4" />

The title above my buttons doesn't appear. WHat would you say it's the best way to address this?
