### ISSUE TITLE
How can I list all areas?

### ISSUE THREAD

**Issue by elblogbruno** [thomasloven/lovelace-auto-entities#382]
Hello everyone. I am trying to list all available areas on my UI, hovewer I have not been very lucky.

I tried using a template:

 ```
   - type: "custom:auto-entities"
            card:
              type: "grid"
              title: All areas
              columns: 2
              square: false
            card_param: "cards"
            filter:
              template: "{{ areas() }}"
              options:
                type: area
```

Hovewer this gives me the following error:

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/10481058/cee6a05c-5959-4993-a2e4-d922de480fa7)

Am I missing something? is this a bug or something?
Thanks a lot!

**Comment by danielbrunt57** [comment]
It appears to be a bug since the [example ](https://github.com/thomasloven/lovelace-auto-entities#examples) code doesn't even work.

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/49846893/0f5909a4-9237-464a-886b-6569198e617f)

This example following that on also is not working for me:

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/49846893/492c0e3b-6d0e-4bc7-b736-dc9b1f56471f)

**Comment by ildar170975** [comment]
1. This is neither a bug nor a FR. Suggest to ask similar questions in a dedicated auto-entities Community thread.

2.  This is wrong:
```
           filter:
             template: "{{ areas() }}"
             options:
               type: area
```
You cannot use the "template" & "options" together.
All your code to create a list of area cards should be inside the "template" option.
