### ISSUE TITLE
Use custom:template-entity-row possible?

### ISSUE THREAD

**Issue by saschabrockel** [thomasloven/lovelace-auto-entities#383]
Is it possible to manipulate the value of all entities with your card `custom:template-entity-row`? I love this card for fuel prices but I would like to cut off one digit and it would be possible with your other card but I guess that is not possible.

**Comment by ildar170975** [comment]
> cut off one digit

```
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - entity_id: sensor.xiaomi*humidity
          options:
            type: custom:template-entity-row
            state: >-
              {{ states(config.entity) | float(default=0) | round(0) }}
```

Suggest to ask similar questions in the [dedicated Community thread](https://community.home-assistant.io/t/template-entity-row-put-templates-in-an-entities-row/160167) and leave Github for reporting bugs & proposing FRs.

**Comment by TylonHH** [comment]
and without entity-row?
this is what I tried

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - attributes:
        device_class: humidity
      options:
        state: >
          {{ states(config.entity) | float(default=0) | round(0) }} %
exclude:
  - state: unavailable
  - area: Außenbereich
  - area: kontrollraum
sort:
  method: state
  attribute: humidity
  numeric: true
  reverse: true
show_empty: true
```
