### ISSUE TITLE
Error when using with "Hue like card" 

### ISSUE THREAD

**Issue by twanjaarsveld** [thomasloven/lovelace-auto-entities#395]
When using auto entities with the cars "hue like"  in a grid it won't work 

Here is the code I used 
`square: false
type: grid
cards:
  - type: custom:auto-entities
    filter:
      include:
        - domain: light
          area: 829d23948f6844f0a15e2a14e4318e23
      exclude:
        - state: unavailable
    card:
      type: custom:hue-like-light-card
      title: Woonkamer
      icon: mdi:sofa
      slider: mushroom
      theme: synthwave
      style: |
        .brightness-slider {
          --mush-control-height: 20px;
          --slider-color: white;
        }`

**Comment by ildar170975** [comment]
Code is unformatted. Impossible to analyze.

**Comment by Gh61** [comment]
```yaml
square: false
type: grid
columns: 1
cards:
  - type: custom:auto-entities
    filter:
      include:
        - domain: light
          area: 829d23948f6844f0a15e2a14e4318e23
      exclude:
        - state: unavailable
    card:
      type: custom:hue-like-light-card
      title: Woonkamer
      icon: mdi:sofa
      slider: mushroom
      theme: synthwave
      style: |
        .brightness-slider {
          --mush-control-height: 20px;
          --slider-color: white;
        }
```

See https://github.com/Gh61/lovelace-hue-like-light-card/issues/103
