### ISSUE TITLE
How to install if used in yaml-dashboard with docker?

### ISSUE THREAD

**Issue by Cangoo** [thomasloven/lovelace-auto-entities#396]
Hello,

I'm using HA in a docker-container with a yaml-lovelace-dashboard. Unfortunately, the installation-instructions on this page don't show exactly how to do the installation in my situation.

I git cloned the project to /config/www/plugins/lovelace-auto-entities/. I added to my configuration.yaml:

```
lovelace:
  mode: yaml
  resources:
    - url: /config/www/plugins/lovelace-auto-entities/auto-entities.js
      type: mode
```

and to my ui-lovelace.yaml:

```
 - type: custom:auto-entities
        card:
          type: entities
          title: All sensors with batteries!
          sort_by_level: asc
        filter:
          include:
            - entity_id: sensor.*.battery*
              
```

but I'm only getting a card which says: Custom element doesn't exist: auto-entities.

I tried different urls:
```
- url: /www/plugins/lovelace-auto-entities/auto-entities.js
- url: /plugins/lovelace-auto-entities/auto-entities.js

```
but none is working. What is the correct way to do it?
