### ISSUE TITLE
include: - area: "Tariffed Utility Meters" is yielding more entities than what are in that area

### ISSUE THREAD

**Issue by danielbrunt57** [thomasloven/lovelace-auto-entities#398]
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - area: "Tariffed Utility Meters"
```
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/49846893/e6fcfc41-1249-49f7-a0d8-1425066cb9e0)

My template works though:
```
{{ 
  expand(states) 
  |selectattr('entity_id', 'in', area_entities('Tariffed Utility Meters')) 
  |map(attribute='entity_id')
  |list
}}
```
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/49846893/ea69fad0-10b5-41f0-81d7-d22371098a67)
