### ISSUE TITLE
state: "< 10" doesn't work

### ISSUE THREAD

**Issue by h4nc** [thomasloven/lovelace-auto-entities#4]
I have some battery state entities. So this entites have the battery value as state. They also have this value as an attribute (json_attributes_topic, zigbee2mqtt autodiscover devices)

This works fine:

```
        filter:
          include:
            - entity_id: "sensor.zigbee_*_battery"
              attributes:
                battery: "< 20"  
```

But why can't I use the state instead of attributes? Like this?

```
        filter:
          include:
            - entity_id: "sensor.zigbee_*_battery"
              state: "< 20"  
```

What am I doing wrong? I also testet 

```
        filter:
          include:
            - entity_id: "sensor.zigbee_*_battery"
            - state: "< 20"  
```

without luck.
