### ISSUE TITLE
 show_header_toggle: false doesn't work

### ISSUE THREAD

**Issue by h4nc** [thomasloven/lovelace-auto-entities#40]
`show_header_toggle: false` doesn't work. The header toggle stills shows. I refreshed the page and restarted ha. 

```
      - type: custom:auto-entities
        show_empty: false      
        show_header_toggle: false
        card:
          type: entities
          title: 'scripts'
        filter:
          include:
            - entity_id: "script.*"
```
