### ISSUE TITLE
Showing automations triggered in the last 30 minutes

### ISSUE THREAD

**Issue by moritzmaier84** [thomasloven/lovelace-auto-entities#401]
Hi,
I'm dying in figuring out how to do this.
This is my try - does not show any.
Is there a solution for this?
Thank you!

- type: custom:auto-entities
  card:
    type: entities
    title: Zuletzt aktive Automationen
    show_header_toggle: false
    state_color: false
  filter:
    template: |
      {% for entity in states.automation %}
        {% if (as_timestamp(now()) - as_timestamp(entity.last_triggered)) < 1800 %}
          - entity: {{ entity.entity_id }}
      {% endfor %}

**Comment by mag1024** [comment]
```
type: custom:auto-entities
card:
  type: entities
filter:
  template: >-
    {{ states.automation|rejectattr('attributes.last_triggered', 'undefined')|selectattr('attributes.last_triggered', 'gt', now()-timedelta(minutes=30))|map(attribute='entity_id')|list }}
```
