### ISSUE TITLE
Help needed - Auto-Entites and Grid_layout

### ISSUE THREAD

**Issue by idominiki** [thomasloven/lovelace-auto-entities#403]
My Home Assistant version: 2023.12.2

I want to use Auto-Entities with UI-Lovelace-Minimalist.

I've set up the following room yaml for UI Minimalist:
``` ---
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  #default
  grid-gap: 1px 1px
  grid-template-columns: 25% 25% 25% 25%
  grid-template-rows: auto
  grid-template-areas: |
    "  bar    bar    bar    bar    "
    "  chips  chips  chips  chips  "
    "  t1     t1     t1     t1     "
    "  l1     l2     l3     l4     "
    "  l5     l6     .      .      "
``` 

l1 ... l6 is used for light cards. I want to replace this static configuration with auto-entities. 

I changed configuration to:
``` ---
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  #default
  grid-gap: 1px 1px
  grid-template-columns: 25% 25% 25% 25%
  grid-template-rows: auto
  grid-template-areas: |
    "  bar    bar    bar    bar    "
    "  chips  chips  chips  chips  "
    "  t1     t1     t1     t1     "
    "  l1     l1     l1     l1     "
    "  t2     t2     t2     t2     "
``` 

And configured auto-entities to:
```
  - type: custom:button-card
    template: title
    name: Wohnzimmer
    label: "Beleuchtung"
    view_layout:
      grid-area: t1

  - type: "custom:auto-entities"
    card:
      type: "grid"
      #columns: 2
      square: false
    card_param: "cards"
    sort:
      count: 4
    filter:
      include:
        - domain: "light"
          area: Wohnzimmer
          options:
            type: "custom:button-card"
            template: "card_light"
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_popup: true
    view_layout:
      grid-area: l1
``` 

On desktop it looks good but not on a mobile.
![Bildschirmfoto 2023-12-14 um 16 31 15](https://github.com/thomasloven/lovelace-auto-entities/assets/62521486/81c6fba6-d429-47b3-975e-0e6d2b8572bd)
![Bildschirmfoto 2023-12-14 um 16 31 53](https://github.com/thomasloven/lovelace-auto-entities/assets/62521486/459ec13d-4a7a-4c80-9724-10fa8fe5b8b1)

How can I adjust this behavior, that columns are used dynamically?

Wished behavior:
4 columns on desktop, 3 on tablet, 2 on mobile.
Thanks, Dominik!

**Comment by idominiki** [comment]
I found the solution using custom grid-layout as type:

```
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  #default
  grid-gap: 1px 1px
  grid-template-columns: 25% 25% 25% 25%
  grid-template-rows: auto
  mediaquery:
    #phone
    "(max-width: 799px)":
      grid-gap: 1px 1px
      grid-template-columns: 50% 50%
    #portrait
    "(max-width: 1200px)":
      grid-gap: 1px 1px
      grid-template-columns: 33.3% 33.3% 33.3%
```

**Comment by idominiki** [comment]
I found the solution using custom grid-layout as type:

```
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  #default
  grid-gap: 1px 1px
  grid-template-columns: 25% 25% 25% 25%
  grid-template-rows: auto
  mediaquery:
    #phone
    "(max-width: 799px)":
      grid-gap: 1px 1px
      grid-template-columns: 50% 50%
    #portrait
    "(max-width: 1200px)":
      grid-gap: 1px 1px
      grid-template-columns: 33.3% 33.3% 33.3%
```
