### ISSUE TITLE
"else" card not displayed when using a vertical-stack

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#404]
Consider an `auto-entities` card placed into `vertical-stack`:
```
title: test-2
path: test-2
cards:
  - type: vertical-stack
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - domain: cover
              state: open
        else:
          type: entities
          entities:
            - entity: sun.sun

      - type: entity
        entity: sun.sun
```

What I expect to see:
a) the "main" card is displayed:

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/47784c93-20ef-4329-a112-ba2fde66a129)

b) OR the "else" card is displayed:

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/60731319-5897-46cb-96a3-afe45661329d)

What I see in instead of "b" case in fact:

![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/0073e2df-dccd-470d-8430-624bc6444efc)

To get a desired result I need NOT to use a `vertical-stack` card:
```
title: test-2
path: test-2
cards:
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - domain: cover
          state: open
    else:
      type: entities
      entities:
        - entity: sun.sun

  - type: entity
    entity: sun.sun
```

**Comment by R1GFY** [comment]
I get similar results also:
```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      show_header_toggle: false
      type: entities
    filter:
      include:
        - entity_id: binary_sensor.fridge_plug
          options:
            type: custom:template-entity-row
            color: >-
              {% if is_state('this.entity_id','on') %} green {% else %} red {%
              endif %}
        - entity_id: binary_sensor.freezer_plug
          options:
            type: custom:template-entity-row
            color: >-
              {% if is_state('this.entity_id','on') %} green {% else %} red {%
              endif %}
      exclude:
        - state: 'on'
    unique: true
    else:
      type: entities
      entities:
        - entity: binary_sensor.always_true
          type: custom:template-entity-row
          name: All Plugs
          icon: mdi:power-plug
          color: green
```

**Comment by srrt33** [comment]
This is also an issue when an auto-entities card is in a stack-in card. Editing (or simply opening the edit dialog and saving) will make the "else" option reappear, but any time the screen is refreshed the issue persists.

**Comment by e3drigs** [comment]
Same behaviour with auto entities inside a grid. Oddly, it displays correctly in the edit UI, just not in the normal view.

**Comment by screamer83** [comment]
I get similar results also:
  ```
type: custom:auto-entities
  card:
      type: entities
      title: "Датчики протечки"
      #state_color: true
      card_mod:
        style: |
          ha-card {
            color: red;
            font-size: 12px;
            animation: blinking 1s linear alternate infinite;
          }      
          @keyframes blinking {
            0% {opacity: 0;}
            100% {opacity: 1;}
          }
    filter:
      include:
        - domain: binary_sensor
          state: "on"
          attributes:
            device_class: "moisture"
          options:
            secondary_info: last-changed
      exclude:
        - entity_id: binary_sensor.datchiki_protechki
    else:
      type: markdown
      content: |
        <ha-alert alert-type="success">Датчики протечки в норме.</ha-alert>
```
How it can be fixed?

**Comment by PixNyb** [comment]
It happens on and off for me, the else card doesn't show up when state changes but after a reload of the browser it shows up about 80% of the time. This is my config:
```yml
type: vertical-stack
cards:
  ...
  - type: custom:auto-entities
    filter:
      include:
        - name: Plex *
          domain: media_player
          options:
            type: custom:template-entity-row
            name: >-
              {% set device = 'this.entity_id' %} {% set name =
              state_attr(device, 'friendly_name') | regex_findall('\((.*?)\)') |
              regex_replace('Plex.* - ', '') %} {{ name }}
            state: >-
              {% set device = 'this.entity_id' %} {% set type =
              state_attr(device, 'media_content_type') %} {% set state =
              states(device) %} {% if type == 'music' %}
                {% set type_nice = 'music' %}
              {% elif type == 'tvshow' %}
                {% set type_nice = 'a show' %}
              {% elif type == 'movie' %}
                {% set type_nice = 'a movie' %}
              {% endif %} {{ state[0]|upper }}{{ state[1:] }}
            secondary: >-
              {% set device = 'this.entity_id' %} {% set type =
              state_attr(device, 'media_content_type') %} {% set library =
              state_attr(device, 'media_library_title') %} {% set title =
              state_attr(device, 'media_title') %} {% if type == 'music' %}
                {% set series = state_attr(device, 'media_album_artist') %}
              {% else %}
                {% set series = state_attr(device, 'media_series_title') %}
              {% endif %} {{ title }} {% if series %}
                - {{ series }}
              {% endif %}
      exclude:
        - state: unavailable
        - state: idle
    sort:
      reverse: true
      method: state
      ignore_case: true
      ip: false
    card:
      type: entities
    else:
      type: entities
      entities:
        - type: custom:template-entity-row
          name: No active players...
          icon: mdi:cast-off
```
