### ISSUE TITLE
allow a way to configure entity properties in card configuration like secondary_info

### ISSUE THREAD

**Issue by mmerickel** [thomasloven/lovelace-auto-entities#408]
```yaml
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: All Lights
filter:
  include:
    - domain: light
  exclude:
    - hidden_by: '*'
sort:
  method: friendly_name
```

Looking at something like this - there isn't a way to define the `secondary_info: last-changed` key in the rendered entities of the card.

To be clear the `type: entities` card supports the following, and there does not seem to be a way from the auto-entities wrapper to define the extra attributes on each rendered entity:

```yaml
type: entities
entities:
  - entity: binary_sensor.dark_outside
    secondary_info: last-changed
  - entity: binary_sensor.front_door_contact
    secondary_info: last-changed
  - entity: binary_sensor.patio_sliding_door_contact
    secondary_info: last-changed
  - entity: binary_sensor.kitchen_garage_door_contact
    secondary_info: last-changed
  - entity: cover.garage_door
    secondary_info: last-changed
state_color: true
```

I'd like to define a jinja template for the rendered entity if possible. This would allow configuring things like tap actions on other card types as well. Imagine an `entity_template` attribute on the auto-entities card config:

```yaml
entity_template: |
  entity: {{ entity.id }}
  secondary_info: last-changed
```
