### ISSUE TITLE
[duplicate of #347] Sorting by "area" causes auto-entities to not show any results. Sorting by anything else works.

### ISSUE THREAD

**Issue by ncd7** [thomasloven/lovelace-auto-entities#409]
The following causes the card to be empty.
Changing the method to say "entity_id" makes it work again.
All the matching entities have their areas set (just in case that's a special requirement).
Let me know if I'm doing something stupid.

```
        - card:
            type: custom:auto-entities
            card:
              type: entities
            filter:
              include:
                - domain: input_boolean
                - domain: switch
            sort:
              method: area
              reverse: true
              numeric: false
            show_empty: false
          attributes:
            icon: mdi:toggle-switch-outline

```
