### ISSUE TITLE
Options: secondary_info doesn't work with template filter

### ISSUE THREAD

**Issue by Arman-GeDon** [thomasloven/lovelace-auto-entities#411]
Version: 1.12.1
options: secondary_info doesn't work with template filter but works with include filter
Example:

```
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: My Title
  state_color: true
filter:
  template: "{{ 'input_number.htpc_timer' }}"
  options:
    secondary_info: last-changed
```

**Comment by ildar170975** [comment]
`options` cannot work with `template`. Not a bug. Expected behaviour.

**Comment by tjorim** [comment]
Does not mean it can't or shouldn't. I think this would be a nice feature to have.
E.g.
```yaml
...
filter:
  include:
    - options:
        name: '{{state_attr(this.entity_id, ''friendly_name'')[5:]}}'
        type: custom:multiple-entity-row
        ...
        tap_action:
          action: url
          url_path: '{{state_attr(this.entity_id, ''item_url'')}}'
        ...
```
