### ISSUE TITLE
Unable to expand card size to both full width and height

### ISSUE THREAD

**Issue by sdschramm** [thomasloven/lovelace-auto-entities#412]
Hello, I created an auto-entities card to display a rolling history of events in my home but using the filtering feature to remove things I don't care to see. It works great, but has one small issue. No matter what type of view or layout I set, the card can be expanded to the full width of the window but will not expand to the full height. I have also tried "Layout-card" and "Card Mod" and was unable to find a working combination to get the card to expand to all viewable space. I don't have this issue with other types of cards. Below is the code I am using for the card and a screenshot of the result. Is there something I am doing wrong or is this a known issue?

```
type: custom:auto-entities
card:
  type: logbook
  hours_to_show: 2
filter:
  include:
    - {}
  exclude:
    (truncated)
```
![Screenshot 2024-01-08 at 12 28 37 AM](https://github.com/thomasloven/lovelace-auto-entities/assets/38740977/aecb283a-9866-4917-9d12-3a73009b5ed2)

![Screenshot 2024-01-08 at 12 19 17 AM](https://github.com/thomasloven/lovelace-auto-entities/assets/38740977/6178854d-0a81-4629-b9b0-d906405107c6)
