### ISSUE TITLE
Timeout waiting for strategy element ll-strategy-dashboard-auto-entities to be registered

### ISSUE THREAD

**Issue by Bluscream** [thomasloven/lovelace-auto-entities#416]
```
Error loading the dashboard strategy:

Error: Timeout waiting for strategy element ll-strategy-dashboard-auto-entities to be registered
```

```yaml
type: custom:auto-entities
show_empty: false
card:
  type: original-states
filter:
  include:
    - domain: light
  exclude:
    - state: 'off'
    - state: unavailable
    - hidden_by: user
```
