### ISSUE TITLE
Possible to use with multiple-entity-row?

### ISSUE THREAD

**Issue by Milinator** [thomasloven/lovelace-auto-entities#418]
Hey there,

I've been trying to sort the following entity list (originally using multiple-entity-row):
`type: entities
entities:
  - entity: sensor.ics_1
    style: |
      :host {
        color: grey;
      }      
    icon: mdi:delete-empty
    show_state: false
    type: custom:multiple-entity-row
    name: Schwarze Tonne
    secondary_info: last-changed
    entities:
      - type: attribute
        entity: sensor.ics_1
        attribute: remaining
        name: Abholung in
        unit: Tage(n)
      - type: entity
        name: Datum
        entity: sensor.ics_1
  - entity: sensor.ics_2
    style: |
      :host {
        color: grey;
      }      
    icon: mdi:paper-roll
    show_state: false
    type: custom:multiple-entity-row
    name: Papiermüll
    secondary_info: last-changed
    entities:
      - type: attribute
        entity: sensor.ics_2
        attribute: remaining
        name: Abholung in
        unit: Tage(n)
      - type: entity
        name: Datum
        entity: sensor.ics_2
  - entity: sensor.ics_3
    style: |
      :host {
        color: grey;
      }      
    icon: mdi:delete-variant
    show_state: false
    type: custom:multiple-entity-row
    name: Gelber Sack
    secondary_info: last-changed
    entities:
      - type: attribute
        entity: sensor.ics_3
        attribute: remaining
        name: Abholung in
        unit: Tage(n)
      - type: entity
        name: Datum
        entity: sensor.ics_3
  - entity: sensor.ics_4
    style: |
      :host {
        color: grey;
      }      
    icon: mdi:bottle-soda
    show_state: false
    type: custom:multiple-entity-row
    name: Altglas
    secondary_info: last-changed
    entities:
      - type: attribute
        entity: sensor.ics_4
        attribute: remaining
        name: Abholung in
        unit: Tage(n)
      - type: entity
        name: Datum
        entity: sensor.ics_4
  - entity: sensor.ics_5
    style: |
      :host {
        color: grey;
      }      
    icon: mdi:food-apple
    show_state: false
    type: custom:multiple-entity-row
    name: Biomüll
    secondary_info: last-changed
    entities:
      - type: attribute
        entity: sensor.ics_5
        attribute: remaining
        name: Abholung in
        unit: Tage(n)
      - type: entity
        name: Datum
        entity: sensor.ics_5
`

But I'm not sure if it even is possible? Could someone help me out?
I want to sort it by the attribute "remaining", but I just can't get it to work.
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/67156976/6da08d85-d2f4-4aa4-8a6a-bb0e20536781)

Best regards,

Milan

**Comment by austin20202020** [comment]
i too have been trying to get this work

**Comment by jb1228** [comment]
There might be another way to do this, but I have been using the template filter to return a list of objects instead of just a list of entity IDs. 

Here is an example: 

``` YAML
type: custom:auto-entities
card:
  type: entities
filter:
  template: |
    {% set ns = namespace(list=[]) %}

    {% for light in states.light %}
      {% if light.state == "on" %}
      
        {% set ns.list = ns.list + 
          [
            {
              'type': 'custom:multiple-entity-row',
              'entity': light.entity_id,
              'name': light.attributes.friendly_name,
              'state_color': true,
              'show_state': false,
              'entities': [
                {
                  'entity': light.entity_id,
                  'name': 'Lights',
                  'toggle': true
                },
                {
                  'entity': light.entity_id,
                  'attribute': 'brightness',
                  'name': 'Brightness'
                }
              ]
            }
          ] 
        %}
        
      {% endif %}
    {% endfor %}

    {{ ns.list }}
```
