### ISSUE TITLE
How to use with grouping cards like grid/stacks

### ISSUE THREAD

**Issue by Bluscream** [thomasloven/lovelace-auto-entities#419]
I want to have a grid of all camera.* entities, how would i do that?

```yaml
type: custom:auto-entities
filter:
  include:
    - domain: camera
card:
  type: grid
  cards:
     - type: picture-glance
       camera_view: auto
show_empty: true
card_param: cards
```
