### ISSUE TITLE
Filter uses or instead of and

### ISSUE THREAD

**Issue by AnderssonPeter** [thomasloven/lovelace-auto-entities#421]
According to the documentation if I specify multiple filters the card should use **and** between them so

filter:
  include:
    - domain: plant
    - area: Stuga

And

filter:
  include:
    - and:
      - domain: plant
      - area: Stuga

Should be the same thing? But the first code uses or instead of and?

Is the documentation wrong or am I doing something wrong?

**Comment by outdooracorn** [comment]
The options inside a filter use AND, multiple different filters use OR. There is a good example of this in the [repeating options](https://github.com/thomasloven/lovelace-auto-entities?tab=readme-ov-file#repeating-options) section of the docs.

This includes entities where the domain is plant OR area is Stuga:
```yaml
filter:
  include:
    - domain: plant
    - area: Stuga
```

This includes entities where the domain is plant AND area is Stuga:
```yaml
filter:
  include:
    - domain: plant
      area: Stuga
```

**Comment by erkr** [comment]
@outdooracorn or others :-)
I tried to include powercalc entities in two areas like this:
```
filter:
  include:
    - integration: powercalc
      area: 
        - cellar
        - attic
```
Based on the example above, I expect to have the areas evaluated as an OR, but is seems to be an AND relation?!
The next example works, selecting powercalc entities in area cellar or attic, but is a little silly:
```
filter:
  include:
    - integration: powercalc
      area: cellar
    - integration: powercalc
      area: attic
```

**Comment by outdooracorn** [comment]
I don't think you can provide a list to `area`, but you might be able use the `or:` special option (untested): 

```
filter:
  include:
    - integration: powercalc
      or:
        - area: cellar
        - area: attic 
```
