### ISSUE TITLE
Area filter not working as intended?

### ISSUE THREAD

**Issue by AnderssonPeter** [thomasloven/lovelace-auto-entities#422]
Hi if I run the following template `{{ area_name('plant.plant_11') }}` it outputs `Stuga` but it's not included in the following

```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
  state_color: false
  title: Växter
filter:
  include:
      - area: Stuga
```
