### ISSUE TITLE
can not use sensor or gauge card

### ISSUE THREAD

**Issue by jurgenweber** [thomasloven/lovelace-auto-entities#427]
if I try with the sensor card::

```
        - type: custom:auto-entities
          card:
            type: sensor
          filter:
            include:
              - domain: sensor
                entity_id: "sensor.days_to_*"
                state: "< 30"
 ```
 
 I get 
 
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/3013734/ef5470b2-1d04-4118-8120-67cc35229efc)

if I just change the type to gauge:

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/3013734/3b9e2c22-b9b8-46ba-b67e-1e3eedb5527d)

What am I doing wrong?
