### ISSUE TITLE
Feature Request: Filter by floor

### ISSUE THREAD

**Issue by SLaks** [thomasloven/lovelace-auto-entities#434]
I'd love to have an auto-entities card that shows all entities in all areas belonging to a specific floor in HA 2024.4+

**Comment by pos-ei-don** [comment]
yes pleeeeaaasssee!!!

**Comment by mal2856** [comment]
Did anyone figure out a way to do this using the Jinja template filter workaround?

**Comment by NickChristensen** [comment]
You could use [`floors()`](https://www.home-assistant.io/docs/configuration/templating/#floors) and [`areas()`](https://www.home-assistant.io/docs/configuration/templating/#areas) to get entites by that heirarchy:

```
{% for floor in floors() %}
  Floor: {{floor}}
  {% for area in floor_areas(floor) %}
    Area: {{area}}
    {% for entity in area_entities(area) %}
      {{entity}}
    {% endfor %}
  {% endfor %}
{% endfor %}
```

You could adapt this to the filter/template structure, and you would have to output JSON for your card configuration similar to https://github.com/thomasloven/lovelace-auto-entities/issues/382#issuecomment-1824799660

**Comment by Bsector** [comment]
Yes, I also need this function!!!

**Comment by petervk** [comment]
Would love to have floors as a filter!

**Comment by Rediwed** [comment]
Filtering by floor would be great!

**Comment by FlexxFR** [comment]
Oh, yes. Please add a floor function

**Comment by wtstreetglow** [comment]
I would also like this addition.

**Comment by MilesTEG1** [comment]
I also would like to have this feature 😃

**Comment by wemyster** [comment]
I was after all the **Lights** located on the **Upstairs** floor that are currently **on**. 

So I used the auto-entities card's `template` filter option to select entities by floor: `floor_entities('upstairs')`  The magic here is using the `intersect` function to return only the common entities that are known as lights: `label_entities('Light')`

You can then filter your entities further by state to select the ones that you actually want, such as the light being on or off.

Enjoy:

```
type: custom:auto-entities
card:
  type: entities
  title: Lights On Now
  show_header_toggle: false
  state_color: true
filter:
  template: |-
    {{ intersect( label_entities('Light'), floor_entities('upstairs') ) 
       | select('is_state', 'on') | list }}
sort:
  method: friendly_name
```
