### ISSUE TITLE
Filtering entities by label doesn't work

### ISSUE THREAD

**Issue by adamlc** [thomasloven/lovelace-auto-entities#435]
I'm testing the new labels features and can't get auto entities to display anything for light entities, nothing is shown.

It does however seem to work for automation with labels!

Not tried any other entity types however.

**Comment by Revilo91** [comment]
Same here

**Comment by filippo196302** [comment]
Same here

**Comment by Earthweb-EWS** [comment]
I have the sane problem. No option are shown in UI dropdown and in code-editor it doesn't work also.

The code I using is this:
  filter:
    include:
      - label: Test

**Comment by RuneNyhuus** [comment]
Same problem here... Not working with Labels

**Comment by Mariusthvdb** [comment]
also, add a problem config ;-)

```
    - type: custom:auto-entities
      card:
        type: entities
        title: Test label auto entities
      filter:
        include:
          - label: intercom speler
   ```

remains empty, 

<img width="336" alt="Scherm­afbeelding 2024-04-05 om 15 54 48" src="https://github.com/thomasloven/lovelace-auto-entities/assets/33354141/e2c512ef-7eeb-4772-892d-3291f8997bfe">


even though:

<img width="452" alt="Scherm­afbeelding 2024-04-05 om 15 09 04" src="https://github.com/thomasloven/lovelace-auto-entities/assets/33354141/7eeafda4-c579-431f-a133-1fafc7fdb57e">
