### ISSUE TITLE
filter on include: label causes lag and grinds the view

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#438]
HA 2024.4.2
Auto-entities 1.13.0

Glad the new labels are implemented in the auto-entities config options (thanks!). However, something is causing a huge lag, so much so, it practically stops the view from responding.
Ive moved the testing configs for this from UI dashboards to yaml dashboards, as the editor simply wont open.

Als there seems to be a memory increase (see far right for the sudden spike on editing an auto-entities card with the option label filter)

<img width="1337" alt="Scherm­afbeelding 2024-04-09 om 10 35 45" src="https://github.com/thomasloven/lovelace-auto-entities/assets/33354141/170a15da-218b-46e7-901a-cedb3ec162fc">

though that is of lesser importance, and not 100% reproducible 

The Frontend Lag is, I am afraid.

using a template filter is fine:

```
card:
  type: entities
filter:
  template: |
    {{label_entities('Theater')}}
```

but using the label include makes the card drag the view down:

```
type: custom:auto-entities
card:
  type: entities
  title: Auto label
filter:
  include:
    - label: theater
```
or
```
type: custom:auto-entities
card:
  type: entities
  title: test filter label auto entities
filter:
  include:
    - label: intercom_speler
  exclude:
    - state: unavailable
```

they all show the correct entities, so the label include does work in itself.

That's why I opened this separate issue from another open issue
