### ISSUE TITLE
Icon Color in Template

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#439]
I want to be able to set the icon color dynamically based on the state of a sensor. The end goal is to be able to have sensors with high battery percentage be green, 50% be yellow, and less than 20% be red. Or whatever percentages I want to put on it. When I try to code below, I get no colors and the icon circle just disappears. 

```
type: custom:auto-entities
card:
  square: false
  columns: 2
  type: grid
card_param: cards
filter:
  include:
    - attributes:
        device_class: battery
      domain: sensor
      sort:
        method: state
        numeric: true
      options:
        type: custom:mushroom-entity-card
        icon_color: >-
          {% if states('sun.sun') == 'above_horizon' %}
            green
          {% else %}
            red
          {% endif %}
        entities:
          - this.entity_id
  exclude:
    - entity_id: sensor.*iphone_battery*
    - entity_id: sensor.*low_battery_level
```
