### ISSUE TITLE
multiple-entity-row name templating

### ISSUE THREAD

**Issue by arifroni** [thomasloven/lovelace-auto-entities#440]
I want to customize the friendly name. But when I use templaing on the name, it doesn't work? is it possible?

```
type: custom:auto-entities
card:
  type: entities
  title: Heater Reading
filter:
  include:
    - entity_id: sensor.mbus*
      options:
        type: custom:multiple-entity-row
        show_state: false
        secondary_info: last-changed
        entities:
          - attribute: previous_hca
            name: 2023
            unit: m³
          - attribute: current_hca
            name: 2024
            unit: m³
  exclude: []
sort:
  method: state
  ignore_case: false
  numeric: true
  reverse: true
```
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/59896374/53f35067-8246-4051-8e49-db1ae9f20858)

as you can see when I just try to use any templating, it fails. I want to remove 'mbus_' and '_heater'  from the friendly name and capitalize the rest.

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/59896374/940ded4a-2961-4755-a80a-b68b5e0a834d)
