### ISSUE TITLE
Map card: may show a minimal zoom when placed inside auto-entities

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#441]
Consider the code:
```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: map
      auto_fit: true
      fit_zones: true
    entities:
      - zone.home
    filter:
      include:
        - entity_id: person.ildar
```
Use-case: show `device_tracker` or `person` entities AND some zone.
Here I chose one particular `person` entity & home zone.

Select a dashboard in STORAGE mode, add a new card with this code.
How it is displayed:
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/9f0b2bdc-94b2-494b-801c-e0c1a16bf446)

Zoom is minimal.
Pressing F5 does not help.

Save the dashboard (exit "edit mode") - still zoom is minimal:
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/23d63804-9720-453d-8b5e-ea7cda591fab)
Pressing F5 does not help.

Go back to "edit mode" - the card is shown normal (zoom is OK).
Press F5 - again zoom is minimal.

In these cases I do not observe the issue:
1. The card is shown in Editor.
2. Same card is placed on a dashboard in YAML mode.
3. No `vertical-stack` is used:
```
    type: custom:auto-entities
    card:
      type: map
      auto_fit: true
      fit_zones: true
    entities:
      - zone.home
    filter:
      include:
        - entity_id: person.ildar
```
4. `auto-entities` is not used:
```
type: vertical-stack
cards:
  - type: map
    auto_fit: true
    fit_zones: true
    entities:
      - zone.home
      - person.ildar
```
5. Those `auto_fit` & `fit_zones` options have different values or omitted (i.e. using default `false` values).
