### ISSUE TITLE
[FR] option to override `entities:` as target

### ISSUE THREAD

**Issue by erkr** [thomasloven/lovelace-auto-entities#447]
It would be great it can override the target 'entities:'
E.g to generate entity lists for paper-button-row

**Comment by ildar170975** [comment]
> paper-button-row

What is this?

**Comment by ildar170975** [comment]
Have you tried defining `card_param`?

**Comment by erkr** [comment]
> Have you tried defining `card_param`?

Now I don't know what that is 😉

**Comment by ildar170975** [comment]
![изображение](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/ace414a7-1280-4bb7-9997-e3ad121818d6)

**Comment by erkr** [comment]
Yes that works great. Thanks for the hint. Will close the issue.

For those looking for this as well. I managed to populate a 'History-explorer' card.
A little more complex as the entities are declared in sub keys of graph types. 

This is a simple history-explorer card:
``` 
type: custom:history-explorer-card
graphs:
  - type: line
    entities:
      - entity: sensor.temperatures_bedroom
      - entity: sensor.temperatures_living
 ...
``` 

This is the same card, populated with auto-entities:
``` 
type: custom:auto-entities
card_param: graphs
filter:
  template: >
    {%- set entities = state_attr('sensor.temperatures_binnen','entity_id') or
    [] -%}
    {%- set ns = namespace(lines=[]) -%}
    {%- for entity in entities -%}
      {%- set ns.lines = ns.lines + [{'entity': entity }] -%}
    {%- endfor -%}
    {%- set graph=[
             {'type': 'line',
              'entities': ns.lines}, 
              ]  
     -%}
    {{ graph }}      
card:
  type: custom:history-explorer-card
```
