### ISSUE TITLE
this.entity_id not working, used to with monster card

### ISSUE THREAD

**Issue by mdegat01** [thomasloven/lovelace-auto-entities#45]
I noticed monster card was deprecated in favor of the auto-entities card so I began migrating over.  However it seems to have broken a couple of my cards around task management.  For example here is one that used to work when the type was 'custom:monster-card':
```
- card:
    columns: 2
    show_state: true
    type: glance
   filter:
    include:
    - attributes:
        repeat: '> 0'
       entity_id: input_datetime.recurring_task_*
       options:
        format: relative
        secondary_info: last_updated
        tap_action:
         action: call-service
         service: script.set_datetime_to_now
         service_data:
          id: this.entity_id
   type: 'custom:monster-card'
```

When i change the type of this one to 'custom:auto-entities' the card itself renders the same but the tap action does not work.  My script is no longer passed in the ID of what was clicked, instead of it is just passed in the text "this.entity_id".

Is there new syntax for using the ID in things in auto-entities vs. monster-card that I have to use now? Or do I have to stick with monster-card until this use case can be supported by auto-entities?
