### ISSUE TITLE
Filtering op label doens't seem to work

### ISSUE THREAD

**Issue by VPelt** [thomasloven/lovelace-auto-entities#453]
I can't seem to use labels to exclude entities

`type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: sensor
      attributes:
        device_class: power
  exclude:
    - label: nolist
    - state: unknown
    - state: unavailable
sort:
  method: state
  reverse: true
  count: 10
  numeric: true
`

![Schermafbeelding 2024-07-03 170349](https://github.com/thomasloven/lovelace-auto-entities/assets/50661431/aad07f18-407f-4438-90e1-2801e9e19dd2)

![Schermafbeelding 2024-07-03 170417](https://github.com/thomasloven/lovelace-auto-entities/assets/50661431/fe1801d1-5ece-4816-9a61-db8b3117c3de)

**Comment by tomofdarkness** [comment]
I just tried to exclude things lebeled with "service" from my kid's dashboard so he can't turn off the router or the washing machine, but I see this behavior too -- filtering on label doesn't work as an exclude: or as a not:

**Comment by mljenkinsdotcom** [comment]
Same issue.  For example I am using this card and entities with the label "ignore" still populate on the view.

```yaml
type: custom:auto-entities
filter:
  include:
    - domain: light
      state: 'on'
      integration: insteon
      options:
        secondary_info: last-changed
    - domain: light
      state: 'on'
      integration: govee
      options:
        secondary_info: last-changed
    - domain: switch
      state: 'on'
      integration: tplink
      options:
        secondary_info: last-changed
    - domain: switch
      state: 'on'
      integration: insteon
      options:
        secondary_info: last-changed
  exclude:
    - area: Tag On
    - area: Tag On Bedroom
    - label: ignore
show_empty: true
card:
  type: entities
  title: Lights On
  state_color: true
sort:
  method: last_changed
  reverse: true
```

**Comment by mljenkinsdotcom** [comment]
Something to note, if anyone needs to INCLUDE items with labels, this can currently be done using a template like this to workaround the label filter issue:

```yaml
type: custom:auto-entities
card:
  type: entities
filter:
  template: '{{ label_entities(''ignore'') }}'
```

Where `ignore` is the label you want to include.  Unfortunately you cannot use a template to exclude items, so this doesn't help those like myself that want to exclude items based on a label.

**Comment by x4N70pHyLL** [comment]
Doesn't work for me as well.

What I noticed: Older labels do work, even when included in a new auto entities card. A newly created label does not, neither in include, nor in exclude.
The workaround with the template doesn't work for me as well.

**Comment by x4N70pHyLL** [comment]
Another note: It seems to work occasionally, I have no idea why. So using the label (for debugging I just have a filter "show all entities with this label") sometimes shows all the relevant entities (couple of times a day when looking at my dashboard), but most of the time it does not. Maybe this helps in analysis

**Comment by VPelt** [comment]
My bug report was explicitly for the exclude functionality. Include does seem te work/have a workaround available

**Comment by simllll** [comment]
Just ran into the same issue. Anything we can do to get this fixed?

**Comment by paranoidi** [comment]
Still broken, unable to remove unwanted elements with following very simple config.

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - options: {}
      entity_id: input_number.mod_*
  exclude:
    - options: {}
      label: slider
```
