### ISSUE TITLE
nested call 

### ISSUE THREAD

**Issue by NYFB8888** [thomasloven/lovelace-auto-entities#454]
I wonder is it possible to use auto-entities inside `auto-entities?`

`type: custom:auto-entities
card:
  type: custom:auto-entities
  card:
    type: entities
    title: Printer Toner Usage
  filter:
    include:
      - name: '*toner*'
    exclude: null
  sort:
    method: friendly_name
  show_empty: true

  title:Printer Statistic
filter:
  include:
    - device: '*MFC-L3750CDW*'
  exclude: null
sort:
  method: friendly_name
show_empty: true
`
I want to show sensor info associated with toner, drum etc. usage and I thought to use your concept but without success. After implementing the code above, I got information from all the printer's sensors.
Can you suggest a solution to my request?

**Comment by ildar170975** [comment]
1. The code you posted is unformatted & cannot be analysed. Can't you see it?
2. A simple example of "nested" cards:
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: group
      options:
        type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - group: this.entity_id
```
3. Since this is not a bug report or FR - suggest to close the issue & then ask similar questions in a [dedicated Community thread](https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801).
