### ISSUE TITLE
Margin space if show_empty: false after upd. 2024.7

### ISSUE THREAD

**Issue by Klaestrup** [thomasloven/lovelace-auto-entities#456]
After updating HA to 2024.7 I now have empty space (should be no space at all like before) if there are no entities present (with show_empty: false). 
Maybe some CSS styling needed, but I'm not sure.

**Comment by ildar170975** [comment]
2024.7.1
Cannot confirm.
```
  - title: 13x
    path: 13x
    cards:
      - &ref_0
        type: gauge
        entity: input_number.test_level_1
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: sun.sn
        show_empty: false
      - *ref_0
      - *ref_0
      - *ref_0
      - *ref_0
      - *ref_0
```
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/909696d5-ff76-4a9e-8826-81a6182b9535)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/5a25fb5e-5221-4186-9db8-ee0a5a688751)

**Comment by Klaestrup** [comment]
Okay, it seems that it only happens when the auto-entities card is within a vertical stack card.
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/61654382/c4e0d1b9-4bf7-4698-aea7-cd1f7d3f5b9a)

**Comment by ildar170975** [comment]
> within a vertical stack card

A similar case: place 3 conditional cards inside a vertical stack - and make these conditions "false".
Then you will still see a stack card with some empty area inside.
Means - not an `auto-entities`'s card issue.

**Comment by Klaestrup** [comment]
You're right that it does not seem to be an auto-entities issue - but again, it was not acting like that before the update.
So definitely a HA thing! ;-)

Thanks for your response!

**Comment by ildar170975** [comment]
> it was not acting like that before the update.

Do not think so.
```
views:
  - title: Home
    cards:
      - &ref_ae
        type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: sun.sn
        show_empty: false

      - &ref_button
        show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.virtual_switch_1

      - type: vertical-stack
        cards:
          - *ref_ae

      - *ref_button

      - type: vertical-stack
        cards:
          - *ref_ae
          - *ref_ae

      - *ref_button
```
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/fe28dda7-900c-4d14-b528-f6b2e9cf29a0)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/ef5594c4-0c3b-46d6-99e9-0d4988fa3bd5)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/dde44b0c-ce62-490d-a940-99be8f4d0728)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/71872483/48dd0bf8-5c43-4abb-a76e-184605ffb16e)
