### ISSUE TITLE
[Request] lovelace-auto-entities collapse

### ISSUE THREAD

**Issue by beckynet** [thomasloven/lovelace-auto-entities#458]
Is it possible to have a collapse after an optional number of entities, as we can find in custom:battery-state-card ?
I know there is count in sort. But count stop displaying result, collapse hide only and is more efficient to limit size of card.
thanks a lot

**Comment by igorsantos07** [comment]
I would say _no_, given this should be an option on the target card...

However, I wonder if a sort of "ellipsis" is possible, at least. It could be feasible if `auto-entities` limited the amount of entities given to the target card (as in `count`) + included a standard footer with "...and XX hidden entities" whenever `count` was hit.

**Comment by ildar170975** [comment]
> have a collapse after an optional number of entities

This is mainly applicable for Entities card as a target card.
The `auto-entities` card does not (& should not) depend on a particular target card - and hence should not have options only meaningful for SOME particular target card (same story about endless wishes like "add auto-name-ing option").

**Comment by dcapslock** [comment]
You can use [custom:expander-card](https://github.com/MelleD/lovelace-expander-card)  with title-card and card in expander being the same auto-entities card but with different `sort` options, using `count` in the title-card and then `first` in the card in the expander. Note: `first` counts from 0.

Example below. There will be a gap between the title-card and expanded, which can be styled out if desired with card_mod, included in the example (there is top/bottom padding of the entities #states div which gives rise to the gap). There are also options for expander-card whther to make the whole title card clickable - in this case I have styled the header-overlay to reduce the overlay height back to the expander arrow.

```yaml
type: custom:expander-card
clear-children: true
title-card-clickable: true
title-card-button-overlay: true
title-card:
  type: custom:auto-entities
  card:
    type: entities
    card_mod:
      style: |
        #states {
          padding: 16px 16px 8px 16px; /* 8px bottom to simulate entity row gap */
        }
  filter:
    include:
      - options: {}
        domain: light
    exclude: []
  sort:
    count: 5
style: |
  .header-overlay {
    height: unset !important;
  }
cards:
  - type: custom:auto-entities
    card:
      type: entities
      card_mod:
        style: |
          #states {
            padding: 0 16px 16px 16px; /* No padding at top to make seemless from title-card */
          }
    filter:
      include:
        - options: {}
          domain: light
      exclude: []
    sort:
      first: 5
```
