### ISSUE TITLE
Filter Doesnt work for Device Names with #1 #4 etc

### ISSUE THREAD

**Issue by comet424** [thomasloven/lovelace-auto-entities#460]
so i have some 3d Printers
devices are labeled
3D Printer #1 
3D Printer #2
3D Printer #3 
3D Printer #4 

when i setup the auto entries filter for device
```
type: custom:auto-entities
card:
  type: entities
  title: '3D Printer #2'
filter:
  include:
    - device: '3D Printer #2'
  exclude: []
```
using #2 and #3  works  
but filtering  #1  and #4   cant be auto added  it can be manually entered  normally with the enteries  but the filter cant detect  #1 #4
