### ISSUE TITLE
Regression? - Area filter doesn’t work for entities with no device

### ISSUE THREAD

**Issue by sbjzn** [thomasloven/lovelace-auto-entities#461]
Related: https://github.com/thomasloven/lovelace-auto-entities/issues/149

I'm facing this issue when entities are supplied by remote home-assistant (https://github.com/custom-components/remote_homeassistant/)

These entities do not have a device associated with them.
When I put a light entity in an area, it does not show in the auto-entities card, only entities with a device associated are shown.

Card config:
```
type: custom:auto-entities
card:
  type: entities
  title: Living Room
  show_header_toggle: true
  state_color: false
filter:
  include:
    - area: living_room
  exclude: []
layout_options:
  grid_columns: 4
  grid_rows: auto
```

Home Assistant version: 2024.7.4

**Comment by ildar170975** [comment]
Do not confirm.
There 2 entities with "Коридор" area - some `light` entity (associated with some device) & `input_boolean` (w/o device):
![изображение](https://github.com/user-attachments/assets/99bd336c-95df-4f78-a3d4-0913c73be5a5)

The card selects both:
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - area: Коридор
```
![изображение](https://github.com/user-attachments/assets/b19b3990-1006-473f-8da8-35ad972e269a)

Another case - let's create a new area & associate 2 helpers with it:
![изображение](https://github.com/user-attachments/assets/c866d849-88c5-458f-ab25-e896c06b0519)

And the cards again shows all entities:
![изображение](https://github.com/user-attachments/assets/f1516437-a6c9-4c89-afd2-7d042372349d)
