### ISSUE TITLE
Using two filters throws an error...

### ISSUE THREAD

**Issue by samedarkclouds** [thomasloven/lovelace-auto-entities#463]
I labeled my devices by function (i.e. "Shade"") Some things that are labeled  "Shade" are also "Group" because they are a group of shades.

If I want the shades that are only group I would 

```
filter:
 include:
    - label: 'shade'
      label: 'group'
```

But this throws a "duplicate key mapping."

Using "and, or, not" doesn't seem to work either. It does not throw an error, it just retunes no results:

```
filter:
  include:
    - label: 'shade'
      and:
        label: 'group'
```

So, this using labels to drill down in filters (my only real reason for them) pretty useless without making a bunch of accommodations that makes the whole point of labels pretty moot. Example, labeling ever single entities thats not in a group "not group" and putting it in exclude, but that means I need 20 not group labels because there is one group in the domain.

So, could you please consider making the and/or/not functions allow the duplicating Label Key? This would make the world a much better place!

Thanks.... Love your stuff.

**Comment by AlexLab** [comment]
Hey! sry if i missunderstand but i too tried to use 2 filters and it didn´t work, so i found this and tried a few things. These to options here:
```
filter: 
include:
    - integration: zha
      and:
        state: 'unavailable'

```
or 
```
filter:
 include:
    - integration: zha      
       state: 'unavailable
```
Didnt work for me either - no results or an error, but this worked:
```
    - integration: zha
      and:
        - state: 'unavailable'
```
This was also the only way combining 2 filters worked for me and not just seperatly filter all entities for filter 1 and then for filter 2.
