### ISSUE TITLE
Visibility control

### ISSUE THREAD

**Issue by oywino** [thomasloven/lovelace-auto-entities#468]
I have the following card yaml which gives a long list of the update state of all my integrations;
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: update
    - name: HA Current Version
    - name: HA Update Available
  exclude: []
sort:
  method: entity_id
  ignore_case: true
```
However, I only need to see each item (entity) in the list when an update is available. 
Is this possible to achieve?
(I have the card in the new sections view in HA 2024.10.2)
