### ISSUE TITLE
config.entity not working in card_mod for setting styles

### ISSUE THREAD

**Issue by royf007** [thomasloven/lovelace-auto-entities#469]
I'm trying to set the ha-icon styles within card_mod, based on the entity state.  Is this possible?  It works if I hard-code an entity name, but not when using config.entity .

My YAML is below.

```
square: false
type: grid
columns: 1
cards:
  - type: vertical-stack
    cards:
      - type: custom:auto-entities
        card:
          type: custom:bar-card
          card_mod:
            style: |
              ha-icon {
                {% if states (config.entity) | float > 100  %}
                  color: orange;
                {% else %}
                  color: red;
                {% endif %}
              }
         entities:
          - entity: sensor.main_ac_compressor_usage
            name: AC Main Compressor
            animation: true
            icon: mdi:flash
            positions:
              indicator: outside
            max: 3800
            severity:
              - color: Red
                from: 700
                to: 3800
              - color: Orange
                from: 400
                to: 699
              - color: Green
                from: 0
                to: 399
        filter:
          include: []
          exclude: []
        sort:
          method: state
          numeric: true
          reverse: true
        show_empty: false

```
