### ISSUE TITLE
Feature request: Improve sorting

### ISSUE THREAD

**Issue by zyp** [thomasloven/lovelace-auto-entities#47]
Hi, this is a double feature request, as there's two improvements to sorting I would like to see:

Firstly I would like to be able to sort by area.

Secondly I would like to be able to provide a list of sorting methods, so that entities that compares equally with the first method are sorted by the second method, and so on.

Combined, this will let me have entities appear room by room with each room sorted alphabetically.

**Comment by thomasloven** [comment]
In all honesty - do you remodel your house often enough to justify a dynamically updating list of rooms?

**Comment by zyp** [comment]
I'm not sure what point you're trying to make. I haven't asked for a list of rooms, I've asked for a list of entities sorted by which room they are assigned to.

**Comment by thomasloven** [comment]
What I mean is that the easiest way to do this would be to specify one area at a time:

```yaml
filter:
  include:
    - area: bedroom
      sort:
        method: name
    - area: kitchen
      sort:
        method: name
    - area: livingroom
      sort:
        method: name
```
and that you wouldn't have to change that list very often.
