### ISSUE TITLE
Does not inform inner stack about a Panel mode

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#470]
In Panel mode, stock cards (`vertical-stack`, `horizontal-stack`, `grid`) use a "ispanel" property to style themself properly.
For instance, this defines processing of borders & box-shadows:
https://github.com/home-assistant/frontend/blob/79ac2a72fa39636e628b10b7bd04dad7a4b59a15/src/panels/lovelace/cards/hui-stack-card.ts#L109
```
      :host([ispanel]) #root {
        --ha-card-border-radius: var(--restore-card-border-radius);
        --ha-card-border-width: var(--restore-card-border-width);
        --ha-card-box-shadow: var(--restore-card-border-shadow);
      }
```
When `auto-entities` is used with stacks in a Panel mode - it causes absence of borders.
Consider these 2 cards:
-- `grid` with `auto-entities`
-- grid
```
type: custom:auto-entities
card:
  type: grid
  square: false
  columns: 2
card_param: cards
filter:
  include:
    - &ref_card_1
      entity_id: sun.sun
      options:
        type: entity
        entity: this.entity_id
    - *ref_card_1
    - *ref_card_1
    - *ref_card_1
```
```
type: grid
square: false
columns: 2
cards:
  - &ref_card_2
    type: entity
    entity: sun.sun
  - *ref_card_2
  - *ref_card_2
  - *ref_card_2
```
Both cards properly shown in a masonry layout:
![image](https://github.com/user-attachments/assets/060862fd-6ae5-4914-b374-ab5e09cb95c1)

The 1s card (with `auto-entities`) in Panel mode - no borders are shown:
![image](https://github.com/user-attachments/assets/802861e4-9aba-4807-a8c5-051facbd004c)

The 2nd card in Panel mode - borders are shown:
![image](https://github.com/user-attachments/assets/64294626-7023-43fe-b35a-090cd4269674)
