### ISSUE TITLE
Filtering state not working properly with logbook card

### ISSUE THREAD

**Issue by mathgim** [thomasloven/lovelace-auto-entities#474]
Seems not to work properly on state filtering with the official logbook card.

```
type: custom:auto-entities
show_empty: false
card:
  type: logbook
  title: Logbook
  hours_to_show: 240
filter:
  include:
    - entity_id: binary_sensor.*contact
  exclude:
    - state: "off"
    - state: "unavailable"
```

This displays all states of my contact sensors. However, the same code with the entities card works properly.

**Comment by ildar170975** [comment]
What do you expect in this code:
```
type: custom:auto-entities
card:
  type: history-graph
filter:
  include:
    - entity_id: sun.sun
      state: above_horizon
```
?
Same thing. Not a bug, just a wrong use.
