### ISSUE TITLE
possible values for format: below options:

### ISSUE THREAD

**Issue by Klap-in** [thomasloven/lovelace-auto-entities#484]
There is the possibility to change the format of the state of the entities (a date in my case) with the `format` option in the `options:` option of the filters. I try to find which configuration values are possible for `format:`, but so far I could not find documentation or code that show these. 

Do you know them, or do you have a pointer where can I find the possible configuration values? So far I found `relative`, `date` and `datetime`.

```
  - type: custom:auto-entities
    card:
      show_name: true
      show_icon: true
      show_state: true
      type: glance
      state_color: false
    filter:
      include:
        - entity_id: sensor.afvalwijzer_gft
          options:
            format: relative
        - entity_id: sensor.afvalwijzer_papier
          options:
            format: date
        - entity_id: sensor.afvalwijzer_pmd
          options:
            format: datetime
    sort:
      attribute: days_until_collection_date
      method: attribute
      numeric: true
```
