### ISSUE TITLE
Sort by state using percentage gives unexpected sort order

### ISSUE THREAD

**Issue by thecreaser** [thomasloven/lovelace-auto-entities#485]
I have a card showing battery percentages.  All battery entities have attributes _state_class: measurement, unit_of_measurement: %, device_class: battery_ and have the string _battery_ in their entity ids and names.

Entities with 100% battery level seem to be sorted in the wrong position i.e. the 100% is treated as 1%
This happens irrespective of the sort order.

```
type: custom:auto-entities
card:
  type: entities
  title: Batteries
  state_color: true
  show_header_toggle: false
filter:
  include:
    - entity_id: sensor.*battery*
  exclude:
    - entity_id: sensor.*battery*state*
sort:
  method: state
  reverse: false
```

![Image](https://github.com/user-attachments/assets/509c6574-646d-42ad-8d4b-b377d89e926e)

**Comment by ildar170975** [comment]
Try with `numeric: true`:
```
type: custom:auto-entities
card:
  type: entities
  title: Batteries
  state_color: true
filter:
  include:
    - domain: sensor
      attributes:
        device_class: battery
sort:
  method: state
  numeric: true
  reverse: false
```
This is not a bug, this is a question.
Suggest to ask questions in Community: https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801.
