### ISSUE TITLE
icon color

### ISSUE THREAD

**Issue by dummbold** [thomasloven/lovelace-auto-entities#487]
There are some complicated workarounds out there how to set the icon color according to the state of a sensor. I am just looking for an easy way to give some icons inside a whole bunch of device sensors (mdi:water = ink level of printer ink) the according color of the ink. I selected the entities with the manufacturer's name as i only have on device from this manufacturer.

A statement like "icon-color" seems not to be existing. If I try using card-mod I always run into the trap that the card is dynamic and these statements are ignored.

Any Idea how to fix this?

**Comment by ildar170975** [comment]
This is not a bug , it is a question and I suggest you to use Community.

**Comment by wrybit** [comment]
Maybe something like that:

```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
filter:
  include:
    - options:
        card_mod:
          style: |
            :host {
              {% set val = states(config.entity) | int(0) %}
              color: {% if val < 30 %}red{% elif val < 60 %}orange{% elif val < 100 %}yellow{% else %}var(--primary-text-color){% endif %};
            }
```

It works for the row color .. could also work for an icon to my POV.
