### ISSUE TITLE
auto-entities not working for me

### ISSUE THREAD

**Issue by Oldertarl** [thomasloven/lovelace-auto-entities#488]
Let me first of all try to explain what the situation is 
I have an API that return a nice clean json with some values 
`{"ABT":{"ABT":44.267684700096},"XRP":{"XRP":376.11259500989996},"SLP":{"SLP":13.576539064630722},"SOL":{"SOL":497.43060954329997},"TRUMP":{"TRUMP":74.35098443979},"BTC":{"BTC":321.6749058}}`
(disclaimer actual values have been adjusted before posting)
In the configuration.yaml I am collecting the json via 

```
rest:
  - scan_interval: 5
    resource: https://<domain_name>/wallet.php
    sensor:
      - name: Crypto Prices
        value_template: '{{ value_json }}'
```

I created a dashboard card after adding the needed plugins 

```
type: custom:config-template-card
entities:
  - sensor.crypto_prices
card:
  type: custom:auto-entities
  card:
    type: entities
    title: Crypto Prices
  filter:
    include:
      - entity_id: sensor.crypto_prices
        options:
          type: custom:template-entity-row
          name: ""
        name: |
          name: >
            {{ key }}
          state: >
            {{ value }}
```

The only thing showing up on the card it the title "Crypto Prices"

I can see when auto-completing the entity that the json is in place and correctly received.
I also created a normal entity card, trying to show the values and this is working as expected.
Reason to use auto-entities for this, is when there is a new coin added to the portfolio, I want this to show up as well, on the updated card.

Any help getting this working is highly appreciated!
