### ISSUE TITLE
Cant use the Sensor card graph with this

### ISSUE THREAD

**Issue by MrCaspan** [thomasloven/lovelace-auto-entities#489]
You just get an error saying that you must state the entity for this type of card

```
Specify an entity from within the sensor domain
```

```
type: custom:auto-entities
card:
  type: sensor
  graph: line
filter:
  include:
    - label: Monthly Cost
  exclude: []
```
