### ISSUE TITLE
Can auto entities be used with plant-status?

### ISSUE THREAD

**Issue by AnderssonPeter** [thomasloven/lovelace-auto-entities#49]
Can i use this with a cart that does not have a entities attribute?
In my case i want to use it with [plant status](https://www.home-assistant.io/lovelace/plant-status/) but as it does not have a entities attribute i don't think i can?

**Comment by thomasloven** [comment]
This can be done with the help of [layout-card](https://github.com/thomasloven/lovelace-layout-card).
See the bottom of the readme.

**Comment by deveth0** [comment]
Just for the record, i stumbled upon this, thanks @thomasloven for the hint!

```
type: 'custom:auto-entities'
filter:
  include:
    - entity_id: 'plant*'
      options:
        type: plant-status
sort:
  method: name
  ignore_case: true
card:
  type: 'custom:layout-card'

```
