### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by erkr** [thomasloven/lovelace-auto-entities#490]
First thanks for this super nice card!.

I ran into an issue. Excluding a specific entity seems to fail. The config used:
```
filter:
  include:
    - name: attributes.device_class
      value: battery
  exclude:
    - entity_id: sensor.batteries_mobiles
```

The excluded entity is still included though

**Comment by ildar170975** [comment]
Actually, this code is wrong:
```
  include:
    - name: attributes.device_class
      value: battery
```
Should be
```
  include:
    - attributes:
        device_class: battery
```

**Comment by erkr** [comment]
@ildar170975 
Thanks, if I change that, it works indeed. Strange remains that my old code was also selecting the right entries

**Comment by ildar170975** [comment]
>  Strange remains that my old code was also selecting the right entries

Honestly have no idea how this can happen. But anyway we are supposed to use DOCUMENTED ways ))).
Consider closing the issue if resolved for clarity & less clutter in repo.

**Comment by erkr** [comment]
I concluded to fast. The new code doesn't work

**Comment by ildar170975** [comment]
Suggest to always check with stock cards.
Look at this:
```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include: &ref_include
        - attributes:
            device_class: carbon_dioxide
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include: *ref_include
      exclude:
        - entity_id: sensor.carbon_dioxide
```
![Image](https://github.com/user-attachments/assets/187e5f17-bfda-4e11-a244-03cc6f7e1586)
