### ISSUE TITLE
Area Script Not Included

### ISSUE THREAD

**Issue by wstrater** [thomasloven/lovelace-auto-entities#492]
I have tagged an `input_boolean` and a `script` with the `Office` area and only the `input_boolean` shows up when I include the area.

The following template in the Developer Tools Template:

```
{{ area_entities('Office') }}
```

Creates the following output:

```
['input_boolean.office_automations', 'script.override_office_automations']
```

The following configuration only shows the `input_boolean` entity:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - area: Office
  exclude: []
```

The following shows all `script` entities but is not what I want but does prove that the card can display `script` entities:

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: script
  exclude: []
```

I even tried various combinations of `include` with `domain` **AND** `area` or with `domain` **OR** `area`. The **AND** with the `domain` and `area` in the same block shows nothing. The **OR** with the `domain` and the `area` in separate blocks shows all scripts and the `input_boolean` entity. Adding the `exclude` removes all scripts including the one tagged with `Office`.

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - domain: script
    - area: Office
  exclude:
    - domain: script
      not:
        area: Office
```

The only one that works as I expect it is using `template`:

```
type: custom:auto-entities
card:
  type: entities
filter:
  template: "{{ area_entities('Office') }}"
  include: []
  exclude: []
```
