### ISSUE TITLE
Sort not displaying as expected

### ISSUE THREAD

**Issue by poldim** [thomasloven/lovelace-auto-entities#494]
For some reason, this creates a card that doesn't seem to sort as expected.  The sensor values are all just numbers (seconds) so it should be straightforward.  Any ideas what I'm doing wrong?

```yaml
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: ESPHome Device Uptime
  show_header_toggle: false
filter:
  include:
    - entity_id: sensor.*_uptime
  exclude:
    - state: "unavailable"
sort:
  method: state
  reverse: true
```

![Image](https://github.com/user-attachments/assets/e162cd88-4000-4a81-a6df-6ed21e038a05)
