### ISSUE TITLE
Is slicing `this.entity_id` possible?

### ISSUE THREAD

**Issue by RedNo7** [thomasloven/lovelace-auto-entities#497]
Hi,

I am trying to create a list of entities using `custom:multiple-entity-row` by slicing the auto-entities entity

```yaml
- type: custom:auto-entities
  card:
    type: entities
    title: Reset battery replaced
    show_header_toggle: false
  sort:
    method: entity_id
  filter:
    include:
      - entity_id: "sensor.*battery_plus"
        state: "<50"
        options:
          type: custom:multiple-entity-row
          entity: this.entity_id
          entities:

            # I want to slice `this.entity_id` on these 2 entities
            - entity: "'button.' ~ this.entity_id[7:-5] ~ '_replaced'"
              name: " "
              state_color: true
              icon: true
            - entity: "this.entity_id[-5] ~ 'last_replaced'"
              name: "Last replaced"
              format: date

            # to turn them into this format
            - entity: button.ensuite_battery_replaced
              name: " "
              state_color: true
              icon: true
            - entity: sensor.ensuite_battery_last_replaced
              name: "Last replaced"
              format: date

```
I've tried a bunch of ways (Javascriot style, jinja style, etc) but cannot make it work.  Is it possible?
