### ISSUE TITLE
Question - Combine auto-entities with secondaryinfo-entity-row

### ISSUE THREAD

**Issue by lociii** [thomasloven/lovelace-auto-entities#5]
secondaryinfo-entity-row (https://github.com/MizterB/lovelace-secondaryinfo-entity-row) provides a functionality to customize the secondary row of an entity. However the templating language provided by card-tools to secondaryinfo-entity-row requires the template to start with a fully qualified entity (with domain).
The problem in combination with auto-entities is that we don't know the entity.

```
- type: custom:auto-entities
  card:
    type: entities
    title: Docker
    show_header_toggle: false
  filter:
    include:
      - entity_id: "switch.ha_dockermon*"
        options:
          type: "custom:secondaryinfo-entity-row"
          secondary_info: "[[ whatever-comes-here ]]"
```

Is there any way auto-entities can support generating that template?
