### ISSUE TITLE
Attribute numeric sorting not working as expected

### ISSUE THREAD

**Issue by parrel** [thomasloven/lovelace-auto-entities#50]
Hi,

I have two entities with an attribute named `days_till` with a number of days. I want to have the least amount of days sorted to be on the top of my entity list. But it seems that my configuration is not working, because if I set `reverse: true` then the order does not change.

How can I debug this? Is my card config incorrect?

Thanks

One of the entities' state:
![image](https://user-images.githubusercontent.com/22742147/70175154-76ca4000-16d6-11ea-8913-ba991fdea8eb.png)

Card config: 
``` yaml
card:
  type: entities
filter:
  include:
    - entity_id: sensor.datum_*_bak_t
sort:
  attribute: days_till
  method: attribute
  numeric: true
type: 'custom:auto-entities'

```
