### ISSUE TITLE
How to show only the 3 moste consuming sensors ?

### ISSUE THREAD

**Issue by 0000Max0000** [thomasloven/lovelace-auto-entities#500]
Is there a way to filter out only the X most consuming sensors (for example 3) and not all of them ?

**Comment by mag1024** [comment]
```
sort:
  method: state
  reverse: true
  numeric: true
  count: 3
```
