### ISSUE TITLE
card map Error: Either show_all, entities, or geo_location_sources must be specified

### ISSUE THREAD

**Issue by lingfish** [thomasloven/lovelace-auto-entities#501]
### Version info
auto-entities v1.13.0

Home assistant:
Core 2025.3.3
Supervisor 2025.03.3
Operating System 14.2
Frontend 20250306.0

### Details
Up until recently, things had worked fine with auto entities.

I use this config to draw a map card:

```yaml
type: horizontal-stack
cards:
  - type: custom:auto-entities
    card:
      type: map
      hours_to_show: 24
      theme_mode: auto
    filter:
      include:
        - domain: zone
        - entity_id: person.fred
    show_empty: false
```

Now, randomly, when I go to this panel, I'm getting JS errors in the console:

```javascript
auto-entities.js?hac…g=1677445841130:172 
 card map Error: Either show_all, entities, or geo_location_sources must be specified
    at s.value (￼hui-map-card.ts:114:13)
    at s (￼create-element-base.ts:153:11)
    at ￼create-element-base.ts:209:12
    at d (￼create-element-base.ts:308:12)
    at l (￼create-element-base.ts:242:12)
    at Module.v (￼create-card-element.ts:106:3)
    at Gt.update_card (￼auto-entities.js?hac…7445841130:172:4213)
```

I thought it might be browser/cache issues, but the same thing happens in the Android app.

If I go to another view and back, it then seems to work.

**Comment by ildar170975** [comment]
Try this workaround:
```
...
  - type: custom:auto-entities
    card:
      type: map
      ...
    entities:
      - entity: person.fred
    filter:
      include:
        - domain: zone
    ...
```
