### ISSUE TITLE
Map card does not show entities

### ISSUE THREAD

**Issue by Cyberes** [thomasloven/lovelace-auto-entities#503]
![Image](https://github.com/user-attachments/assets/3124fddb-5dce-424d-b22b-6013560f1389)

The entities that should be shown on the map all display fine on the standalone (native) map.

Seems like a console error:

```
Uncaught (in promise) Error: Invalid LatLng object: (unknown, unknown)
    j LatLng.js:32
    H LatLng.js:123
    initialize Marker.js:112
    i Class.js:24
    s decorated_marker.ts:12
    value ha-map.ts:556
    value ha-map.ts:145
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value ha-map.ts:235
    value ha-map.ts:116
    connectedCallback scoped-custom-element-registry.js:248
    k lit-html.ts:1411
    $ lit-html.ts:1454
    g lit-html.ts:1563
    _$AI lit-html.ts:1384
    W lit-html.ts:2183
    update lit-element.ts:166
    performUpdate reactive-element.ts:1333
    scheduleUpdate reactive-element.ts:1262
    _$Ej reactive-element.ts:1237
    requestUpdate reactive-element.ts:1215
    set reactive-element.ts:731
    value hui-map-card.ts:132
    d create-element-base.ts:219
    promise callback*40249/d/< create-element-base.ts:214
    d create-element-base.ts:308
    l create-element-base.ts:242
    v create-card-element.ts:107
    value hui-card.ts:123
    value hui-card.ts:42
    value hui-section.ts:71
    _cards hui-section.ts:290
    value hui-section.ts:289
    value hui-section.ts:199
    value hui-section.ts:99
    performUpdate reactive-element.ts:1328
    scheduleUpdate reactive-element.ts:1262
LatLng.js:32:8
```

**Comment by ildar170975** [comment]
https://github.com/thomasloven/lovelace-auto-entities/issues/501

**Comment by Cyberes** [comment]
```yaml
type: custom:auto-entities
card:
  type: map
  theme_mode: auto
filter:
  include:
    - domain: device_tracker
      attributes:
        provider: FindMy (muehlt/home-assistant-findmy)
      options:
        secondary_info: last-updated
  exclude:
    - domain: device_tracker
      attributes:
        source_type: router
sort:
  method: entity_id
```

**Comment by ildar170975** [comment]
Try with
```
type: custom:auto-entities
card:
  type: map
  theme_mode: auto
filter:
  include:
    - domain: device_tracker
      attributes:
        source_type: gps
      options:
        secondary_info: last-updated
  exclude:
    - domain: device_tracker
      attributes:
        source_type: router
sort:
  method: entity_id
```

**Comment by ildar170975** [comment]
btw,
this is meaningless here:
```
      options:
        secondary_info: last-updated
```

**Comment by Cyberes** [comment]
Even just

```yaml
type: custom:auto-entities
card:
  type: map
  theme_mode: auto
filter:
  include:
    - domain: device_tracker
```

Doesn't display anything.
