### ISSUE TITLE
Add Unique based on a property

### ISSUE THREAD

**Issue by LiquidPT** [thomasloven/lovelace-auto-entities#507]
I have an auto entity card to post scores for my favorite teams using the ESPN TeamTracker integration and card:

```
type: custom:auto-entities
filter:
  include:
    - integration: teamtracker
      options:
        type: custom:teamtracker-card
        home_side: left
  exclude:
    - entity_id: sensor.team_tracker_f1
    - attributes:
        event_url: null
    - attributes:
        date: "> 18h ago"
    - attributes:
        date: < -24h ago
card:
  type: vertical-stack
show_empty: false
card_param: cards
sort:
  method: attribute
  attribute: date
```

The problem happens when 2 of my favorite teams play each other. I end up with duplicate cards on the dashboard, but they are separate entities (one for the home team and one for the away team). However, there is an "event_url" attribute (which has a game ID in it) that uniquely identifies the game and could be de-duped upon. 

This is possible but messy using templates and seems unreliable (if the list is empty, it doesn't always update with teams when pulling entities using just templates, but the above YAML seems solid).
