### ISSUE TITLE
Auto-entities disappears when placed inside conditional card and with show_empty: false

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [thomasloven/lovelace-auto-entities#508]
Current master version of `auto-entities`, placed inside conditional card and with show_empty: true, disappears after some time of having app/web opened. I'm able to force trigger the issue by pressing 3 dots on the top right of Lovelace and pressing Refresh. 

It works fine if I set `show_empty: true`. It also works fine with [v1.13.0](https://github.com/thomasloven/lovelace-auto-entities/releases/tag/v1.13.0)

My configuration:
```
      - type: conditional
        conditions:
          - entity: binary_sensor.display_night_cards
            state: "on"
        card:
          type: custom:auto-entities
          show_empty: false
          card:
            type: entities
            title: 'Zapalone światło:'
          filter:
            include:
              - domain: light
                state: "on"
                options:
                  tap_action:
                    action: toggle
                  show_state: false
              - entity_id: "switch.bathroom_mirror_switch"
                state: "on"
                options:
                  tap_action:
                    action: toggle
                  show_state: false
            exclude:
              - entity_id: "*_screen" 
```
