### ISSUE TITLE
filter of attribute current not working any longer?

### ISSUE THREAD

**Issue by criticallimit** [thomasloven/lovelace-auto-entities#509]
Updated to actual version my filter is no longer running.
```
type: custom:auto-entities
  filter:
    include:
      - domain: automation
        attributes:
          current: 1
     - domain: script
        attributes:
          current: 1
```
other attributes are working, current is not working any more
