### ISSUE TITLE
State_not sometime not working in Version 1.14.0

### ISSUE THREAD

**Issue by ClaymoreTech4** [thomasloven/lovelace-auto-entities#511]
![Image](https://github.com/user-attachments/assets/0ca7e101-ccf9-47a0-b910-3d7d411ce010)

`
type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: Nas Needs to Be Addressed
  show_header_toggle: false
filter:
  include:
    - entity_id: sensor.nas_drive_4_status
      state_not: "normal"
    - entity_id: sensor.nas_drive_5_status
      state_not: "normal"
    - entity_id: binary_sensor.backups_stale
      state_not: "off"
    - entity_id: sensor.nas_memory_usage_real
      state: ">= 75"
    - entity_id: sensor.nas_volume_1_status
      state_not: "normal"
    - entity_id: sensor.nas_cpu_utilization_total
      state: ">= 75"
    - entity_id: sensor.nas_volume_1_volume_used
      state: ">= 75"
    - entity_id: sensor.backup_state
      state_not: "backed_up"
sort:
  method: state
  numeric: true
  reverse: true
`

**Comment by thomasloven** [comment]
That's why it's not in the readme. And never has been.
You need to use an exclude filter or a `not:`

**Comment by bighippo999** [comment]
I've no idea how I found and used state_not if it's never been in the readme, but I've been seeing an entity for a few days when I shouldn't have been.
In case it helps anyone else, changing state_not to the following worked for me:
```
    - entity_id: sensor.diesel_heater_status
      state:
        not:
          - "Off"
          - Standby
          - unavailable
          - unknown
      options:
        name: Diesel Heater
        icon: mdi:radiator
        secondary_info: last-changed
```
