### ISSUE TITLE
After Update to 1.14.1 pollination calendar not working

### ISSUE THREAD

**Issue by NetRat88** [thomasloven/lovelace-auto-entities#512]
Unfortunately after update to 1.14.1 my pollination calendar is not working anymore an don't show any entries:

```

type: custom:auto-entities
card:
  type: grid
  columns: 1
  square: false
card_param: cards
filter:
  include:
    - name: Pollenflug*
      state: ">0"
      options:
        type: custom:mushroom-template-card
        primary: "{{state_attr('this.entity_id', 'friendly_name')}}"
        secondary: morgen {{state_attr('this.entity_id', 'state_tomorrow_desc')}}
        icon: "{{state_attr('this.entity_id', 'icon')}}"
        layout: horizontal
        icon_color: |-
          {% if states(config.entity) | float <= 1 %}
            green
          {% elif states(config.entity) | float <= 2 %}
            orange
          {% else %}
            red
          {% endif %}
        tap_action:
          action: more-info
          entity: camera.pollen
        hold_action:
          action: none
        double_tap_action:
          action: none
        multiline_secondary: true
  exclude: []
sort:
  method: state
  reverse: true
show_empty: false

```

Maybe you can see any incompatibility issues in my code?

Best regards

**Comment by francois-le-ko4la** [comment]
Hello @NetRat88,

Just my humble opinion, but part of this issue might be related to the this.entity_id parameter.
In my case, I had to include it in the past, but after updating to version 1.14.1, I removed it and everything works fine now.

**Comment by thomasloven** [comment]
Same base issue as #516

**Comment by Mariusthvdb** [comment]
> Hello [@NetRat88](https://github.com/NetRat88),
> 
> Just my humble opinion, but part of this issue might be related to the this.entity_id parameter. In my case, I had to include it in the past, but after updating to version 1.14.1, I removed it and everything works fine now.
> 
> Note: in my case the parameter was optional. In your card thats seems to be mandatory....

yes I noticed the same, a long standing config suddenly broke.

removing that `entity: this.entity_id` brought back the template-entity-rows
```
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
    filter:
      include:
        - entity_id: sensor.*_verjaardag
          <<: &options_full
            options:
              type: custom:template-entity-row
#               entity: this.entity_id
```
