### ISSUE TITLE
Attribute filter not working in exclude with 1.41.1

### ISSUE THREAD

**Issue by SukramJ** [thomasloven/lovelace-auto-entities#515]
This is working code from version 1.30.0, but faulis with 1.41.1.

```
type: vertical-stack
cards:
  - card:
      state_color: true
      title: eingeschaltete Lichter/Schalter
      type: entities
    filter:
      exclude:
        - state: "off"
        - state: unavailable
        - attributes:
            ignore_ui: true
        - integration: home_connect
      include:
        - domain: light
        - domain: switch
        - attributes:
            is_light: true
    show_empty: false
    sort:
      method: name
    type: custom:auto-entities
```

Entities with attribute  `ignore_ui: true` are not excluded from list.
