### ISSUE TITLE
Template indentation breaks after 1.14.x update

### ISSUE THREAD

**Issue by ThomasDeMarez** [thomasloven/lovelace-auto-entities#516]
Template indentations seem to be broken after upgrading to 1.14.1. 

All of my auto-entities layouts were blank after upgrading. I noticed that the `|-` templating tag no longer works and the `>-` should be used without the use of empty lines or code indentations.

Old way of templating
```yaml
secondary: |-
  {% from 'easy_time.jinja' import easy_time %}

  {% if states[entity] is defined and states[entity].last_changed > now() %}
    {{ easy_time(states[entity].last_changed, language='nl') }} geleden 
  {% endif %}
```

New (=broken) way of templating
```yaml
secondary: >-
  {% from 'easy_time.jinja' import easy_time %}
  {% if states[entity] is defined and states[entity].last_changed > now() %}
  {{ easy_time(states[entity].last_changed, language='nl') }} geleden 
  {% endif %}
```

The old way of templating is much cleaner and clearer, can we get this back?

<details>
<summary>Full card for reference</summary>

```yaml
type: custom:auto-entities
card:
  type: grid
  square: false
  columns: 2
card_param: cards
filter:
  include:
    - entity_id: binary_sensor.smoke_alarm_*_smoke
      options:
        type: custom:mushroom-template-card
        icon: mdi:smoke-detector-variant
        icon_color: "{% if is_state(entity, 'on') %} red {% else %} green {% endif %}"
        primary: "{{ area_name(entity) }}"
        secondary: >-
          {% from 'easy_time.jinja' import easy_time %}
          {% if states[entity] is defined and states[entity].last_changed > now() %}
          {{ easy_time(states[entity].last_changed, language='nl') }} geleden 
          {% endif %}
      sort:
        method: friendly_name
sort:
  method: state
  reverse: false
```
</details>
