### ISSUE TITLE
All cards return blank after 1.14.x

### ISSUE THREAD

**Issue by reylinux** [thomasloven/lovelace-auto-entities#519]
I have multiple cards that were working correctly in the previous versions, and they stopped showing anything after the update.
Below is one of the examples for a working light filter code.
```yaml
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 2
  title: Lights
card_param: cards
filter:
  include:
    - group: light.all_lights
      state: "on"
      options:
        type: custom:mushroom-light-card
        use_light_color: true
        show_brightness_control: true
        show_color_control: true
        layout: vertical
  exclude: []
show_empty: false
sort:
  method: entity_id
```

![Image](https://github.com/user-attachments/assets/e375ce74-7746-4987-80f1-17073a3ea62d)

**Comment by thomasloven** [comment]
This should be fixed in 1.14.2

**Comment by Alfamonk** [comment]
Same here. Nothing works anymore!!!!
And I already updated to 1.14.2...

**Comment by thomasloven** [comment]
Please update to 1.14.3 and verify in your browser console that that is the version that is running.

**Comment by reylinux** [comment]
Updated to 1.14.3 and can confirmed the cards are back. Thanks Thomas for quick fix!!

> Please update to 1.14.3 and verify in your browser console that that is the version that is running.

**Comment by oilid** [comment]
I have the same problem but still with 1.14.3. And yes the version 1.14.3 is running.
This is my card config which is/was working with 1.14.0 but not anymore with 1.14.3:
```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
	- entity_id: sensor.papiermull_datum
	  options:
		type: custom:multiple-entity-row
		entity: this.entity_id
		image: /local/muell/schwarz-blau.png
		name: Papiermüll
		entities:
		  - entity: sensor.papiermull
			name: false
			styles:
			  font-weight: bold
			  width: 75px
	- entity_id: sensor.plastikmull_datum
	  options:
		type: custom:multiple-entity-row
		entity: this.entity_id
		card_mod: null
		style:
		  hui-generic-entity-row $: |
			.text-content {
			  font-size: 20px;
			  color: red;
			}
		image: /local/muell/schwarz-gelb.png
		name: Plastikmüll
		entities:
		  - entity: sensor.plastikmull
			name: false
			styles:
			  font-weight: bold
			  width: 75px
	- entity_id: sensor.restmull_datum
	  options:
		type: custom:multiple-entity-row
		entity: this.entity_id
		image: /local/muell/schwarz.png
		name: Restmüll
		entities:
		  - entity: sensor.restmull
			name: false
			styles:
			  font-weight: bold
			  width: 75px
	- entity_id: sensor.biomull_datum
	  options:
		type: custom:multiple-entity-row
		entity: this.entity_id
		image: /local/muell/braun.png
		name: Biomüll
		entities:
		  - entity: sensor.biomull
			name: false
			styles:
			  font-weight: bold
			  width: 75px
	- entity_id: sensor.sperrmull_datum
	  options:
		type: custom:multiple-entity-row
		entity: this.entity_id
		image: /local/muell/sperrabfall.png
		name: Sperrmüll
		entities:
		  - entity: sensor.sperrmull
			name: false
			styles:
			  font-weight: bold
			  width: 75px
  exclude:
	- attributes:
		daysTo: '> 30'
sort:
  method: attribute
  attribute: daysTo
  numeric: true
```

Please fix it, thanks a lot!
