### ISSUE TITLE
Sorting by name broken

### ISSUE THREAD

**Issue by tadly** [thomasloven/lovelace-auto-entities#52]
Sorting by name seems to be super broken.

```
  - type: custom:auto-entities
    unique: true
    sort:
      method: 'name'
    card:
      title: Gaming
      type: entities
      show_header_toggle: false
    filter:
      include:
        - entity_id: script.living_room_play_*
```

This gives me the following result.
![image](https://user-images.githubusercontent.com/503647/70240674-f1926a00-176d-11ea-94af-fcfec9568aa9.png)

I also tried the following with no difference:
```
    sort:
      method: 'attribute'
      attribute: 'friendly_name'
```

`ignore_case` and `numeric` don't change anything either.

**Comment by thomasloven** [comment]
Can't reproduce. Are you sure you are using the latest version?

**Comment by tadly** [comment]
Yes, I am on the latest version.

I've created a full example for you to reproduce.
While creating it I noticed the order gets messed up only after customizing the entities.
Without the customization, the pure entity-ids are sorted properly.

````
# configuration.yaml

homeassistant:
  name: 'Home Assistant'

  customize:
    script.living_room_play_crosscode:
      friendly_name: 'Crosscode'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_eso:
      friendly_name: 'Elder Scrolls Online'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_ffxv:
      friendly_name: ' Final Fantasy'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_gw2:
      friendly_name: 'Guild Wars'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_monsterhunter:
      friendly_name: 'Monster Hunter'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_rocket_league:
      friendly_name: 'Rocket League'
      icon: 'mdi:gamepad-variant'
    script.living_room_play_skyrim:
      friendly_name: 'Skyrim'
      icon: 'mdi:gamepad-variant'

frontend:
config:
http:

lovelace:
  mode: yaml


script:
  living_room_play_crosscode:
      sequence: []
  living_room_play_eso:
      sequence: []
  living_room_play_ffxv:
      sequence: []
  living_room_play_gw2:
      sequence: []
  living_room_play_monsterhunter:
      sequence: []
  living_room_play_rocket_league:
      sequence: []
  living_room_play_skyrim:
      sequence: []
````
````
# ui-lovelace.yaml

resources:
  - url: /local/auto-entities.js
    type: module

views:
  - title: 'Gamging'
    cards:
    - type: custom:auto-entities
      unique: true
      sort: 'name'
      card:
        title: Gaming
        type: entities
        show_header_toggle: false
      filter:
        include:
          - entity_id: input_boolean.living_room_config_gaming_auto
          - entity_id: script.living_room_play_*
````
