### ISSUE TITLE
numeric sort order reversed from 1.14.x?

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#524]
seeing the order of entities being reversed compared to before

```
    sort:
      method: attribute
      attribute: days_until_collection_date
      numeric: true
```

<img width="549" alt="Image" src="https://github.com/user-attachments/assets/54c5f0d2-e806-47b0-9d88-a48fda361935" />

which now apparently requires the explicit

```
    sort:
      method: attribute
      attribute: days_until_collection_date
      numeric: true
      reverse: true
```

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/e5c4498d-4ebd-4f87-89d6-8dcb4c27c81a" />

As this is a long standing card (as are 1 or 2 others in my config), the change is surprising

maybe a long time bug being fixed ? ;-)
otoh, and tbh, this feels like a bug because one would expect the lowest number to be atop (as it was before)?
