### ISSUE TITLE
Only sort non explicite entities

### ISSUE THREAD

**Issue by tadly** [thomasloven/lovelace-auto-entities#53]
The following example will sort all entities by name. This makes sense given that the sort option is a global flag.
With monster cards however I had the ability to explicitly position entities while the ones determined by pattern where sorted alphabetically.

It'd be nice to have this option again.

```yaml
  - type: custom:auto-entities
    sort: 'name'
    card:
      title: Configuration
      type: entities
    filter:
      include:
        - entity_id: input_datetime.living_room_config_start_morning
        - entity_id: input_datetime.living_room_config_start_day
        - entity_id: input_datetime.living_room_config_start_evening
        - entity_id: '*living_room_config_*'
```
