### ISSUE TITLE
Exclude Entities which have never triggered no longer being excluded

### ISSUE THREAD

**Issue by Shaun-Harrison** [thomasloven/lovelace-auto-entities#530]
This is my card for displaying the most recently triggered automations, any automations that have not triggered were always excluded from this list

```
- type: custom:auto-entities
  card:
     type: entities
    show_header_toggle: false
  filter:
    exclude:
      - attributes:
          last_triggered: null
    include:
      - domain: automation
        options:
          secondary_info: last-triggered
```

With the latest release, this is now not working and the non triggered automations are now showing up in the list
