### ISSUE TITLE
Issue with tile card and template filter in 1.14.x

### ISSUE THREAD

**Issue by sebcou21** [thomasloven/lovelace-auto-entities#531]
I want to show a tile only if a template evaluates to true. The following was working fine prior to 1.14.x but it doesn't anymore.

```yaml
type: custom:auto-entities
show_empty: false
unique: true
card:
  type: tile
  entity: input_boolean.heating_dynamic_temperature_adjustment
  tap_action:
    action: toggle
filter:
  template: >
    {% set season = states('sensor.season') %} 
    {% set preset = state_attr('climate.heat_circuit_1', 'preset_mode') %} 
    {% if (season == 'spring' or season == 'autumn') and preset == 'program' %}  
      {{ 'true' }}
    {% endif %}
```

Did the behavior change or am I missing something obvious?

Thanks and great job by the way!
