### ISSUE TITLE
Unknown rule "value" in include filter 1

### ISSUE THREAD

**Issue by Borromini** [thomasloven/lovelace-auto-entities#539]
Updating to v1.15.0 seems to have broken something in my auto-entities card. I'm seeing this error:

![Image](https://github.com/user-attachments/assets/e9a68c68-c99e-4af9-b280-12996dffe080)

On HA 2025.5.1. Card YAML worked fine before this update:

```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  secondary_info: "{attributes.battery_type_and_quantity}"
  title: Batterijstatus
  round: 0
  colors:
    steps:
      - "#ff0000"
      - "#ffff00"
      - "#008000"
    gradient: true
  sort:
    by: state
filter:
  include:
    - integration: battery_notes
      domain: sensor
      attributes:
        device_class: battery
    - name: entity_id
      value: "*_battery_type"
    - name: Area
      value: "{area.name}"

```
