### ISSUE TITLE
tap_action not passing entity ID

### ISSUE THREAD

**Issue by bluesheep** [thomasloven/lovelace-auto-entities#54]
I don't think the auto-entities card is properly passing through the entity ID for tap_actions. But works fine for 'toggle's. Config is below - works for the lights (basic tap_action) but not for the scenes (complex tap_action). When I tap the scenes, every scene I have defined triggers.

```
      - type: vertical-stack
        title: Study
        cards:
          - type: custom:auto-entities
            card: 
              type: glance
              show_state: false
            filter: 
              include: 
                - domain: scene
                  entity_id: "scene.study*"
                  options:
                    tap_action: 
                      action: call-service
                      service: scene.turn_on
          - type: custom:auto-entities
            card: 
              type: glance
            filter: 
              include: 
                - area: "Study"
                  domain: light
                  options:
                    tap_action:
                      action: toggle
                - area: "Study"
                  domain: switch
```
