### ISSUE TITLE
Device filters replaced with empty "options: {}..."

### ISSUE THREAD

**Issue by brettmiller** [thomasloven/lovelace-auto-entities#545]
When adding filters for devices, include or exclude, after saving and reopening they have been replaced with:

```
    - options: {}
      device: ""
```

Original yaml:

```type: custom:auto-entities
card:
  type: custom:mini-graph-card
  hours_to_show: 48
  points_per_hour: 2
  line_width: 2
  font_size: 80
  height: 100
  smoothing: false
  group: true
  show:
    legend: true
    labels: true
    icon: true
filter:
  include:
    - or:
        - attributes:
            device_class: temperature
        - template: >
            {{states.climate |
            selectattr('attributes.current_temperature')|list}} 
        - device: /[Bb]az/
    - device: /[Ff]oo/
  exclude:
    - name: /[Pp]hone/
    - name: /[Ww]atch/
    - name: /[Ss]limey/
    - name: /[Kk][Bb][Nn][Aa]/
    - name: /[Oo]pen[Ww]eather/
    - name: /[Aa]ccu[Ww]eather/
    - name: /[Xx]1[Cc]/
    - name: /[Dd]isk/
    - device: /[Pp][Vv][Ee]/
    - device_manufacturer: Inovelli
sort:
  method: friendly_name
  numeric: true
layout_options:
  grid_columns: 4
  grid_rows: 6
```

Yaml after saving and reopening

```
type: custom:auto-entities
card:
  type: custom:mini-graph-card
  hours_to_show: 48
  points_per_hour: 2
  line_width: 2
  font_size: 80
  height: 100
  smoothing: false
  group: true
  show:
    legend: true
    labels: true
    icon: true
filter:
  include:
    - or:
        - attributes:
            device_class: temperature
        - template: >
            {{states.climate |
            selectattr('attributes.current_temperature')|list}} 
        - device: /[Bb]az/
    - options: {}
      device: ""
  exclude:
    - name: /[Pp]hone/
    - name: /[Ww]atch/
    - name: /[Ss]limey/
    - name: /[Kk][Bb][Nn][Aa]/
    - name: /[Oo]pen[Ww]eather/
    - name: /[Aa]ccu[Ww]eather/
    - name: /[Xx]1[Cc]/
    - name: /[Dd]isk/
    - options: {}
      device: ""
    - device_manufacturer: Inovelli
sort:
  method: friendly_name
  numeric: true
layout_options:
  grid_columns: 4
  grid_rows: 6

```

As a workaround it seems that using an `or:` does not cause the rewrite. 

```
exclude:
  - or:
     - device: /foo/
     - ...
```

**Comment by ildar170975** [comment]
You are using a misplaced “template” option. 
It cannot be inside “include”.

**Comment by brettmiller** [comment]
> You are using a misplaced “template” option. It cannot be inside “include”.

@ildar170975 good to know, that was an over site but not really relevant to the issue. With the template removed the issue still exists.

**Comment by brettmiller** [comment]
This is still an issue after https://github.com/thomasloven/lovelace-auto-entities/issues/545

**Comment by brettmiller** [comment]
#545 seems not to leave things broken any longer, but it is adding empty `- options: {}` after saving. 

Filter yaml as written
```
filter:
  include:
    - attributes:
        device_class: temperature
    - device: /[Ff]oo/
```

what it's converted to after saving
```
filter:
  include:
    - options: {}
      attributes:
        device_class: temperature
    - options: {}
      device: /[Ff]oo/
```
