### ISSUE TITLE
help with complex template

### ISSUE THREAD

**Issue by RedNo7** [thomasloven/lovelace-auto-entities#552]
Hi,

This template filter works very well to show what is in `group.unavailable_entities`
```yaml
            - type: custom:auto-entities
              show_empty: false
              card:
                type: entities
                show_header_toggle: false
              sort:
                method: name
              filter:
                  {%- for attr in states['group.unavailable_entities'].attributes.entity_id -%}
                    {{
                      {
                        'entity': attr,
                        'name': attr
                      }
                    }},
                  {%- endfor %}

```

But I would like to combine the above (as an exclude) to the following:
```yaml
              filter:
                include:
                  - state: "unavailable"
                  - state: "unknown"
                exclude:
                  - entity_id: sensor.unavailable_entities
                  - label: "ignored"
```

I.e. show all `unavailable` and `uknown` that do not have the label `ignored`, is not `sensor.unavailable_entities` and are not in `group.unavailable_entities`.

Is that possible?
