### ISSUE TITLE
Filtering Not Working

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#56]
I'm trying to filter a group of alexa audio players that are in a playing or paused state, but when I run the following, I see ALL devices in that group AND other media player devices in a play/paused state.

How do I do filtering where a device has to be in a particular group AND is in state playing OR state paused?

lt;dr Can you do and/or in include filtering?

```
card:
  type: entities
filter:
  include:
    - group: group.audio_players
      options:
        group: true
        hide:
          controls: true
          icon: true
          power: true
          source: true
        type: 'custom:mini-media-player'
    - state: paused
    - state: playing
type: 'custom:auto-entities'
```

**Comment by thomasloven** [comment]
From the readme:
> [...]
> Filters have the following options, and will match any entity fulfilling ALL options:
> [...]
> Include all entities that matches ALL options of ANY filter in the filter.include section.
> [...]
> Examples:
> [... several examples ...]

**Comment by broyuken** [comment]
That doesn’t answer my question, I need to filter if it is either playing or paused AND in a particular group in the same filter. I don’t want it showing up if it’s playing or paused but not in that group.

**Comment by thomasloven** [comment]
Then make two filters. One where it is in a group AND playing, and one where it is in a group AND paused.
It will display any entities that matches ALL options (i.e is in the group AND is playing, or is in the group AND is paused) for ANY filter (i.e. either is in the group AND is player OR is in the group AND is paused).

```yaml
filter:
  include:
    - group: mygroup
      state: playing
    - group: mygroup
      state: paused
```
