### ISSUE TITLE
Multiple filtering

### ISSUE THREAD

**Issue by Ralleberg** [thomasloven/lovelace-auto-entities#58]
Hi Thomas,
Is it possible to somehow have multiple filter to match before listing the entities?
As an example I want to list all the "domains: light" AND "area: livingroom" in my filtering. If I add these to as it is, it both list all the light entities and the entities which have been set to livingroom in the area.

**Comment by thomasloven** [comment]
Duplicate of #56

**Comment by netes** [comment]
It's not a duplicate, such option doesn't work, it displays nothing:
```yaml
type: 'custom:auto-entities'
card:
  type: entities
  title: Salon
filter:
  include:
    - area: Salon
      domain: light
```

Or am I doing something wrong?
