### ISSUE TITLE
FR: add last-triggered to sort options

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#59]
as title, please consider adding last-triggered to the sort option, which would be very nice to list (the most active) automations and scripts on a card.

thanks

**Comment by thomasloven** [comment]
Done.

**Comment by Mariusthvdb** [comment]
really sorry but neither:
the new 
```
  - type: custom:auto-entities
    card:
      type: entities
      title: All Automations auto
      show_header_toggle: false
    filter:
      include:
        - domain: automation
          options:
            secondary_info: last-triggered
    sort:
      method: last_triggered
```

nor the old:
```
  - type: custom:auto-entities
    card:
      type: entities
      title: All Automations auto
      show_header_toggle: false
    filter:
      include:
        - domain: automation
          options:
            secondary_info: last-triggered
    sort:
      method: attribute
      attribute: last_triggered
```

seem to work properly.
I see groups of sorted automations, but the full list of automations isn't ordered as one.
