### ISSUE TITLE
Option show_empty not working?

### ISSUE THREAD

**Issue by derandiunddasbo** [thomasloven/lovelace-auto-entities#6]
Is the show_empty option currently working? At least in my config it makes no difference, if it's set to true or false or not at all. The card is always hidden, if no entities match the filter:

```
card:
  show_header_toggle: false
  title: Offene Fenster und Türen
  type: entities
filter:
  exclude:
    - state: closed
    - state: locked
  include:
    - entity_id: /sensor\..*_fenster_status/
    - entity_id: /sensor\..*tur_status/
show_empty: true
type: 'custom:auto-entities'
```
I'm running HA version 0.87.0.

**Comment by derandiunddasbo** [comment]
Edit: The card seems to vanish only under certain circumstances, i.e. after shift-reloading the page in the browser or restarting HA. It reappears, when switching to another panel or view and back to the affected view.

**Comment by derandiunddasbo** [comment]
Edit 2: I retried this with other browsers. Chrome on android always shows the empty card.

But I also noticed, that Microsoft Edge doesn't load the plugin at all. Instead it shows an error in the UI ("`Custom element doesn't exist: auto-entities.`") and throws an error to the HA log, every time the page is loaded:
```
2019-02-15 11:14:31 ERROR (MainThread) [frontend.js.latest.201902030] https://hass.boerners.net:8123/local/plugins/auto-entities.js?v=1:12:64 Expected identifier, string or number
```
This is my plugin configuration:
```
name: Das Haus
resources:
  - type: js
    url: /local/plugins/card-tools.js?v=1
  - type: js
    url: /local/plugins/auto-entities.js?v=1
  - type: js
    url: /local/plugins/fold-entity-row.js?v=1
views:
  [...]
```
BTW: The fold-entity-row plugin is working fine in chrome as well as in edge.
