### ISSUE TITLE
Filter by attribute containing space in name

### ISSUE THREAD

**Issue by jacekpaszkowski** [thomasloven/lovelace-auto-entities#61]
Is it possible to define filter by attribute which name contains space?

Code below doesn't work.

```
card:
    show_header_toggle: false
    title: Mi temp
    type: entities
filter:
   include:
     - attributes:
          sensor type: LYWSDCGQ
```

**Comment by thomasloven** [comment]
Attributes *can't* have spaces. Check again.

**Comment by jacekpaszkowski** [comment]
Hi,
i use custom component which creates entities with attributes containing spaces (eg. "sensor type"). Please take a look

![image](https://user-images.githubusercontent.com/4264991/72053221-debc0980-32c6-11ea-8744-34cef2935e1a.png)

**Comment by jacekpaszkowski** [comment]
please see this thread https://github.com/custom-components/sensor.mitemp_bt/issues/24

and docs https://www.home-assistant.io/docs/configuration/state_object/

**Comment by thomasloven** [comment]
Honestly, that's stupid and user unfriendly. But it can be fixed.

**Comment by Dunky13** [comment]
@thomasloven  I'm sorry I'm commenting on this old issue, but I'm facing this issue on the latest version. Where I'm trying to read the attribute "Update available" being true. Please see attached

<img width="674" height="503" alt="Image" src="https://github.com/user-attachments/assets/fd2ea5a0-0963-42ae-9132-abf2bff13cb6" />
<img width="1003" height="488" alt="Image" src="https://github.com/user-attachments/assets/9c202fa4-b4eb-4911-8d58-442b16711bbd" />
<img width="1465" height="284" alt="Image" src="https://github.com/user-attachments/assets/d62a4a96-ce51-413e-93ce-d118ea575063" />

**Comment by dcapslock** [comment]
See https://github.com/thomasloven/lovelace-auto-entities/issues/154. This can't be fixed in auto-entities.

**Comment by dcapslock** [comment]
@Dunky13 A workaround for you using `eval_js` and hacking a `visibility` condition.

```yaml
type: custom:auto-entities
filter:
  include:
    - options:
        eval_js: true
        visibility:
          - condition: screen
            media_query: "(min-width: ${state.attributes['Update available'] ? 0 : 99999}px)"
        type: custom:mushroom-update-card
      entity_id: sensor.update_attributes_test
  exclude: []
card:
  type: grid
  square: false
show_empty: true
card_param: cards
```

EDIT: Note that when there is no updates for any entities, the card will be invisible in edit mode. You can always find in raw config editor
