### ISSUE TITLE
Enable templating for options

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-auto-entities#62]
I have a card that appears as follows:
```YAML
card:
  show_header_toggle: false
  type: entities
filter:
  exclude:
    - state: unknown
    - entity_id: sensor.withings_*kg*
  include:
    - entity_id: sensor.withings_*
ignorecase=True)|regex_replace(find='_', replace=' ') }}"
type: 'custom:auto-entities'
```
![image](https://user-images.githubusercontent.com/1435262/71944156-9f31e680-320e-11ea-8442-a275479f46c5.png)

It would be nice to enable tempting on the options to allow the person who is logged on to be able to have their entities filtered, and the name to be formatted such as:
```YAML
....
  include:
    - entity_id: "sensor.withings_*_{{ user.name }}"
      options:
        name: "{{ entity.name|regex_replace(find='^Withings\s*|\s*' + user.name + '\s*$', replace='', ignorecase=True)|regex_replace(find='_', replace=' ') }}"
....
```
If you are wondering about user ... can you make it support this also?? .. as would be good to filter by this.

Kris
