### ISSUE TITLE
FR: allow custom card like multiple-entity-row

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#64]
Hi,

trying to automate the setup, I was wondering if you could allow a custom card to be used, and have the advantages of that card over the native entities card be used with your auto-entities card.

https://github.com/benct/lovelace-multiple-entity-row

use case: have all the lights in the setup be shown with their respective brightness, colortemp and color values, on 1 single line

**Comment by thomasloven** [comment]
Sure. Go right ahead. Just put the type in the options, like with any other option.

**Comment by Mariusthvdb** [comment]
just for reference and saying thank you:

```
  - type: custom:auto-entities
    card:
      type: entities
      title: Multiple lights
      show_header_toggle: false
    filter:
      include:
        - domain: light
          state: 'on'
          attributes:
            rgb_color: '! none'
          options:
             type: custom:multiple-entity-row
             entity: this.entity_id
             toggle: true
             secondary_info: last-changed
             primary:
               entity: this.entity_id
               attribute: brightness
               name: Bri
               unit: '%'
             secondary:
               entity: this.entity_id
               attribute: rgb_color
               name: Rgb

        - domain: light
          state: 'on'
          attributes:
            color_temp: '! none'
          options:
             type: custom:multiple-entity-row
             entity: this.entity_id
             toggle: true
             secondary_info: last-changed
             primary:
               entity: this.entity_id
               attribute: brightness
               name: Bri
               unit: '%'
             secondary:
               entity: this.entity_id
               attribute: color_temp
               name: Color
```

**Comment by thomasloven** [comment]
>              entity: this.entity_id

I don't think this is necessary.

**Comment by Mariusthvdb** [comment]
you're right! thanks. 2 lines less:
<img width="451" alt="Schermafbeelding 2020-01-10 om 08 00 26" src="https://user-images.githubusercontent.com/33354141/72132471-52b9e880-337f-11ea-8050-b0cdfda5a5dd.png">

I'll edit my community post

**Comment by bcutter** [comment]
I was looking for exactly this: combining `auto-entities` with `multiple-entity-row`. BUT I need to show values from another entity not being included or directly related to the filter/include setting of `auto-entities`.

Use case:
- I have one switch entity and one sensor entity for one power device (smart plug).
- I want to show the current consumption (sensor value from separate entity) next to the switch status (from separate entity).
- Entities:
   1) `switch.plug_device1` --> part of include filter
   2) `sensor.plug_device1_current_consumption` --> this is what I would like to add by using `multiple-entity-row`.

Target (created manually with entities card):
![grafik](https://user-images.githubusercontent.com/13799156/133687589-57584461-1be7-4f09-b8ad-9452900152ac.png)

This is the corresponding yaml code:
```
      - type: custom:multiple-entity-row
        entity: switch.plug_device1
        name: ''
        toggle: true
        state_color: true
        show_state: true
        secondary_info: last-changed
        entities:
          - entity: sensor.plug_device1_current_consumption
            name: Aktuell
        state_header: ''
        column: false
```

**Is this possible?** (@thomasloven) Natively, with any tweaks or workarounds, ...

As I understand @Mariusthvdb above example the additional values shown als separate rows are from the same entity which is part of the include filter.

**Comment by Mariusthvdb** [comment]
I believe yes, but you'd probably need custom:decluttering card to create the main framework, and then use template-entity-row to select the entitynin the template and pass it on to the decluttering-card

like this:
```
default:
  - action: more-info
  - confirmation: false
  - toggle: true

card:
  type: custom:multiple-entity-row
  entity: switch.[[entity]]
  state_color: true
  toggle: '[[toggle]]'
  tap_action:
    action: '[[action]]'
    confirmation: '[[confirmation]]'
  hold_action:
    action: more-info
  secondary_info: last-changed
  entities:
    - entity: sensor.[[entity]]_actueel
      name: Actueel
      unit: Watt
    - entity: sensor.[[entity]]_totaal
      name: Totaal
      unit: kWh
  sort:
    method: name
```
