### ISSUE TITLE
Templating Support for Groups

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#67]
I'd like to see the ability to use groups in temples instead of just entity_id's. I'm looking to have an input select that lists my alexa whole home audio groups. Then when one is selected, it displays the volume sliders for the devices in that group. I'm not sure what's wrong with my templating, because none of the entity_id's are even showing up in the card, but it works in developer tools, but it only shows the entity_id not the members of the group. 

```
card:
  show_header_toggle: false
  title: Volume Control
  type: entities
filter:
  template: >
    {%if is_state('input_select.alexa_wha_groups','Everywhere')%}group.alexa_wha_everywhere{%endif%}
    {%if is_state('input_select.alexa_wha_groups','Everywhere but the Living Room')%}group.alexa_wha_everywhere_but_living_room{%endif%} 
{%if is_state('input_select.alexa_wha_groups','Downstairs')%}group.alexa_wha_downstairs{%endif%}
    {%if is_state('input_select.alexa_wha_groups','Upstairs')%}group.alexa_wha_upstairs{%endif%}
    {%if is_state('input_select.alexa_wha_groups','Master Bedroom')%}group.alexa_wha_master_bedroom{%endif%}
  include:
    - entity_id: input_select.alexa_wha_groups
show_empty: true
type: 'custom:auto-entities'

```

EDIT: Using one of the examples provided doesn't even seem to work. All I did was change the entity_id to be one of my own but the template does not work. The office light is 100% off

```
card:
  show_header_toggle: false
  title: Template Test
  type: entities
filter:
  template: |
    {%if is_state('light.office_light','off')%}light.office_light{%endif%}
show_empty: true
type: 'custom:auto-entities'
```
