### ISSUE TITLE
this.entity_id does not work!

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-auto-entities#68]
I have a card as follows that Lists the home members... and is also supposed to show the location of the user:
```YAML
card:
  show_header_toggle: false
  type: entities
filter:
  exclude:
    - state: unknown
  include:
    - attributes:
        home_member: true
      entity_id: device_tracker.*
      options:
        primary:
          entity: this.entity_id
          attribute: location
        type: 'custom:multiple-entity-row'
type: 'custom:auto-entities'
```
The problem is that this.entity_id is not working ... I imagine that it is going in as "this.entity_id" and not being replaced.
