### ISSUE TITLE
Cast doesn't work with auto-entities

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#69]
Casting the auto-entities card results in:

```
custom element doesn't exist auto-entities
```

seems independent of the type: card it uses for the Lovelace view. I have many with regular entities card, but also with custom:bar-card (which is Castable individually ) and custom:fold-entity-row (for which I have filed a separate issue)

simplest of cards erroring out:

```
  - type: custom:auto-entities
    card:
      title: Mobile app battery sensors
      type: entities
      show_header_toggle: false
    filter:
      include:
        - entity_id: 'sensor.*_battery_*'
      exclude:
        - entity_id: 'sensor.*ios_battery_*'
```

more complex with custom:bar-card:

```
type: custom:auto-entities
title: Actueel verbruik
card:
  type: custom:bar-card
  show_icon: true
  hue: 240
  saturation: 75%
  align: split
  rounding: 6px
  card_style:
#    background: "#AA00AA"
    border-radius: 6px
  icon_style:
    height: 60px
    width: 60px
    color: '#FF0000'
  title_style:
    color: '#00FF00'
    font-size: 10px
    text-transform: uppercase
    text-decoration: underline
    text-shadow: "0 0 10px #FF0000"
#      value_style:
#        color: '#FFFF00'
#        font-size: 22px
  severity:
    - value: 50
      color: '#bf4040'
    - value: 1500
      color: '#bf9540'
    - value: 2000
      color: '#40bf40'
  title_position: inside
  columns: 3
  padding: 2px
#      align: left
#      title_style:
#        font-size: 16px
  value_style:
    font-size: 8px
filter:
  include:
    - entity_id: 'sensor.*_actueel'
```

both doing their job just fine in regular Lovelace.

please have a look? thanks!
