### ISSUE TITLE
allow templates in filter: options?

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#71]
HI,

would you please consider as title:

```
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - domain: person
          options:
            type: custom:decluttering-card
            template: map_not_home
            variables:
              - name: '{{object_id}}'
              - naam: '{{attributes.friendly_name}}'
```

trying to solve: https://community.home-assistant.io/t/combining-auto-entities-and-decluttering-cards-challenge/162229 but cant use both filter template and regular filters?

thanks for having a look.

**Comment by Mariusthvdb** [comment]
or maybe allow the use of:

```
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - domain: person
          options:
            type: custom:decluttering-card
            template: map_not_home
            variables:
              - name: this.object_id
              - naam: this.attributes.friendly_name
```

current error on this is:

<img width="381" alt="Schermafbeelding 2020-01-13 om 08 41 21" src="https://user-images.githubusercontent.com/33354141/72240971-da089580-35e5-11ea-8d5b-d8c6e8083e89.png">

**Comment by Mariusthvdb** [comment]
getting back to my templating request, maybe a better example:

```
  - type: custom:auto-entities
    card:
      type: entities
      title: Multiple entities
      show_header_toggle: false
    filter:
      include:
        - entity_id: switch.sw*_template
          options:
            type: custom:multiple-entity-row
            state_color: true
            toggle: true
            secondary_info: last-changed
            entities:
              - entity: sensor.[[this.entity_id[10:-9]]]_actueel
                name: Actueel
                unit: Watt
              - entity: sensor.[[this.entity_id[10:-9]]]_totaal
                name: Totaal
                unit: kWh
          sort:
            method: name
```

trying to go from the entity_id in the auto_entities

switch.sw_kantoor_template

to 

sensor.kantoor_actueel and sensor.kantoor_totaal in the options of the multiple-entity-row card.

Hope this makes sense.
thanks for having a look if you would.

**Comment by thomasloven** [comment]
Auto-entities can't and shouldn't do everything, but it can be combined with something that does
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: switch*
      options:
        type: custom:some-custom-row-type-which-supports-the-wanted-functionality
```
