### ISSUE TITLE
What values are acceptable on secondary_info:

### ISSUE THREAD

**Issue by krasatos** [thomasloven/lovelace-auto-entities#73]
Hey, 
I'm trying to display my battery level as secondary info but i can't get it to work. 
```
filter:
  include:
    - attributes:
        battery_level: <50
      options:
        secondary_info: battery_level
```
Tried both with _ and - but nothing.
Is there any documentation about this somewhere?

Thanks in advance.
