### ISSUE TITLE
Accented characters in Friendly name won´t populate

### ISSUE THREAD

**Issue by palengh** [thomasloven/lovelace-auto-entities#77]
Tjena, Thomas!
I totally LOVE your contributions to Home Assistant. Thank you very much for your contribution!
I might have run into an issue using `Påls iPhone` as a devicename, using the Auto-entities card.

It will not populate. When using the kids device names, eg. `Sofies iPhone` it works as expected.

```
type: 'custom:auto-entities'
sort:
  method: domain
card:
  type: entities
  title: Påls iPhone
  show_header_toggle: false
filter:
  include:
    - device: Påls iPhone
```
