### ISSUE TITLE
Change Name in Filter

### ISSUE THREAD

**Issue by broyuken** [thomasloven/lovelace-auto-entities#79]
I have a bunch of temperature sensors that I would like to change the name of within an auto-entities card. The sensors are all named "Something Temperature"

Office Temperature
Living Room Temperature
etc.

I was hoping there could be a way to change the display name to remove the "Temperature" off the end because it looks messy and takes up too much room. 

I have the template set up to display the cards, but I can't figure out how to make the name change work with your card.

This template trims the name the way I want it to in the template editor, but I'm not sure how to put it in your card.
{{ states.sensor.*_temperature_sensor.attributes.friendly_name.split(" Temperature") [0]}}

**Comment by thomasloven** [comment]
Auto-entities can't and shouldn't do everything, but it can be combined with something that does
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: switch*
      options:
        type: custom:some-custom-row-type-which-supports-the-wanted-functionality
```
