### ISSUE TITLE
Have auto-entities sort with secondaryinfo-entity-row 

### ISSUE THREAD

**Issue by quammy** [thomasloven/lovelace-auto-entities#81]
Hi,
I hope it is the right place..
I'm trying to sort entities that are set to show through [https://github.com/custom-cards/secondaryinfo-entity-row](url). The auto-entities shows them, but without sorting.
This is a sample of what I've done and does not sort:

```
type: 'custom:auto-entities'
card:
  type: entities
  entities:
    - entity: sensor.a_birthday
      name: A's birthday
      secondary_info: >-
        Will turn [[ sensor.a_birthday.attributes.years_at_next_anniversary ]]
        in [[ sensor.a_birthday.attributes.weeks_remaining ]] weeks
      type: 'custom:secondaryinfo-entity-row'
    - entity: sensor.b_birthday
      name: B's birthday
      secondary_info: >-
        Will turn [[ sensor.b_birthday.attributes.years_at_next_anniversary ]]
        in [[ sensor.b_birthday.attributes.weeks_remaining ]] weeks
      type: 'custom:secondaryinfo-entity-row'
    - entity: sensor.c_birthday
      name: C's birthday
      secondary_info: >-
        Will turn [[ sensor.c_birthday.attributes.years_at_next_anniversary
        ]] in [[ sensor.c_birthday.attributes.weeks_remaining ]] weeks
      type: 'custom:secondaryinfo-entity-row'
title: Important dates
sort:
  method: state
  numeric: true
```

(the state is the amount of days till next birthday -> [https://github.com/pinkywafer/Anniversaries](url))

Thanks!

**Comment by thomasloven** [comment]
Auto-entities will only sort entities added by auto-entities filters.

**Comment by quammy** [comment]
At the end it works for me with ```type: 'custom:template-entity-row'```. Sorry for not updating this thread. This is the full working code:
```
card:
  show_header_toggle: false
  title: Important dates
  type: entities
entities:
  - entity: sensor.anniversary_a_birthday
    name: A's birthday
    secondary: >-
      Will turn {{state_attr(config.entity, 'years_at_next_anniversary')}} in
      {{state_attr(config.entity, 'weeks_remaining')}} weeks
    type: 'custom:template-entity-row'
  - entity: sensor.anniversary_B_birthday
    name: B's birthday
    secondary: >-
      Will turn {{state_attr(config.entity, 'years_at_next_anniversary')}} in
      {{state_attr(config.entity, 'weeks_remaining')}} weeks
    type: 'custom:template-entity-row'
  - entity: sensor.anniversary_C_birthday
    name: C's birthday
    secondary: >-
      Will turn {{state_attr(config.entity, 'years_at_next_anniversary')}} in
      {{state_attr(config.entity, 'weeks_remaining')}} weeks
    type: 'custom:template-entity-row'
filter:
  exclude: null
sort:
  method: state
  numeric: true
type: 'custom:auto-entities'
```
