### ISSUE TITLE
HASS 0.105.x -- Feature Request - state_color

### ISSUE THREAD

**Issue by tubalainen** [thomasloven/lovelace-auto-entities#84]
With the introduction of Home Assistant Core 0.105.x the automatic change of icon color has been removed and a parameter was added called `state_color`

For reference: (https://www.home-assistant.io/lovelace/entities/)

It would be great if this new feature could be added to this fantastic lovelace card. Thanks in advance! <3
![image](https://user-images.githubusercontent.com/26795429/74088282-e8d35280-4a94-11ea-913b-1d36674a9104.png)
![image](https://user-images.githubusercontent.com/26795429/74088288-fab4f580-4a94-11ea-9139-fe29006fb5a5.png)

**Comment by krkeegan** [comment]
Can't you do that already using the `options` attribute?

```
card:
  show_header_toggle: true
  title: Alla brytare
  type: entities
filter:
  exclude:
    - entity_id: switch.aeotec_zw080_siren_gen5_switch
    - entity_id: '*Passat*'
    - entity_id: swotch.on_off_sonoff_pow02
  include:
    - entity_id: switch.*
      options:
        state_color: true
show_empty: true
type: custom:auto-entities
```
