### ISSUE TITLE
Sorting with different types

### ISSUE THREAD

**Issue by TheLastProject** [thomasloven/lovelace-auto-entities#86]
Hey, love this card, but I have a bit of an issue I can't figure out how to work around.

I want to list all my battery levels, but sadly, Home Assistant is inconsistent here. Half of them are entities with an `device_type` attribute of `battery` and the battery percentage in the state. The other half are simply entities with a `battery_level` attribute.

Sadly, I can't find a way to sort both those filters together to have whatever device has the lowest battery level to be on top.

Any tips/ideas? I'm willing to try to code stuff in myself if needed (although JavaScript is not my main language)

**Comment by timbru31** [comment]
Have you ever solved this?

**Comment by TheLastProject** [comment]
Nope

**Comment by TheLastProject** [comment]
@timbru31 Not a true fix, but https://github.com/maxwroc/battery-state-card appeared in HACS which supports a list of entries to sort itself, so I can now automatically have all battery levels like this:

```
card:
card:
  title: Battery levels
  type: 'custom:battery-state-card'
  sort_by_level: asc
filter:
  include:
    - attributes:
        device_class: battery
    - attributes:
        battery_level: '>= 0'
type: 'custom:auto-entities'
```

So my exact issue is resolved due to a new card existing that can sort the entities itself, but I think this functionality could've still been nice to have.
