### ISSUE TITLE
Unable to filter media_player domain

### ISSUE THREAD

**Issue by pironic** [thomasloven/lovelace-auto-entities#9]
looks as though i can't set my card type to anything like 'media-control' or 'custom:mini-media-player' because 
```
mini-media-player Error: Specify an entity from within the media_player domain.
    at HTMLElement.setConfig (mini-media-player-bundle.js?v=1.0.2:1)
    at _createThing (card-tools.js?track=true&v=0:82)
    at Function.createThing (card-tools.js?track=true&v=0:112)
    at Function.createCard (card-tools.js?track=true&v=0:133)
    at HTMLElement.setConfig (auto-entities.js?v=be1323:12)
    at create_card_element_createElement (401352253e833b70a294.chunk.js:4823)
    at createCardElement (401352253e833b70a294.chunk.js:4823)
    at HTMLElement.createCardElement (401352253e833b70a294.chunk.js:5614)
    at config.cards.forEach (401352253e833b70a294.chunk.js:5693)
    at Array.forEach (<anonymous>)
```
or
```
hui-media-control-card Error: No entity specified
    at HTMLElement.setConfig (401352253e833b70a294.chunk.js:3896)
    at _createThing (card-tools.js?track=true&v=0:82)
    at Function.createThing (card-tools.js?track=true&v=0:112)
    at Function.createCard (card-tools.js?track=true&v=0:133)
    at HTMLElement.setConfig (auto-entities.js?v=be1323:12)
    at create_card_element_createElement (401352253e833b70a294.chunk.js:4823)
    at createCardElement (401352253e833b70a294.chunk.js:4823)
    at HTMLElement.createCardElement (401352253e833b70a294.chunk.js:5614)
    at config.cards.forEach (401352253e833b70a294.chunk.js:5693)
    at Array.forEach (<anonymous>)
```

I know that the error associates itself with card-tools but i think it just may be returning zero results from the filter in auto-entries. thus... opening the issue on this repo and not on card-tools.

Thanks for your help! love all the work you've put into lovelace. 

btw here is my lovelace card:

```
type: 'custom:auto-entities'
card:
  type: media-control
filter:
  include:
    - domain: media_player
```

**Comment by thomasloven** [comment]
Auto-entities works by populating the `entities:` field of the supplied card.
Media-control doesn't have an `entities:` field, but rather an `entit**y**:` field, so it won't work.

Auto-entities can't be used to create several cards at this point.

**Comment by pironic** [comment]
Thanks for the assistance! Makes total sense now.

**Comment by auredor** [comment]
It would be good to support it somehow ;-)

**Comment by thomasloven** [comment]
> Auto-entities can't be used to create several cards *at this point*.

**Comment by jes1417** [comment]
Thanks for this card I was really hoping this would help with my Plex on Xbox, it keys creating new players and I was hoping I could use this card to just display any player it so happens to use.

**Comment by k1rd3rf** [comment]
I have managed to make a workaround for this by using `entities` as type on the wrapper card and by adding a type as option (which will be appended on the card config for each entity):

```
type: custom:auto-entities
card:
  type: entities
  title: Media
  show_header_toggle: false
filter:
  include:
    - entity_id: "media_player.*"
      options:
        type: custom:mini-media-player
        artwork: cover
  exlude:
    - state: "unavailable"
```

See https://www.home-assistant.io/lovelace/entities/#options-for-entities

**Comment by thomasloven** [comment]
Or see the bottom here: https://github.com/thomasloven/lovelace-layout-card#a-few-tips

**Comment by Tiwing1** [comment]
A year+ later, but wanted to share a slightly different take on this - thanks to all the above for your previous posts! I've implemented like this, which only shows the cards that are playing or paused:

`type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
filter:
  include:
    - state: playing
      options:
        type: custom:mini-media-player
        artwork: cover
    - state: paused
      options:
        type: custom:mini-media-player
        artwork: cover
show_empty: false`

**Comment by natethelen** [comment]
I think this is how you had it formatted:
```yaml
type: custom:auto-entities
card:
  type: entities
  show_header_toggle: false
filter:
  include:
    - state: playing
      options:
        type: custom:mini-media-player
        artwork: cover
    - state: paused
      options:
        type: custom:mini-media-player
        artwork: cover
show_empty: false
```

BTW, you can use markdown to format the code and even specify that it is yaml for proper colorization.  Start it with this and then end it with 3 more backticks:
`` ```yaml``

**Comment by natethelen** [comment]
In case others come across this post and my config could help them...

I have a (likely relatively unique) setup where I have a bunch of Sonos Ports plugged into a matrix audio switcher that drives a bunch of rooms.  Nowadays you would just have 1 Port per room, but in my case the Sonos-es came later and the # of Ports would be cost prohibitive.  

I wanted a dynamic UI that would show just the rooms currently sourced to each Sonos so here is what I have per Sonos:
```yaml
type: entities
entities:
  - type: custom:mini-media-player
    entity: media_player.main_floor
    group: true
    info: short
    hide:
      volume: true
      power: true
      source: true
  - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - entity_id: media_player.*_speakers
          attributes:
            source: Main Floor Sonos
          options:
            type: custom:mini-media-player
            group: true
            toggle_power: false
            hide:
              controls: true
      sort:
        method: name
    show_empty: false
    unique: true
```

Then I have this to list out all the rooms that are not associated to a Sonos so I can easily assign them:
```yaml
type: custom:auto-entities
card:
  type: entities
  title: Unassigned Speakers
filter:
  include:
    - entity_id: media_player.*_speakers
      state: 'off'
      options:
        type: custom:mini-media-player
        group: true
        toggle_power: false
        hide:
          controls: true
      sort:
        method: name
show_empty: false
unique: true
```
