### ISSUE TITLE
Complex filter not working correctly

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-auto-entities#92]
I have the following:
``` yaml
    card:
      type: entities
    filter:
      exclude:
        - state: unknown
      include:
        - state: home
          attributes:
            home_member: true
          domain: device_tracker
          options:
            icon: 'mdi:home-account'
        - attributes:
            home_member: true
          not:
            state: home
            attributes:
              location: '!'
          domain: device_tracker
    sort:
      method: name
    type: 'custom:auto-entities'
```
It shows like this:
![image](https://user-images.githubusercontent.com/1435262/76180986-59dc6600-620b-11ea-935c-aa5e1ffc3fbe.png)

Data:
```
Damien:
  state: home
  home_member: true
  domain: device_tracker
Kris:
  state: not_home
  home_member: true
  domain: device_tracker
  location: Brisbane
Maria:
  state: not_home
  home_member: true
  domain: device_tracker
```

... The issues is, in the not bit:
- If I remove the attributes, the Damien with the person icon disappears
- When I remove the state bit, Kris disappears

**... shouldn't having both of the not conditions there remove both Damien and Kris?**
