### ISSUE TITLE
Allow options to be set with a template filter

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-auto-entities#93]
The current structure is floored as it doesn't allow multiple filters for templates

Current:
``` yaml
filter:
  template: <template>
  include:
    - <filter>
    - <filter>
  exclude:
    - <filter>
    - <filter>
```
Proposed:
``` yaml
filter:
  include:
    - <filter>
    - <filter>
  exclude:
    - <filter>
    - <filter>
```
With the filters being able to have a template specified within them...

This would allow options for each matched filter
e.g.:
```yaml
  include:
    - template: <template>
      options:
        # ...Options for template 1
    - template: <template>
      options:
        # ...Options for template 2
```
