### ISSUE TITLE
Feature request: ability to display an attribute value

### ISSUE THREAD

**Issue by wsw70** [thomasloven/lovelace-auto-entities#97]
Except if I missed something in the configuration, the only value which can be displayed in a card is the state.

There are some cases where the value of an attribute would have been a better choice. For instance, I generate entities from a homemade monitoring system and end up with entities such as 

![image](https://user-images.githubusercontent.com/1345886/77346135-06ebce00-6d36-11ea-9298-a056cb18319d.png)

I then filter all `homemonitor.*` for status `KO`

![image](https://user-images.githubusercontent.com/1345886/77346472-93968c00-6d36-11ea-9716-878c497b3641.png)

All the entities will display `KO` while it would be more interesting to display the value of the attribute `when` or `why`. ← this is the feature request :)

It would also be great if the name of the entity could be taken from the attributes as well (`HTTP → Seafile` instead of `http seafile` in the screenshot above)

**Comment by thomasloven** [comment]
DIsplay of the entities is up to whatever card you send the entity list to.
Auto-entities can't and shouldn't do everything, but it can be combined with something that does
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - entity_id: switch*
      options:
        type: custom:some-custom-row-type-which-supports-the-wanted-functionality
```
