### ISSUE TITLE
auto-entities/hui-media-control-card issue on 107.5 HA

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#98]
using:
```
 - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      title: Now Playing
      show_header_toggle : false
    filter:
      include:
        - domain: media_player
          state: /playing|paused|'on'/
          options:
            type: custom:hui-media-control-card
```

is no longer supported on core HA 107(.5)

resulting in 
<img width="357" alt="Schermafbeelding 2020-03-24 om 10 25 47" src="https://user-images.githubusercontent.com/33354141/77414825-e1a4a180-6dc1-11ea-905b-3edc9a54a72a.png">

workaround with the new card-preloader seems to be possible, but often show the red card nonetheless.

please have a look if this can be fixed?
thanks
